In [1]:
import os
import pandas as pd
from paper_processor import DocumentProcessor
from relevance_checker import RelevanceChecker
from affiliation_processor import AffiliationProcessor
from affiliation_matcher import AffiliationMatcher
from entropy_calculator import EntropyCalculator

import warnings
warnings.filterwarnings('ignore')

In [2]:
types = ['preprint', 'article']
start_date = "2018-10-01"
end_date = "2024-09-30"

processor = DocumentProcessor()
checker = RelevanceChecker()
matcher = AffiliationMatcher()
calculator = EntropyCalculator()

### Processing LLM papers
#### 1. Cleaning papers

In [3]:
df1 = processor.sample_documents('search-llm', 1)
print(f"The total number of downloaded papers: {len(df1)}")
df1 = processor.filter_by_date(df1, start_date, end_date)
print(f"The total number of papers after sorting date: {len(df1)}")
df1 = processor.filter_by_type(df1)
print(f"The total number of papers after filtering paper types: {len(df1)}")
df1 = processor.remove_exact_duplicates(df1)
print(f"The total number of papers after removing duplicates: {len(df1)}")
df1 = processor.remove_similar_documents(df1)
print(f"The total number of papers after potential duplicates: {len(df1)}")

The total number of downloaded papers: 177462
The total number of papers after sorting date: 167123
The total number of papers after filtering paper types: 128736
The total number of papers after removing duplicates: 107243

Processing preprints: 100%|██████████| 29113/29113 [01:32<00:00, 315.42it/s]

The total number of papers after potential duplicates: 100746

#### 2. Checking relevance

In [4]:
batch_size = 200
all_results = []
save_directory = "search-llm-relevance"
if not os.path.exists(save_directory):
    os.makedirs(save_directory)

for start_idx in range(0, len(df1), batch_size):
    batch_df = df1.iloc[start_idx:start_idx + batch_size]
    batch_number = start_idx // batch_size + 1
    batch_results = checker.check_papers(batch_df)
    batch_results.to_csv(f'{save_directory}/check_batch_{batch_number}.csv', index=False)
    all_results.append(batch_results)
    print(f"Batch {batch_number} processed and saved.")

df1 = pd.concat(all_results, ignore_index=True)

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 1 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 2 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 3 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 4 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 5 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 6 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 7 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 8 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 9 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 10 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 11 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 12 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 13 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 14 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 15 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 16 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 17 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 18 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 19 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 20 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 21 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 22 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:53<00:00,  1.76it/s]

Batch 23 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 24 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 25 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 26 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 27 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 28 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 29 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 30 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 31 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 32 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 33 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 34 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 35 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 36 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 37 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 38 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:57<00:00,  1.70it/s]

Batch 39 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 40 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 41 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 42 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 43 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 44 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 45 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 46 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 47 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 48 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 49 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 50 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 51 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 52 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 53 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 54 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 55 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 56 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 57 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 58 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 59 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 60 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 61 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 62 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 63 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 64 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:27<00:00,  2.30it/s]

Batch 65 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:26<00:00,  2.31it/s]

Batch 66 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 67 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 68 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:25<00:00,  2.35it/s]

Batch 69 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:25<00:00,  2.34it/s]

Batch 70 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 71 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 72 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 73 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 74 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 75 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 76 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 77 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 78 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 79 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 80 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 81 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 82 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 83 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 84 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 85 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 86 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 87 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 88 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 89 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 90 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 91 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 92 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 93 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 94 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 95 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 96 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 97 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 98 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 99 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 100 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 101 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 102 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 103 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 104 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 105 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 106 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 107 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 108 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 109 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 110 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 111 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 112 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 113 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 114 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 115 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 116 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 117 processed and saved.

Processing papers: 100%|██████████| 200/200 [03:58<00:00,  1.19s/it]

Batch 118 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 119 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 120 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 121 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 122 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 123 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 124 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 125 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 126 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 127 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 128 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 129 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 130 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 131 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.13it/s]

Batch 132 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:26<00:00,  2.32it/s]

Batch 133 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 134 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 135 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 136 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 137 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 138 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 139 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 140 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 141 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 142 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 143 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 144 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:26<00:00,  2.32it/s]

Batch 145 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 146 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:25<00:00,  2.34it/s]

Batch 147 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 148 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 149 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 150 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 151 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 152 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 153 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 154 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 155 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 156 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 157 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 158 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 159 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 160 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 161 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 162 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 163 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 164 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 165 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.13it/s]

Batch 166 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 167 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 168 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 169 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 170 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 171 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 172 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 173 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 174 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 175 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 176 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 177 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 178 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 179 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 180 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 181 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 182 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:26<00:00,  2.30it/s]

Batch 183 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 184 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.22it/s]

Batch 185 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.22it/s]

Batch 186 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:21<00:00,  2.46it/s]

Batch 187 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:26<00:00,  2.32it/s]

Batch 188 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:24<00:00,  2.35it/s]

Batch 189 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:23<00:00,  2.39it/s]

Batch 190 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:23<00:00,  2.39it/s]

Batch 191 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:25<00:00,  2.34it/s]

Batch 192 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:22<00:00,  2.43it/s]

Batch 193 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:26<00:00,  2.30it/s]

Batch 194 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:24<00:00,  2.36it/s]

Batch 195 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:26<00:00,  2.32it/s]

Batch 196 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 197 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.25it/s]

Batch 198 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 199 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:25<00:00,  2.33it/s]

Batch 200 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 201 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:20<00:00,  2.47it/s]

Batch 202 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 203 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 204 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 205 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:25<00:00,  2.33it/s]

Batch 206 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 207 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 208 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 209 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 210 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 211 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 212 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 213 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 214 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:27<00:00,  2.29it/s]

Batch 215 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 216 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 217 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 218 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 219 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 220 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 221 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 222 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 223 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 224 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 225 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 226 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 227 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 228 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 229 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 230 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 231 processed and saved.

Processing papers: 100%|██████████| 200/200 [06:01<00:00,  1.81s/it]

Batch 232 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 233 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 234 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 235 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 236 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 237 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 238 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 239 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 240 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 241 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 242 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 243 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 244 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 245 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 246 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 247 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 248 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 249 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 250 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 251 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 252 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 253 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 254 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 255 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 256 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 257 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 258 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 259 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 260 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 261 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 262 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 263 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 264 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 265 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 266 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 267 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 268 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 269 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 270 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 271 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 272 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 273 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 274 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 275 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 276 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 277 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 278 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 279 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 280 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 281 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 282 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 283 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 284 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 285 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 286 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 287 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 288 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 289 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 290 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 291 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 292 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 293 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 294 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 295 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 296 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 297 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 298 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 299 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 300 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 301 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 302 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 303 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.13it/s]

Batch 304 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 305 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 306 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 307 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 308 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 309 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 310 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 311 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 312 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 313 processed and saved.

Processing papers: 100%|██████████| 200/200 [02:08<00:00,  1.56it/s]

Batch 314 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 315 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 316 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 317 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 318 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 319 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 320 processed and saved.

Processing papers: 100%|██████████| 200/200 [02:03<00:00,  1.62it/s]

Batch 321 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 322 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 323 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 324 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 325 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 326 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 327 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 328 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 329 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 330 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 331 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 332 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 333 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 334 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 335 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 336 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:50<00:00,  1.82it/s]

Batch 337 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 338 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 339 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 340 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 341 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 342 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 343 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 344 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 345 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 346 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 347 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 348 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 349 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 350 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 351 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 352 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 353 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 354 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 355 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 356 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 357 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 358 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 359 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 360 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 361 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:27<00:00,  2.29it/s]

Batch 362 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 363 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 364 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 365 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 366 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 367 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 368 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 369 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 370 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 371 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 372 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 373 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 374 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 375 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 376 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 377 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 378 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 379 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 380 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 381 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 382 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 383 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 384 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 385 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 386 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 387 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 388 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 389 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 390 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 391 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 392 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 393 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:53<00:00,  1.76it/s]

Batch 394 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 395 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 396 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 397 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 398 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 399 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 400 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 401 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 402 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 403 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 404 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 405 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 406 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 407 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 408 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 409 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 410 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 411 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 412 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 413 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 414 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 415 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 416 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 417 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 418 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 419 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 420 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 421 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 422 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 423 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 424 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 425 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 426 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 427 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 428 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 429 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 430 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 431 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 432 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 433 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 434 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 435 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 436 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 437 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 438 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 439 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 440 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 441 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 442 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 443 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 444 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 445 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 446 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 447 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 448 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 449 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 450 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 451 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 452 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 453 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 454 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 455 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 456 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 457 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 458 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 459 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 460 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:55<00:00,  1.73it/s]

Batch 461 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 462 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 463 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 464 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 465 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 466 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 467 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 468 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 469 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 470 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 471 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 472 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 473 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 474 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 475 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 476 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 477 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 478 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 479 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 480 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 481 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 482 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 483 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 484 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 485 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 486 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 487 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 488 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 489 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 490 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 491 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 492 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 493 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 494 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 495 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 496 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 497 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 498 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 499 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 500 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 501 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 502 processed and saved.

Processing papers: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 503 processed and saved.

Processing papers: 100%|██████████| 146/146 [01:13<00:00,  1.99it/s]

Batch 504 processed and saved.

In [6]:
# Uncomment the code only if previous files are saved
# directory = 'search-llm-relevance'
# dataframes = []

# for filename in os.listdir(directory):
#     if filename.endswith('.csv'):
#         file_path = os.path.join(directory, filename)
#         df = pd.read_csv(file_path)
#         dataframes.append(df)
    
# df1 = pd.concat(dataframes, ignore_index=True)
# print(f"Total number of rows in combined DataFrame: {len(df1)}")

df1 = df1[df1['GPT_response']=='Yes']
print(f"The total number of papers after checking relevance: {len(df1)}")

df1.to_csv('llm-cleaned-samples.csv',index=False) #save file in case lose track of llm response

The total number of papers after checking relevance: 59239

#### 3. Extracting department information

In [12]:
save_directory = "llm-author-affiliations"

extractor = AffiliationProcessor(
    batch_size=200,
    save_directory=save_directory
)

affiliations1 = extractor.extract_affiliation(df1)
affiliations1 = extractor.prepare_prompt(affiliations1)
print(f"The total number of authors: {len(affiliations1)}")
extractor.process_batches(affiliations1)

The total number of authors: 61454

Processing batch 0: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 0 processed and saved to llm-author-affiliations/gpt_responses_batch_0.csv

Processing batch 1: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 1 processed and saved to llm-author-affiliations/gpt_responses_batch_1.csv

Processing batch 2: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 2 processed and saved to llm-author-affiliations/gpt_responses_batch_2.csv

Processing batch 3: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 3 processed and saved to llm-author-affiliations/gpt_responses_batch_3.csv

Processing batch 4: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 4 processed and saved to llm-author-affiliations/gpt_responses_batch_4.csv

Processing batch 5: 100%|██████████| 200/200 [01:56<00:00,  1.72it/s]

Batch 5 processed and saved to llm-author-affiliations/gpt_responses_batch_5.csv

Processing batch 6: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 6 processed and saved to llm-author-affiliations/gpt_responses_batch_6.csv

Processing batch 7: 100%|██████████| 200/200 [01:52<00:00,  1.77it/s]

Batch 7 processed and saved to llm-author-affiliations/gpt_responses_batch_7.csv

Processing batch 8: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 8 processed and saved to llm-author-affiliations/gpt_responses_batch_8.csv

Processing batch 9: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 9 processed and saved to llm-author-affiliations/gpt_responses_batch_9.csv

Processing batch 10: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 10 processed and saved to llm-author-affiliations/gpt_responses_batch_10.csv

Processing batch 11: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 11 processed and saved to llm-author-affiliations/gpt_responses_batch_11.csv

Processing batch 12: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 12 processed and saved to llm-author-affiliations/gpt_responses_batch_12.csv

Processing batch 13: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 13 processed and saved to llm-author-affiliations/gpt_responses_batch_13.csv

Processing batch 14: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 14 processed and saved to llm-author-affiliations/gpt_responses_batch_14.csv

Processing batch 15: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 15 processed and saved to llm-author-affiliations/gpt_responses_batch_15.csv

Processing batch 16: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 16 processed and saved to llm-author-affiliations/gpt_responses_batch_16.csv

Processing batch 17: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 17 processed and saved to llm-author-affiliations/gpt_responses_batch_17.csv

Processing batch 18: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 18 processed and saved to llm-author-affiliations/gpt_responses_batch_18.csv

Processing batch 19: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 19 processed and saved to llm-author-affiliations/gpt_responses_batch_19.csv

Processing batch 20: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 20 processed and saved to llm-author-affiliations/gpt_responses_batch_20.csv

Processing batch 21: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 21 processed and saved to llm-author-affiliations/gpt_responses_batch_21.csv

Processing batch 22: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 22 processed and saved to llm-author-affiliations/gpt_responses_batch_22.csv

Processing batch 23: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 23 processed and saved to llm-author-affiliations/gpt_responses_batch_23.csv

Processing batch 24: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 24 processed and saved to llm-author-affiliations/gpt_responses_batch_24.csv

Processing batch 25: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 25 processed and saved to llm-author-affiliations/gpt_responses_batch_25.csv

Processing batch 26: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 26 processed and saved to llm-author-affiliations/gpt_responses_batch_26.csv

Processing batch 27: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 27 processed and saved to llm-author-affiliations/gpt_responses_batch_27.csv

Processing batch 28: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 28 processed and saved to llm-author-affiliations/gpt_responses_batch_28.csv

Processing batch 29: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 29 processed and saved to llm-author-affiliations/gpt_responses_batch_29.csv

Processing batch 30: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 30 processed and saved to llm-author-affiliations/gpt_responses_batch_30.csv

Processing batch 31: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 31 processed and saved to llm-author-affiliations/gpt_responses_batch_31.csv

Processing batch 32: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 32 processed and saved to llm-author-affiliations/gpt_responses_batch_32.csv

Processing batch 33: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 33 processed and saved to llm-author-affiliations/gpt_responses_batch_33.csv

Processing batch 34: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 34 processed and saved to llm-author-affiliations/gpt_responses_batch_34.csv

Processing batch 35: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 35 processed and saved to llm-author-affiliations/gpt_responses_batch_35.csv

Processing batch 36: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 36 processed and saved to llm-author-affiliations/gpt_responses_batch_36.csv

Processing batch 37: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 37 processed and saved to llm-author-affiliations/gpt_responses_batch_37.csv

Processing batch 38: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 38 processed and saved to llm-author-affiliations/gpt_responses_batch_38.csv

Processing batch 39: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 39 processed and saved to llm-author-affiliations/gpt_responses_batch_39.csv

Processing batch 40: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 40 processed and saved to llm-author-affiliations/gpt_responses_batch_40.csv

Processing batch 41: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 41 processed and saved to llm-author-affiliations/gpt_responses_batch_41.csv

Processing batch 42: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 42 processed and saved to llm-author-affiliations/gpt_responses_batch_42.csv

Processing batch 43: 100%|██████████| 200/200 [02:26<00:00,  1.37it/s]

Batch 43 processed and saved to llm-author-affiliations/gpt_responses_batch_43.csv

Processing batch 44: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 44 processed and saved to llm-author-affiliations/gpt_responses_batch_44.csv

Processing batch 45: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 45 processed and saved to llm-author-affiliations/gpt_responses_batch_45.csv

Processing batch 46: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 46 processed and saved to llm-author-affiliations/gpt_responses_batch_46.csv

Processing batch 47: 100%|██████████| 200/200 [02:20<00:00,  1.42it/s]

Batch 47 processed and saved to llm-author-affiliations/gpt_responses_batch_47.csv

Processing batch 48: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 48 processed and saved to llm-author-affiliations/gpt_responses_batch_48.csv

Processing batch 49: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 49 processed and saved to llm-author-affiliations/gpt_responses_batch_49.csv

Processing batch 50: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 50 processed and saved to llm-author-affiliations/gpt_responses_batch_50.csv

Processing batch 51: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 51 processed and saved to llm-author-affiliations/gpt_responses_batch_51.csv

Processing batch 52: 100%|██████████| 200/200 [01:55<00:00,  1.73it/s]

Batch 52 processed and saved to llm-author-affiliations/gpt_responses_batch_52.csv

Processing batch 53: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 53 processed and saved to llm-author-affiliations/gpt_responses_batch_53.csv

Processing batch 54: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 54 processed and saved to llm-author-affiliations/gpt_responses_batch_54.csv

Processing batch 55: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 55 processed and saved to llm-author-affiliations/gpt_responses_batch_55.csv

Processing batch 56: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 56 processed and saved to llm-author-affiliations/gpt_responses_batch_56.csv

Processing batch 57: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 57 processed and saved to llm-author-affiliations/gpt_responses_batch_57.csv

Processing batch 58: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 58 processed and saved to llm-author-affiliations/gpt_responses_batch_58.csv

Processing batch 59: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 59 processed and saved to llm-author-affiliations/gpt_responses_batch_59.csv

Processing batch 60: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 60 processed and saved to llm-author-affiliations/gpt_responses_batch_60.csv

Processing batch 61: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 61 processed and saved to llm-author-affiliations/gpt_responses_batch_61.csv

Processing batch 62: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 62 processed and saved to llm-author-affiliations/gpt_responses_batch_62.csv

Processing batch 63: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 63 processed and saved to llm-author-affiliations/gpt_responses_batch_63.csv

Processing batch 64: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 64 processed and saved to llm-author-affiliations/gpt_responses_batch_64.csv

Processing batch 65: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 65 processed and saved to llm-author-affiliations/gpt_responses_batch_65.csv

Processing batch 66: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 66 processed and saved to llm-author-affiliations/gpt_responses_batch_66.csv

Processing batch 67: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 67 processed and saved to llm-author-affiliations/gpt_responses_batch_67.csv

Processing batch 68: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 68 processed and saved to llm-author-affiliations/gpt_responses_batch_68.csv

Processing batch 69: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 69 processed and saved to llm-author-affiliations/gpt_responses_batch_69.csv

Processing batch 70: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 70 processed and saved to llm-author-affiliations/gpt_responses_batch_70.csv

Processing batch 71: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 71 processed and saved to llm-author-affiliations/gpt_responses_batch_71.csv

Processing batch 72: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 72 processed and saved to llm-author-affiliations/gpt_responses_batch_72.csv

Processing batch 73: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 73 processed and saved to llm-author-affiliations/gpt_responses_batch_73.csv

Processing batch 74: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 74 processed and saved to llm-author-affiliations/gpt_responses_batch_74.csv

Processing batch 75: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 75 processed and saved to llm-author-affiliations/gpt_responses_batch_75.csv

Processing batch 76: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 76 processed and saved to llm-author-affiliations/gpt_responses_batch_76.csv

Processing batch 77: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 77 processed and saved to llm-author-affiliations/gpt_responses_batch_77.csv

Processing batch 78: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 78 processed and saved to llm-author-affiliations/gpt_responses_batch_78.csv

Processing batch 79: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 79 processed and saved to llm-author-affiliations/gpt_responses_batch_79.csv

Processing batch 80: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 80 processed and saved to llm-author-affiliations/gpt_responses_batch_80.csv

Processing batch 81: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 81 processed and saved to llm-author-affiliations/gpt_responses_batch_81.csv

Processing batch 82: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 82 processed and saved to llm-author-affiliations/gpt_responses_batch_82.csv

Processing batch 83: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 83 processed and saved to llm-author-affiliations/gpt_responses_batch_83.csv

Processing batch 84: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 84 processed and saved to llm-author-affiliations/gpt_responses_batch_84.csv

Processing batch 85: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 85 processed and saved to llm-author-affiliations/gpt_responses_batch_85.csv

Processing batch 86: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 86 processed and saved to llm-author-affiliations/gpt_responses_batch_86.csv

Processing batch 87: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 87 processed and saved to llm-author-affiliations/gpt_responses_batch_87.csv

Processing batch 88: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 88 processed and saved to llm-author-affiliations/gpt_responses_batch_88.csv

Processing batch 89: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 89 processed and saved to llm-author-affiliations/gpt_responses_batch_89.csv

Processing batch 90: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 90 processed and saved to llm-author-affiliations/gpt_responses_batch_90.csv

Processing batch 91: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 91 processed and saved to llm-author-affiliations/gpt_responses_batch_91.csv

Processing batch 92: 100%|██████████| 200/200 [02:15<00:00,  1.48it/s]

Batch 92 processed and saved to llm-author-affiliations/gpt_responses_batch_92.csv

Processing batch 93: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 93 processed and saved to llm-author-affiliations/gpt_responses_batch_93.csv

Processing batch 94: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 94 processed and saved to llm-author-affiliations/gpt_responses_batch_94.csv

Processing batch 95: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 95 processed and saved to llm-author-affiliations/gpt_responses_batch_95.csv

Processing batch 96: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 96 processed and saved to llm-author-affiliations/gpt_responses_batch_96.csv

Processing batch 97: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 97 processed and saved to llm-author-affiliations/gpt_responses_batch_97.csv

Processing batch 98: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 98 processed and saved to llm-author-affiliations/gpt_responses_batch_98.csv

Processing batch 99: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 99 processed and saved to llm-author-affiliations/gpt_responses_batch_99.csv

Processing batch 100: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 100 processed and saved to llm-author-affiliations/gpt_responses_batch_100.csv

Processing batch 101: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 101 processed and saved to llm-author-affiliations/gpt_responses_batch_101.csv

Processing batch 102: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 102 processed and saved to llm-author-affiliations/gpt_responses_batch_102.csv

Processing batch 103: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 103 processed and saved to llm-author-affiliations/gpt_responses_batch_103.csv

Processing batch 104: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 104 processed and saved to llm-author-affiliations/gpt_responses_batch_104.csv

Processing batch 105: 100%|██████████| 200/200 [01:50<00:00,  1.82it/s]

Batch 105 processed and saved to llm-author-affiliations/gpt_responses_batch_105.csv

Processing batch 106: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 106 processed and saved to llm-author-affiliations/gpt_responses_batch_106.csv

Processing batch 107: 100%|██████████| 200/200 [01:50<00:00,  1.80it/s]

Batch 107 processed and saved to llm-author-affiliations/gpt_responses_batch_107.csv

Processing batch 108: 100%|██████████| 200/200 [03:17<00:00,  1.01it/s]

Batch 108 processed and saved to llm-author-affiliations/gpt_responses_batch_108.csv

Processing batch 109: 100%|██████████| 200/200 [01:56<00:00,  1.71it/s]

Batch 109 processed and saved to llm-author-affiliations/gpt_responses_batch_109.csv

Processing batch 110: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 110 processed and saved to llm-author-affiliations/gpt_responses_batch_110.csv

Processing batch 111: 100%|██████████| 200/200 [01:58<00:00,  1.68it/s]

Batch 111 processed and saved to llm-author-affiliations/gpt_responses_batch_111.csv

Processing batch 112: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 112 processed and saved to llm-author-affiliations/gpt_responses_batch_112.csv

Processing batch 113: 100%|██████████| 200/200 [01:55<00:00,  1.74it/s]

Batch 113 processed and saved to llm-author-affiliations/gpt_responses_batch_113.csv

Processing batch 114: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 114 processed and saved to llm-author-affiliations/gpt_responses_batch_114.csv

Processing batch 115: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 115 processed and saved to llm-author-affiliations/gpt_responses_batch_115.csv

Processing batch 116: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 116 processed and saved to llm-author-affiliations/gpt_responses_batch_116.csv

Processing batch 117: 100%|██████████| 200/200 [01:46<00:00,  1.89it/s]

Batch 117 processed and saved to llm-author-affiliations/gpt_responses_batch_117.csv

Processing batch 118: 100%|██████████| 200/200 [01:50<00:00,  1.80it/s]

Batch 118 processed and saved to llm-author-affiliations/gpt_responses_batch_118.csv

Processing batch 119: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 119 processed and saved to llm-author-affiliations/gpt_responses_batch_119.csv

Processing batch 120: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 120 processed and saved to llm-author-affiliations/gpt_responses_batch_120.csv

Processing batch 121: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 121 processed and saved to llm-author-affiliations/gpt_responses_batch_121.csv

Processing batch 122: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 122 processed and saved to llm-author-affiliations/gpt_responses_batch_122.csv

Processing batch 123: 100%|██████████| 200/200 [01:56<00:00,  1.71it/s]

Batch 123 processed and saved to llm-author-affiliations/gpt_responses_batch_123.csv

Processing batch 124: 100%|██████████| 200/200 [01:54<00:00,  1.74it/s]

Batch 124 processed and saved to llm-author-affiliations/gpt_responses_batch_124.csv

Processing batch 125: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 125 processed and saved to llm-author-affiliations/gpt_responses_batch_125.csv

Processing batch 126: 100%|██████████| 200/200 [01:57<00:00,  1.70it/s]

Batch 126 processed and saved to llm-author-affiliations/gpt_responses_batch_126.csv

Processing batch 127: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 127 processed and saved to llm-author-affiliations/gpt_responses_batch_127.csv

Processing batch 128: 100%|██████████| 200/200 [01:50<00:00,  1.82it/s]

Batch 128 processed and saved to llm-author-affiliations/gpt_responses_batch_128.csv

Processing batch 129: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 129 processed and saved to llm-author-affiliations/gpt_responses_batch_129.csv

Processing batch 130: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 130 processed and saved to llm-author-affiliations/gpt_responses_batch_130.csv

Processing batch 131: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 131 processed and saved to llm-author-affiliations/gpt_responses_batch_131.csv

Processing batch 132: 100%|██████████| 200/200 [01:52<00:00,  1.77it/s]

Batch 132 processed and saved to llm-author-affiliations/gpt_responses_batch_132.csv

Processing batch 133: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 133 processed and saved to llm-author-affiliations/gpt_responses_batch_133.csv

Processing batch 134: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 134 processed and saved to llm-author-affiliations/gpt_responses_batch_134.csv

Processing batch 135: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 135 processed and saved to llm-author-affiliations/gpt_responses_batch_135.csv

Processing batch 136: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 136 processed and saved to llm-author-affiliations/gpt_responses_batch_136.csv

Processing batch 137: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 137 processed and saved to llm-author-affiliations/gpt_responses_batch_137.csv

Processing batch 138: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 138 processed and saved to llm-author-affiliations/gpt_responses_batch_138.csv

Processing batch 139: 100%|██████████| 200/200 [01:53<00:00,  1.76it/s]

Batch 139 processed and saved to llm-author-affiliations/gpt_responses_batch_139.csv

Processing batch 140: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 140 processed and saved to llm-author-affiliations/gpt_responses_batch_140.csv

Processing batch 141: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 141 processed and saved to llm-author-affiliations/gpt_responses_batch_141.csv

Processing batch 142: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 142 processed and saved to llm-author-affiliations/gpt_responses_batch_142.csv

Processing batch 143: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 143 processed and saved to llm-author-affiliations/gpt_responses_batch_143.csv

Processing batch 144: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 144 processed and saved to llm-author-affiliations/gpt_responses_batch_144.csv

Processing batch 145: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 145 processed and saved to llm-author-affiliations/gpt_responses_batch_145.csv

Processing batch 146: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 146 processed and saved to llm-author-affiliations/gpt_responses_batch_146.csv

Processing batch 147: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 147 processed and saved to llm-author-affiliations/gpt_responses_batch_147.csv

Processing batch 148: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 148 processed and saved to llm-author-affiliations/gpt_responses_batch_148.csv

Processing batch 149: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 149 processed and saved to llm-author-affiliations/gpt_responses_batch_149.csv

Processing batch 150: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 150 processed and saved to llm-author-affiliations/gpt_responses_batch_150.csv

Processing batch 151: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 151 processed and saved to llm-author-affiliations/gpt_responses_batch_151.csv

Processing batch 152: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 152 processed and saved to llm-author-affiliations/gpt_responses_batch_152.csv

Processing batch 153: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 153 processed and saved to llm-author-affiliations/gpt_responses_batch_153.csv

Processing batch 154: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 154 processed and saved to llm-author-affiliations/gpt_responses_batch_154.csv

Processing batch 155: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 155 processed and saved to llm-author-affiliations/gpt_responses_batch_155.csv

Processing batch 156: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 156 processed and saved to llm-author-affiliations/gpt_responses_batch_156.csv

Processing batch 157: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 157 processed and saved to llm-author-affiliations/gpt_responses_batch_157.csv

Processing batch 158: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 158 processed and saved to llm-author-affiliations/gpt_responses_batch_158.csv

Processing batch 159: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 159 processed and saved to llm-author-affiliations/gpt_responses_batch_159.csv

Processing batch 160: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 160 processed and saved to llm-author-affiliations/gpt_responses_batch_160.csv

Processing batch 161: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 161 processed and saved to llm-author-affiliations/gpt_responses_batch_161.csv

Processing batch 162: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 162 processed and saved to llm-author-affiliations/gpt_responses_batch_162.csv

Processing batch 163: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 163 processed and saved to llm-author-affiliations/gpt_responses_batch_163.csv

Processing batch 164: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 164 processed and saved to llm-author-affiliations/gpt_responses_batch_164.csv

Processing batch 165: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 165 processed and saved to llm-author-affiliations/gpt_responses_batch_165.csv

Processing batch 166: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 166 processed and saved to llm-author-affiliations/gpt_responses_batch_166.csv

Processing batch 167: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 167 processed and saved to llm-author-affiliations/gpt_responses_batch_167.csv

Processing batch 168: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 168 processed and saved to llm-author-affiliations/gpt_responses_batch_168.csv

Processing batch 169: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 169 processed and saved to llm-author-affiliations/gpt_responses_batch_169.csv

Processing batch 170: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 170 processed and saved to llm-author-affiliations/gpt_responses_batch_170.csv

Processing batch 171: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 171 processed and saved to llm-author-affiliations/gpt_responses_batch_171.csv

Processing batch 172: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 172 processed and saved to llm-author-affiliations/gpt_responses_batch_172.csv

Processing batch 173: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 173 processed and saved to llm-author-affiliations/gpt_responses_batch_173.csv

Processing batch 174: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 174 processed and saved to llm-author-affiliations/gpt_responses_batch_174.csv

Processing batch 175: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 175 processed and saved to llm-author-affiliations/gpt_responses_batch_175.csv

Processing batch 176: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 176 processed and saved to llm-author-affiliations/gpt_responses_batch_176.csv

Processing batch 177: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 177 processed and saved to llm-author-affiliations/gpt_responses_batch_177.csv

Processing batch 178: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 178 processed and saved to llm-author-affiliations/gpt_responses_batch_178.csv

Processing batch 179: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 179 processed and saved to llm-author-affiliations/gpt_responses_batch_179.csv

Processing batch 180: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 180 processed and saved to llm-author-affiliations/gpt_responses_batch_180.csv

Processing batch 181: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 181 processed and saved to llm-author-affiliations/gpt_responses_batch_181.csv

Processing batch 182: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 182 processed and saved to llm-author-affiliations/gpt_responses_batch_182.csv

Processing batch 183: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 183 processed and saved to llm-author-affiliations/gpt_responses_batch_183.csv

Processing batch 184: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 184 processed and saved to llm-author-affiliations/gpt_responses_batch_184.csv

Processing batch 185: 100%|██████████| 200/200 [01:53<00:00,  1.76it/s]

Batch 185 processed and saved to llm-author-affiliations/gpt_responses_batch_185.csv

Processing batch 186: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 186 processed and saved to llm-author-affiliations/gpt_responses_batch_186.csv

Processing batch 187: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 187 processed and saved to llm-author-affiliations/gpt_responses_batch_187.csv

Processing batch 188: 100%|██████████| 200/200 [01:53<00:00,  1.77it/s]

Batch 188 processed and saved to llm-author-affiliations/gpt_responses_batch_188.csv

Processing batch 189: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 189 processed and saved to llm-author-affiliations/gpt_responses_batch_189.csv

Processing batch 190: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 190 processed and saved to llm-author-affiliations/gpt_responses_batch_190.csv

Processing batch 191: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 191 processed and saved to llm-author-affiliations/gpt_responses_batch_191.csv

Processing batch 192: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 192 processed and saved to llm-author-affiliations/gpt_responses_batch_192.csv

Processing batch 193: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 193 processed and saved to llm-author-affiliations/gpt_responses_batch_193.csv

Processing batch 194: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 194 processed and saved to llm-author-affiliations/gpt_responses_batch_194.csv

Processing batch 195: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 195 processed and saved to llm-author-affiliations/gpt_responses_batch_195.csv

Processing batch 196: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 196 processed and saved to llm-author-affiliations/gpt_responses_batch_196.csv

Processing batch 197: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 197 processed and saved to llm-author-affiliations/gpt_responses_batch_197.csv

Processing batch 198: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 198 processed and saved to llm-author-affiliations/gpt_responses_batch_198.csv

Processing batch 199: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 199 processed and saved to llm-author-affiliations/gpt_responses_batch_199.csv

Processing batch 200: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 200 processed and saved to llm-author-affiliations/gpt_responses_batch_200.csv

Processing batch 201: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 201 processed and saved to llm-author-affiliations/gpt_responses_batch_201.csv

Processing batch 202: 100%|██████████| 200/200 [01:53<00:00,  1.77it/s]

Batch 202 processed and saved to llm-author-affiliations/gpt_responses_batch_202.csv

Processing batch 203: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 203 processed and saved to llm-author-affiliations/gpt_responses_batch_203.csv

Processing batch 204: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 204 processed and saved to llm-author-affiliations/gpt_responses_batch_204.csv

Processing batch 205: 100%|██████████| 200/200 [01:46<00:00,  1.89it/s]

Batch 205 processed and saved to llm-author-affiliations/gpt_responses_batch_205.csv

Processing batch 206: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 206 processed and saved to llm-author-affiliations/gpt_responses_batch_206.csv

Processing batch 207: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 207 processed and saved to llm-author-affiliations/gpt_responses_batch_207.csv

Processing batch 208: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 208 processed and saved to llm-author-affiliations/gpt_responses_batch_208.csv

Processing batch 209: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 209 processed and saved to llm-author-affiliations/gpt_responses_batch_209.csv

Processing batch 210: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 210 processed and saved to llm-author-affiliations/gpt_responses_batch_210.csv

Processing batch 211: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 211 processed and saved to llm-author-affiliations/gpt_responses_batch_211.csv

Processing batch 212: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 212 processed and saved to llm-author-affiliations/gpt_responses_batch_212.csv

Processing batch 213: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 213 processed and saved to llm-author-affiliations/gpt_responses_batch_213.csv

Processing batch 214: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 214 processed and saved to llm-author-affiliations/gpt_responses_batch_214.csv

Processing batch 215: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 215 processed and saved to llm-author-affiliations/gpt_responses_batch_215.csv

Processing batch 216: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 216 processed and saved to llm-author-affiliations/gpt_responses_batch_216.csv

Processing batch 217: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 217 processed and saved to llm-author-affiliations/gpt_responses_batch_217.csv

Processing batch 218: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 218 processed and saved to llm-author-affiliations/gpt_responses_batch_218.csv

Processing batch 219: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 219 processed and saved to llm-author-affiliations/gpt_responses_batch_219.csv

Processing batch 220: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 220 processed and saved to llm-author-affiliations/gpt_responses_batch_220.csv

Processing batch 221: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 221 processed and saved to llm-author-affiliations/gpt_responses_batch_221.csv

Processing batch 222: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 222 processed and saved to llm-author-affiliations/gpt_responses_batch_222.csv

Processing batch 223: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 223 processed and saved to llm-author-affiliations/gpt_responses_batch_223.csv

Processing batch 224: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 224 processed and saved to llm-author-affiliations/gpt_responses_batch_224.csv

Processing batch 225: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 225 processed and saved to llm-author-affiliations/gpt_responses_batch_225.csv

Processing batch 226: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 226 processed and saved to llm-author-affiliations/gpt_responses_batch_226.csv

Processing batch 227: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 227 processed and saved to llm-author-affiliations/gpt_responses_batch_227.csv

Processing batch 228: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 228 processed and saved to llm-author-affiliations/gpt_responses_batch_228.csv

Processing batch 229: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 229 processed and saved to llm-author-affiliations/gpt_responses_batch_229.csv

Processing batch 230: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 230 processed and saved to llm-author-affiliations/gpt_responses_batch_230.csv

Processing batch 231: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 231 processed and saved to llm-author-affiliations/gpt_responses_batch_231.csv

Processing batch 232: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 232 processed and saved to llm-author-affiliations/gpt_responses_batch_232.csv

Processing batch 233: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 233 processed and saved to llm-author-affiliations/gpt_responses_batch_233.csv

Processing batch 234: 100%|██████████| 200/200 [01:52<00:00,  1.79it/s]

Batch 234 processed and saved to llm-author-affiliations/gpt_responses_batch_234.csv

Processing batch 235: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 235 processed and saved to llm-author-affiliations/gpt_responses_batch_235.csv

Processing batch 236: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 236 processed and saved to llm-author-affiliations/gpt_responses_batch_236.csv

Processing batch 237: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 237 processed and saved to llm-author-affiliations/gpt_responses_batch_237.csv

Processing batch 238: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 238 processed and saved to llm-author-affiliations/gpt_responses_batch_238.csv

Processing batch 239: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 239 processed and saved to llm-author-affiliations/gpt_responses_batch_239.csv

Processing batch 240: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 240 processed and saved to llm-author-affiliations/gpt_responses_batch_240.csv

Processing batch 241: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 241 processed and saved to llm-author-affiliations/gpt_responses_batch_241.csv

Processing batch 242: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 242 processed and saved to llm-author-affiliations/gpt_responses_batch_242.csv

Processing batch 243: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 243 processed and saved to llm-author-affiliations/gpt_responses_batch_243.csv

Processing batch 244: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 244 processed and saved to llm-author-affiliations/gpt_responses_batch_244.csv

Processing batch 245: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 245 processed and saved to llm-author-affiliations/gpt_responses_batch_245.csv

Processing batch 246: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 246 processed and saved to llm-author-affiliations/gpt_responses_batch_246.csv

Processing batch 247: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 247 processed and saved to llm-author-affiliations/gpt_responses_batch_247.csv

Processing batch 248: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 248 processed and saved to llm-author-affiliations/gpt_responses_batch_248.csv

Processing batch 249: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 249 processed and saved to llm-author-affiliations/gpt_responses_batch_249.csv

Processing batch 250: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 250 processed and saved to llm-author-affiliations/gpt_responses_batch_250.csv

Processing batch 251: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 251 processed and saved to llm-author-affiliations/gpt_responses_batch_251.csv

Processing batch 252: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 252 processed and saved to llm-author-affiliations/gpt_responses_batch_252.csv

Processing batch 253: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 253 processed and saved to llm-author-affiliations/gpt_responses_batch_253.csv

Processing batch 254: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 254 processed and saved to llm-author-affiliations/gpt_responses_batch_254.csv

Processing batch 255: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 255 processed and saved to llm-author-affiliations/gpt_responses_batch_255.csv

Processing batch 256: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 256 processed and saved to llm-author-affiliations/gpt_responses_batch_256.csv

Processing batch 257: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 257 processed and saved to llm-author-affiliations/gpt_responses_batch_257.csv

Processing batch 258: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 258 processed and saved to llm-author-affiliations/gpt_responses_batch_258.csv

Processing batch 259: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 259 processed and saved to llm-author-affiliations/gpt_responses_batch_259.csv

Processing batch 260: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 260 processed and saved to llm-author-affiliations/gpt_responses_batch_260.csv

Processing batch 261: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 261 processed and saved to llm-author-affiliations/gpt_responses_batch_261.csv

Processing batch 262: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 262 processed and saved to llm-author-affiliations/gpt_responses_batch_262.csv

Processing batch 263: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 263 processed and saved to llm-author-affiliations/gpt_responses_batch_263.csv

Processing batch 264: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 264 processed and saved to llm-author-affiliations/gpt_responses_batch_264.csv

Processing batch 265: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 265 processed and saved to llm-author-affiliations/gpt_responses_batch_265.csv

Processing batch 266: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 266 processed and saved to llm-author-affiliations/gpt_responses_batch_266.csv

Processing batch 267: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 267 processed and saved to llm-author-affiliations/gpt_responses_batch_267.csv

Processing batch 268: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 268 processed and saved to llm-author-affiliations/gpt_responses_batch_268.csv

Processing batch 269: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 269 processed and saved to llm-author-affiliations/gpt_responses_batch_269.csv

Processing batch 270: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 270 processed and saved to llm-author-affiliations/gpt_responses_batch_270.csv

Processing batch 271: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 271 processed and saved to llm-author-affiliations/gpt_responses_batch_271.csv

Processing batch 272: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 272 processed and saved to llm-author-affiliations/gpt_responses_batch_272.csv

Processing batch 273: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 273 processed and saved to llm-author-affiliations/gpt_responses_batch_273.csv

Processing batch 274: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 274 processed and saved to llm-author-affiliations/gpt_responses_batch_274.csv

Processing batch 275: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 275 processed and saved to llm-author-affiliations/gpt_responses_batch_275.csv

Processing batch 276: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 276 processed and saved to llm-author-affiliations/gpt_responses_batch_276.csv

Processing batch 277: 100%|██████████| 200/200 [01:50<00:00,  1.80it/s]

Batch 277 processed and saved to llm-author-affiliations/gpt_responses_batch_277.csv

Processing batch 278: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 278 processed and saved to llm-author-affiliations/gpt_responses_batch_278.csv

Processing batch 279: 100%|██████████| 200/200 [01:46<00:00,  1.89it/s]

Batch 279 processed and saved to llm-author-affiliations/gpt_responses_batch_279.csv

Processing batch 280: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 280 processed and saved to llm-author-affiliations/gpt_responses_batch_280.csv

Processing batch 281: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 281 processed and saved to llm-author-affiliations/gpt_responses_batch_281.csv

Processing batch 282: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 282 processed and saved to llm-author-affiliations/gpt_responses_batch_282.csv

Processing batch 283: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 283 processed and saved to llm-author-affiliations/gpt_responses_batch_283.csv

Processing batch 284: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 284 processed and saved to llm-author-affiliations/gpt_responses_batch_284.csv

Processing batch 285: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 285 processed and saved to llm-author-affiliations/gpt_responses_batch_285.csv

Processing batch 286: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 286 processed and saved to llm-author-affiliations/gpt_responses_batch_286.csv

Processing batch 287: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 287 processed and saved to llm-author-affiliations/gpt_responses_batch_287.csv

Processing batch 288: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 288 processed and saved to llm-author-affiliations/gpt_responses_batch_288.csv

Processing batch 289: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 289 processed and saved to llm-author-affiliations/gpt_responses_batch_289.csv

Processing batch 290: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 290 processed and saved to llm-author-affiliations/gpt_responses_batch_290.csv

Processing batch 291: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 291 processed and saved to llm-author-affiliations/gpt_responses_batch_291.csv

Processing batch 292: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 292 processed and saved to llm-author-affiliations/gpt_responses_batch_292.csv

Processing batch 293: 100%|██████████| 200/200 [01:26<00:00,  2.31it/s]

Batch 293 processed and saved to llm-author-affiliations/gpt_responses_batch_293.csv

Processing batch 294: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 294 processed and saved to llm-author-affiliations/gpt_responses_batch_294.csv

Processing batch 295: 100%|██████████| 200/200 [02:05<00:00,  1.60it/s]

Batch 295 processed and saved to llm-author-affiliations/gpt_responses_batch_295.csv

Processing batch 296: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 296 processed and saved to llm-author-affiliations/gpt_responses_batch_296.csv

Processing batch 297: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 297 processed and saved to llm-author-affiliations/gpt_responses_batch_297.csv

Processing batch 298: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 298 processed and saved to llm-author-affiliations/gpt_responses_batch_298.csv

Processing batch 299: 100%|██████████| 200/200 [01:26<00:00,  2.30it/s]

Batch 299 processed and saved to llm-author-affiliations/gpt_responses_batch_299.csv

Processing batch 300: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 300 processed and saved to llm-author-affiliations/gpt_responses_batch_300.csv

Processing batch 301: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 301 processed and saved to llm-author-affiliations/gpt_responses_batch_301.csv

Processing batch 302: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 302 processed and saved to llm-author-affiliations/gpt_responses_batch_302.csv

Processing batch 303: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 303 processed and saved to llm-author-affiliations/gpt_responses_batch_303.csv

Processing batch 304: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 304 processed and saved to llm-author-affiliations/gpt_responses_batch_304.csv

Processing batch 305: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 305 processed and saved to llm-author-affiliations/gpt_responses_batch_305.csv

Processing batch 306: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 306 processed and saved to llm-author-affiliations/gpt_responses_batch_306.csv

Processing batch 307: 100%|██████████| 54/54 [00:26<00:00,  2.04it/s]

Batch 307 processed and saved to llm-author-affiliations/gpt_responses_batch_307.csv

In [13]:
df1 = pd.read_csv('llm-cleaned-samples.csv')

folder_path1 = "llm-author-affiliations"

df1 = matcher.process_affiliation(df1)
affiliation_df1 = df1['affiliation_strings'].explode().value_counts().reset_index()
compile_df1 = matcher.compile_files(folder_path1)
compile_df1 = compile_df1.rename(columns={'affiliation_string': 'affiliation_strings'})
mapped_affiliation_df1 = matcher.create_affiliation_mapping(affiliation_df1, compile_df1)

df1 = matcher.process_departments(df1)

100%|██████████| 59239/59239 [00:00<00:00, 1063708.61it/s]

#### 4. Calculating Entropy

In [14]:
df1 = calculator.calculate_all_entropies(df1)
df1.to_csv('llm-information-entropy.csv',index=False)
df1.head(5)

Calculating entropy for country_codes...
Calculating entropy for institutions...
Calculating entropy for departments...

,id,doi,title,abstract,publication_year,publication_date,created_date,type,cited_by_count,is_retracted,...,GPT_response,author_names,institutions,country_codes,institution_types,affiliation_strings,departments,country_codes_entropy,institutions_entropy,departments_entropy
0,https://openalex.org/W2902614977,https://doi.org/10.18653/v1/w18-6315,Using Monolingual Data in Neural Machine Trans...,Neural Machine Translation (MT) has radically ...,2018,2018-01-01,2018-12-11,preprint,119,False,...,Yes,"[Franck Burlot, François Yvon]","[Lingua et Machina (France), Laboratoire d'Inf...","[FR, FR]","[company, facility]","[Lingua Custodia 1, Place Charles de Gaulle 78...",[],-0.0,1.0,NaN
1,https://openalex.org/W2904631866,https://doi.org/10.48550/arxiv.1812.03593,SDNet: Contextualized Attention-based Deep Net...,Conversational question answering (CQA) is a n...,2018,2018-01-01,2018-12-22,preprint,122,False,...,Yes,"[Chenguang Zhu, Michael Zeng, Xuedong Huang]",[],[],"[None, None, None]",[],[],NaN,NaN,NaN
2,https://openalex.org/W2913129712,https://doi.org/10.48550/arxiv.1902.04094,"BERT has a Mouth, and It Must Speak: BERT as a...","We show that BERT (Devlin et al., 2018) is a M...",2019,2019-01-01,2019-02-21,preprint,131,False,...,Yes,"[Alex Wang, Kyunghyun Cho]","[New York University, New York University]","[US, US]","[education, education]","[ New York University<sup>**</sup>, New York ...",[],-0.0,-0.0,NaN
3,https://openalex.org/W2914029346,https://doi.org/10.48550/arxiv.1902.04260,Table2answer: Read the database and answer wit...,Semantic parsing is the task of mapping natura...,2019,2019-01-01,2019-02-21,preprint,4,False,...,Yes,"[Tong Guo, Huilin Gao]",[],[],"[None, None]",[],[],NaN,NaN,NaN
4,https://openalex.org/W2914845972,https://doi.org/10.48550/arxiv.1902.00821,Review Conversational Reading Comprehension,Inspired by conversational reading comprehensi...,2019,2019-01-01,2019-02-21,preprint,17,False,...,Yes,"[Hu Xu, Bing Liu, Lei Shu, Philip S. Yu]",[],[],"[None, None, None, None]",[],[],NaN,NaN,NaN

### Processing Control Groups

#### 2. Processing ML papers

In [15]:
# Compile llm papers openalex ids

llm_ids = df1['id'].to_list()

In [20]:
df2 = processor.sample_documents('search-ml', 0.3)
df2 = df2.sample(n=100000)
print(f"The total number of sampled downloaded papers: {len(df2)}")
df2 = processor.filter_by_date(df2, start_date, end_date)
print(f"The total number of papers after sorting date: {len(df2)}")
df2 = processor.filter_by_type(df2)
print(f"The total number of papers after filtering paper types: {len(df2)}")
df2 = processor.remove_exact_duplicates(df2)
print(f"The total number of papers after removing duplicates: {len(df2)}")
df2 = processor.remove_similar_documents(df2)
print(f"The total number of papers after potential duplicates: {len(df2)}")
df2 = df2[~df2['id'].isin(llm_ids)]
print(f"The total number of papers after removing LLM papers: {len(df2)}")
df2.to_csv('ml-cleaned-samples.csv',index=False)

The total number of sampled downloaded papers: 100000
The total number of papers after sorting date: 95952
The total number of papers after filtering paper types: 79368
The total number of papers after removing duplicates: 76035

Processing preprints: 100%|██████████| 13493/13493 [00:44<00:00, 304.55it/s]

The total number of papers after potential duplicates: 71482
The total number of papers after removing LLM papers: 70945

In [21]:
save_directory = "ml-author-affiliations"

extractor = AffiliationProcessor(
    batch_size=200,
    save_directory=save_directory
)

affiliations2 = extractor.extract_affiliation(df2)
affiliations2 = extractor.prepare_prompt(affiliations2)
print(f"The total number of authors: {len(affiliations2)}")
extractor.process_batches(affiliations2)

The total number of authors: 148490

Processing batch 0: 100%|██████████| 200/200 [01:26<00:00,  2.30it/s]

Batch 0 processed and saved to ml-author-affiliations/gpt_responses_batch_0.csv

Processing batch 1: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 1 processed and saved to ml-author-affiliations/gpt_responses_batch_1.csv

Processing batch 2: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 2 processed and saved to ml-author-affiliations/gpt_responses_batch_2.csv

Processing batch 3: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 3 processed and saved to ml-author-affiliations/gpt_responses_batch_3.csv

Processing batch 4: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 4 processed and saved to ml-author-affiliations/gpt_responses_batch_4.csv

Processing batch 5: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 5 processed and saved to ml-author-affiliations/gpt_responses_batch_5.csv

Processing batch 6: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 6 processed and saved to ml-author-affiliations/gpt_responses_batch_6.csv

Processing batch 7: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 7 processed and saved to ml-author-affiliations/gpt_responses_batch_7.csv

Processing batch 8: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 8 processed and saved to ml-author-affiliations/gpt_responses_batch_8.csv

Processing batch 9: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 9 processed and saved to ml-author-affiliations/gpt_responses_batch_9.csv

Processing batch 10: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 10 processed and saved to ml-author-affiliations/gpt_responses_batch_10.csv

Processing batch 11: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 11 processed and saved to ml-author-affiliations/gpt_responses_batch_11.csv

Processing batch 12: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 12 processed and saved to ml-author-affiliations/gpt_responses_batch_12.csv

Processing batch 13: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 13 processed and saved to ml-author-affiliations/gpt_responses_batch_13.csv

Processing batch 14: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 14 processed and saved to ml-author-affiliations/gpt_responses_batch_14.csv

Processing batch 15: 100%|██████████| 200/200 [01:55<00:00,  1.74it/s]

Batch 15 processed and saved to ml-author-affiliations/gpt_responses_batch_15.csv

Processing batch 16: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 16 processed and saved to ml-author-affiliations/gpt_responses_batch_16.csv

Processing batch 17: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 17 processed and saved to ml-author-affiliations/gpt_responses_batch_17.csv

Processing batch 18: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 18 processed and saved to ml-author-affiliations/gpt_responses_batch_18.csv

Processing batch 19: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 19 processed and saved to ml-author-affiliations/gpt_responses_batch_19.csv

Processing batch 20: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 20 processed and saved to ml-author-affiliations/gpt_responses_batch_20.csv

Processing batch 21: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 21 processed and saved to ml-author-affiliations/gpt_responses_batch_21.csv

Processing batch 22: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 22 processed and saved to ml-author-affiliations/gpt_responses_batch_22.csv

Processing batch 23: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 23 processed and saved to ml-author-affiliations/gpt_responses_batch_23.csv

Processing batch 24: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 24 processed and saved to ml-author-affiliations/gpt_responses_batch_24.csv

Processing batch 25: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 25 processed and saved to ml-author-affiliations/gpt_responses_batch_25.csv

Processing batch 26: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 26 processed and saved to ml-author-affiliations/gpt_responses_batch_26.csv

Processing batch 27: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 27 processed and saved to ml-author-affiliations/gpt_responses_batch_27.csv

Processing batch 28: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 28 processed and saved to ml-author-affiliations/gpt_responses_batch_28.csv

Processing batch 29: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 29 processed and saved to ml-author-affiliations/gpt_responses_batch_29.csv

Processing batch 30: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 30 processed and saved to ml-author-affiliations/gpt_responses_batch_30.csv

Processing batch 31: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 31 processed and saved to ml-author-affiliations/gpt_responses_batch_31.csv

Processing batch 32: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 32 processed and saved to ml-author-affiliations/gpt_responses_batch_32.csv

Processing batch 33: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 33 processed and saved to ml-author-affiliations/gpt_responses_batch_33.csv

Processing batch 34: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 34 processed and saved to ml-author-affiliations/gpt_responses_batch_34.csv

Processing batch 35: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 35 processed and saved to ml-author-affiliations/gpt_responses_batch_35.csv

Processing batch 36: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 36 processed and saved to ml-author-affiliations/gpt_responses_batch_36.csv

Processing batch 37: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 37 processed and saved to ml-author-affiliations/gpt_responses_batch_37.csv

Processing batch 38: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 38 processed and saved to ml-author-affiliations/gpt_responses_batch_38.csv

Processing batch 39: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 39 processed and saved to ml-author-affiliations/gpt_responses_batch_39.csv

Processing batch 40: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 40 processed and saved to ml-author-affiliations/gpt_responses_batch_40.csv

Processing batch 41: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 41 processed and saved to ml-author-affiliations/gpt_responses_batch_41.csv

Processing batch 42: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 42 processed and saved to ml-author-affiliations/gpt_responses_batch_42.csv

Processing batch 43: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 43 processed and saved to ml-author-affiliations/gpt_responses_batch_43.csv

Processing batch 44: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 44 processed and saved to ml-author-affiliations/gpt_responses_batch_44.csv

Processing batch 45: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 45 processed and saved to ml-author-affiliations/gpt_responses_batch_45.csv

Processing batch 46: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 46 processed and saved to ml-author-affiliations/gpt_responses_batch_46.csv

Processing batch 47: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 47 processed and saved to ml-author-affiliations/gpt_responses_batch_47.csv

Processing batch 48: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 48 processed and saved to ml-author-affiliations/gpt_responses_batch_48.csv

Processing batch 49: 100%|██████████| 200/200 [01:34<00:00,  2.13it/s]

Batch 49 processed and saved to ml-author-affiliations/gpt_responses_batch_49.csv

Processing batch 50: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 50 processed and saved to ml-author-affiliations/gpt_responses_batch_50.csv

Processing batch 51: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 51 processed and saved to ml-author-affiliations/gpt_responses_batch_51.csv

Processing batch 52: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 52 processed and saved to ml-author-affiliations/gpt_responses_batch_52.csv

Processing batch 53: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 53 processed and saved to ml-author-affiliations/gpt_responses_batch_53.csv

Processing batch 54: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 54 processed and saved to ml-author-affiliations/gpt_responses_batch_54.csv

Processing batch 55: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 55 processed and saved to ml-author-affiliations/gpt_responses_batch_55.csv

Processing batch 56: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 56 processed and saved to ml-author-affiliations/gpt_responses_batch_56.csv

Processing batch 57: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 57 processed and saved to ml-author-affiliations/gpt_responses_batch_57.csv

Processing batch 58: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 58 processed and saved to ml-author-affiliations/gpt_responses_batch_58.csv

Processing batch 59: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 59 processed and saved to ml-author-affiliations/gpt_responses_batch_59.csv

Processing batch 60: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 60 processed and saved to ml-author-affiliations/gpt_responses_batch_60.csv

Processing batch 61: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 61 processed and saved to ml-author-affiliations/gpt_responses_batch_61.csv

Processing batch 62: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 62 processed and saved to ml-author-affiliations/gpt_responses_batch_62.csv

Processing batch 63: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 63 processed and saved to ml-author-affiliations/gpt_responses_batch_63.csv

Processing batch 64: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 64 processed and saved to ml-author-affiliations/gpt_responses_batch_64.csv

Processing batch 65: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 65 processed and saved to ml-author-affiliations/gpt_responses_batch_65.csv

Processing batch 66: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 66 processed and saved to ml-author-affiliations/gpt_responses_batch_66.csv

Processing batch 67: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 67 processed and saved to ml-author-affiliations/gpt_responses_batch_67.csv

Processing batch 68: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 68 processed and saved to ml-author-affiliations/gpt_responses_batch_68.csv

Processing batch 69: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 69 processed and saved to ml-author-affiliations/gpt_responses_batch_69.csv

Processing batch 70: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 70 processed and saved to ml-author-affiliations/gpt_responses_batch_70.csv

Processing batch 71: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 71 processed and saved to ml-author-affiliations/gpt_responses_batch_71.csv

Processing batch 72: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 72 processed and saved to ml-author-affiliations/gpt_responses_batch_72.csv

Processing batch 73: 100%|██████████| 200/200 [01:46<00:00,  1.89it/s]

Batch 73 processed and saved to ml-author-affiliations/gpt_responses_batch_73.csv

Processing batch 74: 100%|██████████| 200/200 [01:46<00:00,  1.89it/s]

Batch 74 processed and saved to ml-author-affiliations/gpt_responses_batch_74.csv

Processing batch 75: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 75 processed and saved to ml-author-affiliations/gpt_responses_batch_75.csv

Processing batch 76: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 76 processed and saved to ml-author-affiliations/gpt_responses_batch_76.csv

Processing batch 77: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 77 processed and saved to ml-author-affiliations/gpt_responses_batch_77.csv

Processing batch 78: 100%|██████████| 200/200 [01:50<00:00,  1.82it/s]

Batch 78 processed and saved to ml-author-affiliations/gpt_responses_batch_78.csv

Processing batch 79: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 79 processed and saved to ml-author-affiliations/gpt_responses_batch_79.csv

Processing batch 80: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 80 processed and saved to ml-author-affiliations/gpt_responses_batch_80.csv

Processing batch 81: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 81 processed and saved to ml-author-affiliations/gpt_responses_batch_81.csv

Processing batch 82: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 82 processed and saved to ml-author-affiliations/gpt_responses_batch_82.csv

Processing batch 83: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 83 processed and saved to ml-author-affiliations/gpt_responses_batch_83.csv

Processing batch 84: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 84 processed and saved to ml-author-affiliations/gpt_responses_batch_84.csv

Processing batch 85: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 85 processed and saved to ml-author-affiliations/gpt_responses_batch_85.csv

Processing batch 86: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 86 processed and saved to ml-author-affiliations/gpt_responses_batch_86.csv

Processing batch 87: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 87 processed and saved to ml-author-affiliations/gpt_responses_batch_87.csv

Processing batch 88: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 88 processed and saved to ml-author-affiliations/gpt_responses_batch_88.csv

Processing batch 89: 100%|██████████| 200/200 [01:54<00:00,  1.74it/s]

Batch 89 processed and saved to ml-author-affiliations/gpt_responses_batch_89.csv

Processing batch 90: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 90 processed and saved to ml-author-affiliations/gpt_responses_batch_90.csv

Processing batch 91: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 91 processed and saved to ml-author-affiliations/gpt_responses_batch_91.csv

Processing batch 92: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 92 processed and saved to ml-author-affiliations/gpt_responses_batch_92.csv

Processing batch 93: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 93 processed and saved to ml-author-affiliations/gpt_responses_batch_93.csv

Processing batch 94: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 94 processed and saved to ml-author-affiliations/gpt_responses_batch_94.csv

Processing batch 95: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 95 processed and saved to ml-author-affiliations/gpt_responses_batch_95.csv

Processing batch 96: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 96 processed and saved to ml-author-affiliations/gpt_responses_batch_96.csv

Processing batch 97: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 97 processed and saved to ml-author-affiliations/gpt_responses_batch_97.csv

Processing batch 98: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 98 processed and saved to ml-author-affiliations/gpt_responses_batch_98.csv

Processing batch 99: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 99 processed and saved to ml-author-affiliations/gpt_responses_batch_99.csv

Processing batch 100: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 100 processed and saved to ml-author-affiliations/gpt_responses_batch_100.csv

Processing batch 101: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 101 processed and saved to ml-author-affiliations/gpt_responses_batch_101.csv

Processing batch 102: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 102 processed and saved to ml-author-affiliations/gpt_responses_batch_102.csv

Processing batch 103: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 103 processed and saved to ml-author-affiliations/gpt_responses_batch_103.csv

Processing batch 104: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 104 processed and saved to ml-author-affiliations/gpt_responses_batch_104.csv

Processing batch 105: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 105 processed and saved to ml-author-affiliations/gpt_responses_batch_105.csv

Processing batch 106: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 106 processed and saved to ml-author-affiliations/gpt_responses_batch_106.csv

Processing batch 107: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 107 processed and saved to ml-author-affiliations/gpt_responses_batch_107.csv

Processing batch 108: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 108 processed and saved to ml-author-affiliations/gpt_responses_batch_108.csv

Processing batch 109: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 109 processed and saved to ml-author-affiliations/gpt_responses_batch_109.csv

Processing batch 110: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 110 processed and saved to ml-author-affiliations/gpt_responses_batch_110.csv

Processing batch 111: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 111 processed and saved to ml-author-affiliations/gpt_responses_batch_111.csv

Processing batch 112: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 112 processed and saved to ml-author-affiliations/gpt_responses_batch_112.csv

Processing batch 113: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 113 processed and saved to ml-author-affiliations/gpt_responses_batch_113.csv

Processing batch 114: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 114 processed and saved to ml-author-affiliations/gpt_responses_batch_114.csv

Processing batch 115: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 115 processed and saved to ml-author-affiliations/gpt_responses_batch_115.csv

Processing batch 116: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 116 processed and saved to ml-author-affiliations/gpt_responses_batch_116.csv

Processing batch 117: 100%|██████████| 200/200 [01:34<00:00,  2.13it/s]

Batch 117 processed and saved to ml-author-affiliations/gpt_responses_batch_117.csv

Processing batch 118: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 118 processed and saved to ml-author-affiliations/gpt_responses_batch_118.csv

Processing batch 119: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 119 processed and saved to ml-author-affiliations/gpt_responses_batch_119.csv

Processing batch 120: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 120 processed and saved to ml-author-affiliations/gpt_responses_batch_120.csv

Processing batch 121: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 121 processed and saved to ml-author-affiliations/gpt_responses_batch_121.csv

Processing batch 122: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 122 processed and saved to ml-author-affiliations/gpt_responses_batch_122.csv

Processing batch 123: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 123 processed and saved to ml-author-affiliations/gpt_responses_batch_123.csv

Processing batch 124: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 124 processed and saved to ml-author-affiliations/gpt_responses_batch_124.csv

Processing batch 125: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 125 processed and saved to ml-author-affiliations/gpt_responses_batch_125.csv

Processing batch 126: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 126 processed and saved to ml-author-affiliations/gpt_responses_batch_126.csv

Processing batch 127: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 127 processed and saved to ml-author-affiliations/gpt_responses_batch_127.csv

Processing batch 128: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 128 processed and saved to ml-author-affiliations/gpt_responses_batch_128.csv

Processing batch 129: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 129 processed and saved to ml-author-affiliations/gpt_responses_batch_129.csv

Processing batch 130: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 130 processed and saved to ml-author-affiliations/gpt_responses_batch_130.csv

Processing batch 131: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 131 processed and saved to ml-author-affiliations/gpt_responses_batch_131.csv

Processing batch 132: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 132 processed and saved to ml-author-affiliations/gpt_responses_batch_132.csv

Processing batch 133: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 133 processed and saved to ml-author-affiliations/gpt_responses_batch_133.csv

Processing batch 134: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 134 processed and saved to ml-author-affiliations/gpt_responses_batch_134.csv

Processing batch 135: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 135 processed and saved to ml-author-affiliations/gpt_responses_batch_135.csv

Processing batch 136: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 136 processed and saved to ml-author-affiliations/gpt_responses_batch_136.csv

Processing batch 137: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 137 processed and saved to ml-author-affiliations/gpt_responses_batch_137.csv

Processing batch 138: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 138 processed and saved to ml-author-affiliations/gpt_responses_batch_138.csv

Processing batch 139: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 139 processed and saved to ml-author-affiliations/gpt_responses_batch_139.csv

Processing batch 140: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 140 processed and saved to ml-author-affiliations/gpt_responses_batch_140.csv

Processing batch 141: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 141 processed and saved to ml-author-affiliations/gpt_responses_batch_141.csv

Processing batch 142: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 142 processed and saved to ml-author-affiliations/gpt_responses_batch_142.csv

Processing batch 143: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 143 processed and saved to ml-author-affiliations/gpt_responses_batch_143.csv

Processing batch 144: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 144 processed and saved to ml-author-affiliations/gpt_responses_batch_144.csv

Processing batch 145: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 145 processed and saved to ml-author-affiliations/gpt_responses_batch_145.csv

Processing batch 146: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 146 processed and saved to ml-author-affiliations/gpt_responses_batch_146.csv

Processing batch 147: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 147 processed and saved to ml-author-affiliations/gpt_responses_batch_147.csv

Processing batch 148: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 148 processed and saved to ml-author-affiliations/gpt_responses_batch_148.csv

Processing batch 149: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 149 processed and saved to ml-author-affiliations/gpt_responses_batch_149.csv

Processing batch 150: 100%|██████████| 200/200 [02:08<00:00,  1.56it/s]

Batch 150 processed and saved to ml-author-affiliations/gpt_responses_batch_150.csv

Processing batch 151: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 151 processed and saved to ml-author-affiliations/gpt_responses_batch_151.csv

Processing batch 152: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 152 processed and saved to ml-author-affiliations/gpt_responses_batch_152.csv

Processing batch 153: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 153 processed and saved to ml-author-affiliations/gpt_responses_batch_153.csv

Processing batch 154: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 154 processed and saved to ml-author-affiliations/gpt_responses_batch_154.csv

Processing batch 155: 100%|██████████| 200/200 [01:52<00:00,  1.77it/s]

Batch 155 processed and saved to ml-author-affiliations/gpt_responses_batch_155.csv

Processing batch 156: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 156 processed and saved to ml-author-affiliations/gpt_responses_batch_156.csv

Processing batch 157: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 157 processed and saved to ml-author-affiliations/gpt_responses_batch_157.csv

Processing batch 158: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 158 processed and saved to ml-author-affiliations/gpt_responses_batch_158.csv

Processing batch 159: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 159 processed and saved to ml-author-affiliations/gpt_responses_batch_159.csv

Processing batch 160: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 160 processed and saved to ml-author-affiliations/gpt_responses_batch_160.csv

Processing batch 161: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 161 processed and saved to ml-author-affiliations/gpt_responses_batch_161.csv

Processing batch 162: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 162 processed and saved to ml-author-affiliations/gpt_responses_batch_162.csv

Processing batch 163: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 163 processed and saved to ml-author-affiliations/gpt_responses_batch_163.csv

Processing batch 164: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 164 processed and saved to ml-author-affiliations/gpt_responses_batch_164.csv

Processing batch 165: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 165 processed and saved to ml-author-affiliations/gpt_responses_batch_165.csv

Processing batch 166: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 166 processed and saved to ml-author-affiliations/gpt_responses_batch_166.csv

Processing batch 167: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 167 processed and saved to ml-author-affiliations/gpt_responses_batch_167.csv

Processing batch 168: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 168 processed and saved to ml-author-affiliations/gpt_responses_batch_168.csv

Processing batch 169: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 169 processed and saved to ml-author-affiliations/gpt_responses_batch_169.csv

Processing batch 170: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 170 processed and saved to ml-author-affiliations/gpt_responses_batch_170.csv

Processing batch 171: 100%|██████████| 200/200 [01:26<00:00,  2.31it/s]

Batch 171 processed and saved to ml-author-affiliations/gpt_responses_batch_171.csv

Processing batch 172: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 172 processed and saved to ml-author-affiliations/gpt_responses_batch_172.csv

Processing batch 173: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 173 processed and saved to ml-author-affiliations/gpt_responses_batch_173.csv

Processing batch 174: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 174 processed and saved to ml-author-affiliations/gpt_responses_batch_174.csv

Processing batch 175: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 175 processed and saved to ml-author-affiliations/gpt_responses_batch_175.csv

Processing batch 176: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 176 processed and saved to ml-author-affiliations/gpt_responses_batch_176.csv

Processing batch 177: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 177 processed and saved to ml-author-affiliations/gpt_responses_batch_177.csv

Processing batch 178: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 178 processed and saved to ml-author-affiliations/gpt_responses_batch_178.csv

Processing batch 179: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 179 processed and saved to ml-author-affiliations/gpt_responses_batch_179.csv

Processing batch 180: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 180 processed and saved to ml-author-affiliations/gpt_responses_batch_180.csv

Processing batch 181: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 181 processed and saved to ml-author-affiliations/gpt_responses_batch_181.csv

Processing batch 182: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 182 processed and saved to ml-author-affiliations/gpt_responses_batch_182.csv

Processing batch 183: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 183 processed and saved to ml-author-affiliations/gpt_responses_batch_183.csv

Processing batch 184: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 184 processed and saved to ml-author-affiliations/gpt_responses_batch_184.csv

Processing batch 185: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 185 processed and saved to ml-author-affiliations/gpt_responses_batch_185.csv

Processing batch 186: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 186 processed and saved to ml-author-affiliations/gpt_responses_batch_186.csv

Processing batch 187: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 187 processed and saved to ml-author-affiliations/gpt_responses_batch_187.csv

Processing batch 188: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 188 processed and saved to ml-author-affiliations/gpt_responses_batch_188.csv

Processing batch 189: 100%|██████████| 200/200 [01:52<00:00,  1.77it/s]

Batch 189 processed and saved to ml-author-affiliations/gpt_responses_batch_189.csv

Processing batch 190: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 190 processed and saved to ml-author-affiliations/gpt_responses_batch_190.csv

Processing batch 191: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 191 processed and saved to ml-author-affiliations/gpt_responses_batch_191.csv

Processing batch 192: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 192 processed and saved to ml-author-affiliations/gpt_responses_batch_192.csv

Processing batch 193: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 193 processed and saved to ml-author-affiliations/gpt_responses_batch_193.csv

Processing batch 194: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 194 processed and saved to ml-author-affiliations/gpt_responses_batch_194.csv

Processing batch 195: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 195 processed and saved to ml-author-affiliations/gpt_responses_batch_195.csv

Processing batch 196: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 196 processed and saved to ml-author-affiliations/gpt_responses_batch_196.csv

Processing batch 197: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 197 processed and saved to ml-author-affiliations/gpt_responses_batch_197.csv

Processing batch 198: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 198 processed and saved to ml-author-affiliations/gpt_responses_batch_198.csv

Processing batch 199: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 199 processed and saved to ml-author-affiliations/gpt_responses_batch_199.csv

Processing batch 200: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 200 processed and saved to ml-author-affiliations/gpt_responses_batch_200.csv

Processing batch 201: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 201 processed and saved to ml-author-affiliations/gpt_responses_batch_201.csv

Processing batch 202: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 202 processed and saved to ml-author-affiliations/gpt_responses_batch_202.csv

Processing batch 203: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 203 processed and saved to ml-author-affiliations/gpt_responses_batch_203.csv

Processing batch 204: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 204 processed and saved to ml-author-affiliations/gpt_responses_batch_204.csv

Processing batch 205: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 205 processed and saved to ml-author-affiliations/gpt_responses_batch_205.csv

Processing batch 206: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 206 processed and saved to ml-author-affiliations/gpt_responses_batch_206.csv

Processing batch 207: 100%|██████████| 200/200 [01:56<00:00,  1.72it/s]

Batch 207 processed and saved to ml-author-affiliations/gpt_responses_batch_207.csv

Processing batch 208: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 208 processed and saved to ml-author-affiliations/gpt_responses_batch_208.csv

Processing batch 209: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 209 processed and saved to ml-author-affiliations/gpt_responses_batch_209.csv

Processing batch 210: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 210 processed and saved to ml-author-affiliations/gpt_responses_batch_210.csv

Processing batch 211: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 211 processed and saved to ml-author-affiliations/gpt_responses_batch_211.csv

Processing batch 212: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 212 processed and saved to ml-author-affiliations/gpt_responses_batch_212.csv

Processing batch 213: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 213 processed and saved to ml-author-affiliations/gpt_responses_batch_213.csv

Processing batch 214: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 214 processed and saved to ml-author-affiliations/gpt_responses_batch_214.csv

Processing batch 215: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 215 processed and saved to ml-author-affiliations/gpt_responses_batch_215.csv

Processing batch 216: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 216 processed and saved to ml-author-affiliations/gpt_responses_batch_216.csv

Processing batch 217: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 217 processed and saved to ml-author-affiliations/gpt_responses_batch_217.csv

Processing batch 218: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 218 processed and saved to ml-author-affiliations/gpt_responses_batch_218.csv

Processing batch 219: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 219 processed and saved to ml-author-affiliations/gpt_responses_batch_219.csv

Processing batch 220: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 220 processed and saved to ml-author-affiliations/gpt_responses_batch_220.csv

Processing batch 221: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 221 processed and saved to ml-author-affiliations/gpt_responses_batch_221.csv

Processing batch 222: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 222 processed and saved to ml-author-affiliations/gpt_responses_batch_222.csv

Processing batch 223: 100%|██████████| 200/200 [01:53<00:00,  1.77it/s]

Batch 223 processed and saved to ml-author-affiliations/gpt_responses_batch_223.csv

Processing batch 224: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 224 processed and saved to ml-author-affiliations/gpt_responses_batch_224.csv

Processing batch 225: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 225 processed and saved to ml-author-affiliations/gpt_responses_batch_225.csv

Processing batch 226: 100%|██████████| 200/200 [02:33<00:00,  1.30it/s]

Batch 226 processed and saved to ml-author-affiliations/gpt_responses_batch_226.csv

Processing batch 227: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 227 processed and saved to ml-author-affiliations/gpt_responses_batch_227.csv

Processing batch 228: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 228 processed and saved to ml-author-affiliations/gpt_responses_batch_228.csv

Processing batch 229: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 229 processed and saved to ml-author-affiliations/gpt_responses_batch_229.csv

Processing batch 230: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 230 processed and saved to ml-author-affiliations/gpt_responses_batch_230.csv

Processing batch 231: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 231 processed and saved to ml-author-affiliations/gpt_responses_batch_231.csv

Processing batch 232: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 232 processed and saved to ml-author-affiliations/gpt_responses_batch_232.csv

Processing batch 233: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 233 processed and saved to ml-author-affiliations/gpt_responses_batch_233.csv

Processing batch 234: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 234 processed and saved to ml-author-affiliations/gpt_responses_batch_234.csv

Processing batch 235: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 235 processed and saved to ml-author-affiliations/gpt_responses_batch_235.csv

Processing batch 236: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 236 processed and saved to ml-author-affiliations/gpt_responses_batch_236.csv

Processing batch 237: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 237 processed and saved to ml-author-affiliations/gpt_responses_batch_237.csv

Processing batch 238: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 238 processed and saved to ml-author-affiliations/gpt_responses_batch_238.csv

Processing batch 239: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 239 processed and saved to ml-author-affiliations/gpt_responses_batch_239.csv

Processing batch 240: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 240 processed and saved to ml-author-affiliations/gpt_responses_batch_240.csv

Processing batch 241: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 241 processed and saved to ml-author-affiliations/gpt_responses_batch_241.csv

Processing batch 242: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 242 processed and saved to ml-author-affiliations/gpt_responses_batch_242.csv

Processing batch 243: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 243 processed and saved to ml-author-affiliations/gpt_responses_batch_243.csv

Processing batch 244: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 244 processed and saved to ml-author-affiliations/gpt_responses_batch_244.csv

Processing batch 245: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 245 processed and saved to ml-author-affiliations/gpt_responses_batch_245.csv

Processing batch 246: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 246 processed and saved to ml-author-affiliations/gpt_responses_batch_246.csv

Processing batch 247: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 247 processed and saved to ml-author-affiliations/gpt_responses_batch_247.csv

Processing batch 248: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 248 processed and saved to ml-author-affiliations/gpt_responses_batch_248.csv

Processing batch 249: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 249 processed and saved to ml-author-affiliations/gpt_responses_batch_249.csv

Processing batch 250: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 250 processed and saved to ml-author-affiliations/gpt_responses_batch_250.csv

Processing batch 251: 100%|██████████| 200/200 [01:58<00:00,  1.69it/s]

Batch 251 processed and saved to ml-author-affiliations/gpt_responses_batch_251.csv

Processing batch 252: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 252 processed and saved to ml-author-affiliations/gpt_responses_batch_252.csv

Processing batch 253: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 253 processed and saved to ml-author-affiliations/gpt_responses_batch_253.csv

Processing batch 254: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 254 processed and saved to ml-author-affiliations/gpt_responses_batch_254.csv

Processing batch 255: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 255 processed and saved to ml-author-affiliations/gpt_responses_batch_255.csv

Processing batch 256: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 256 processed and saved to ml-author-affiliations/gpt_responses_batch_256.csv

Processing batch 257: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 257 processed and saved to ml-author-affiliations/gpt_responses_batch_257.csv

Processing batch 258: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 258 processed and saved to ml-author-affiliations/gpt_responses_batch_258.csv

Processing batch 259: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 259 processed and saved to ml-author-affiliations/gpt_responses_batch_259.csv

Processing batch 260: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 260 processed and saved to ml-author-affiliations/gpt_responses_batch_260.csv

Processing batch 261: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 261 processed and saved to ml-author-affiliations/gpt_responses_batch_261.csv

Processing batch 262: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 262 processed and saved to ml-author-affiliations/gpt_responses_batch_262.csv

Processing batch 263: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 263 processed and saved to ml-author-affiliations/gpt_responses_batch_263.csv

Processing batch 264: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 264 processed and saved to ml-author-affiliations/gpt_responses_batch_264.csv

Processing batch 265: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 265 processed and saved to ml-author-affiliations/gpt_responses_batch_265.csv

Processing batch 266: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 266 processed and saved to ml-author-affiliations/gpt_responses_batch_266.csv

Processing batch 267: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 267 processed and saved to ml-author-affiliations/gpt_responses_batch_267.csv

Processing batch 268: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 268 processed and saved to ml-author-affiliations/gpt_responses_batch_268.csv

Processing batch 269: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 269 processed and saved to ml-author-affiliations/gpt_responses_batch_269.csv

Processing batch 270: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 270 processed and saved to ml-author-affiliations/gpt_responses_batch_270.csv

Processing batch 271: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 271 processed and saved to ml-author-affiliations/gpt_responses_batch_271.csv

Processing batch 272: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 272 processed and saved to ml-author-affiliations/gpt_responses_batch_272.csv

Processing batch 273: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 273 processed and saved to ml-author-affiliations/gpt_responses_batch_273.csv

Processing batch 274: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 274 processed and saved to ml-author-affiliations/gpt_responses_batch_274.csv

Processing batch 275: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 275 processed and saved to ml-author-affiliations/gpt_responses_batch_275.csv

Processing batch 276: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 276 processed and saved to ml-author-affiliations/gpt_responses_batch_276.csv

Processing batch 277: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 277 processed and saved to ml-author-affiliations/gpt_responses_batch_277.csv

Processing batch 278: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 278 processed and saved to ml-author-affiliations/gpt_responses_batch_278.csv

Processing batch 279: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 279 processed and saved to ml-author-affiliations/gpt_responses_batch_279.csv

Processing batch 280: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 280 processed and saved to ml-author-affiliations/gpt_responses_batch_280.csv

Processing batch 281: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 281 processed and saved to ml-author-affiliations/gpt_responses_batch_281.csv

Processing batch 282: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 282 processed and saved to ml-author-affiliations/gpt_responses_batch_282.csv

Processing batch 283: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 283 processed and saved to ml-author-affiliations/gpt_responses_batch_283.csv

Processing batch 284: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 284 processed and saved to ml-author-affiliations/gpt_responses_batch_284.csv

Processing batch 285: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 285 processed and saved to ml-author-affiliations/gpt_responses_batch_285.csv

Processing batch 286: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 286 processed and saved to ml-author-affiliations/gpt_responses_batch_286.csv

Processing batch 287: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 287 processed and saved to ml-author-affiliations/gpt_responses_batch_287.csv

Processing batch 288: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 288 processed and saved to ml-author-affiliations/gpt_responses_batch_288.csv

Processing batch 289: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 289 processed and saved to ml-author-affiliations/gpt_responses_batch_289.csv

Processing batch 290: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 290 processed and saved to ml-author-affiliations/gpt_responses_batch_290.csv

Processing batch 291: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 291 processed and saved to ml-author-affiliations/gpt_responses_batch_291.csv

Processing batch 292: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 292 processed and saved to ml-author-affiliations/gpt_responses_batch_292.csv

Processing batch 293: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 293 processed and saved to ml-author-affiliations/gpt_responses_batch_293.csv

Processing batch 294: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 294 processed and saved to ml-author-affiliations/gpt_responses_batch_294.csv

Processing batch 295: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 295 processed and saved to ml-author-affiliations/gpt_responses_batch_295.csv

Processing batch 296: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 296 processed and saved to ml-author-affiliations/gpt_responses_batch_296.csv

Processing batch 297: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 297 processed and saved to ml-author-affiliations/gpt_responses_batch_297.csv

Processing batch 298: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 298 processed and saved to ml-author-affiliations/gpt_responses_batch_298.csv

Processing batch 299: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 299 processed and saved to ml-author-affiliations/gpt_responses_batch_299.csv

Processing batch 300: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 300 processed and saved to ml-author-affiliations/gpt_responses_batch_300.csv

Processing batch 301: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 301 processed and saved to ml-author-affiliations/gpt_responses_batch_301.csv

Processing batch 302: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 302 processed and saved to ml-author-affiliations/gpt_responses_batch_302.csv

Processing batch 303: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 303 processed and saved to ml-author-affiliations/gpt_responses_batch_303.csv

Processing batch 304: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 304 processed and saved to ml-author-affiliations/gpt_responses_batch_304.csv

Processing batch 305: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 305 processed and saved to ml-author-affiliations/gpt_responses_batch_305.csv

Processing batch 306: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 306 processed and saved to ml-author-affiliations/gpt_responses_batch_306.csv

Processing batch 307: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 307 processed and saved to ml-author-affiliations/gpt_responses_batch_307.csv

Processing batch 308: 100%|██████████| 200/200 [01:53<00:00,  1.76it/s]

Batch 308 processed and saved to ml-author-affiliations/gpt_responses_batch_308.csv

Processing batch 309: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 309 processed and saved to ml-author-affiliations/gpt_responses_batch_309.csv

Processing batch 310: 100%|██████████| 200/200 [01:50<00:00,  1.82it/s]

Batch 310 processed and saved to ml-author-affiliations/gpt_responses_batch_310.csv

Processing batch 311: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 311 processed and saved to ml-author-affiliations/gpt_responses_batch_311.csv

Processing batch 312: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 312 processed and saved to ml-author-affiliations/gpt_responses_batch_312.csv

Processing batch 313: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 313 processed and saved to ml-author-affiliations/gpt_responses_batch_313.csv

Processing batch 314: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 314 processed and saved to ml-author-affiliations/gpt_responses_batch_314.csv

Processing batch 315: 100%|██████████| 200/200 [02:01<00:00,  1.64it/s]

Batch 315 processed and saved to ml-author-affiliations/gpt_responses_batch_315.csv

Processing batch 316: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 316 processed and saved to ml-author-affiliations/gpt_responses_batch_316.csv

Processing batch 317: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 317 processed and saved to ml-author-affiliations/gpt_responses_batch_317.csv

Processing batch 318: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 318 processed and saved to ml-author-affiliations/gpt_responses_batch_318.csv

Processing batch 319: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 319 processed and saved to ml-author-affiliations/gpt_responses_batch_319.csv

Processing batch 320: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 320 processed and saved to ml-author-affiliations/gpt_responses_batch_320.csv

Processing batch 321: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 321 processed and saved to ml-author-affiliations/gpt_responses_batch_321.csv

Processing batch 322: 100%|██████████| 200/200 [01:57<00:00,  1.70it/s]

Batch 322 processed and saved to ml-author-affiliations/gpt_responses_batch_322.csv

Processing batch 323: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 323 processed and saved to ml-author-affiliations/gpt_responses_batch_323.csv

Processing batch 324: 100%|██████████| 200/200 [01:55<00:00,  1.73it/s]

Batch 324 processed and saved to ml-author-affiliations/gpt_responses_batch_324.csv

Processing batch 325: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 325 processed and saved to ml-author-affiliations/gpt_responses_batch_325.csv

Processing batch 326: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 326 processed and saved to ml-author-affiliations/gpt_responses_batch_326.csv

Processing batch 327: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 327 processed and saved to ml-author-affiliations/gpt_responses_batch_327.csv

Processing batch 328: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 328 processed and saved to ml-author-affiliations/gpt_responses_batch_328.csv

Processing batch 329: 100%|██████████| 200/200 [02:00<00:00,  1.66it/s]

Batch 329 processed and saved to ml-author-affiliations/gpt_responses_batch_329.csv

Processing batch 330: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 330 processed and saved to ml-author-affiliations/gpt_responses_batch_330.csv

Processing batch 331: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 331 processed and saved to ml-author-affiliations/gpt_responses_batch_331.csv

Processing batch 332: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 332 processed and saved to ml-author-affiliations/gpt_responses_batch_332.csv

Processing batch 333: 100%|██████████| 200/200 [01:57<00:00,  1.70it/s]

Batch 333 processed and saved to ml-author-affiliations/gpt_responses_batch_333.csv

Processing batch 334: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 334 processed and saved to ml-author-affiliations/gpt_responses_batch_334.csv

Processing batch 335: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 335 processed and saved to ml-author-affiliations/gpt_responses_batch_335.csv

Processing batch 336: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 336 processed and saved to ml-author-affiliations/gpt_responses_batch_336.csv

Processing batch 337: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 337 processed and saved to ml-author-affiliations/gpt_responses_batch_337.csv

Processing batch 338: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 338 processed and saved to ml-author-affiliations/gpt_responses_batch_338.csv

Processing batch 339: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 339 processed and saved to ml-author-affiliations/gpt_responses_batch_339.csv

Processing batch 340: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 340 processed and saved to ml-author-affiliations/gpt_responses_batch_340.csv

Processing batch 341: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 341 processed and saved to ml-author-affiliations/gpt_responses_batch_341.csv

Processing batch 342: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 342 processed and saved to ml-author-affiliations/gpt_responses_batch_342.csv

Processing batch 343: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 343 processed and saved to ml-author-affiliations/gpt_responses_batch_343.csv

Processing batch 344: 100%|██████████| 200/200 [01:55<00:00,  1.73it/s]

Batch 344 processed and saved to ml-author-affiliations/gpt_responses_batch_344.csv

Processing batch 345: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 345 processed and saved to ml-author-affiliations/gpt_responses_batch_345.csv

Processing batch 346: 100%|██████████| 200/200 [01:53<00:00,  1.76it/s]

Batch 346 processed and saved to ml-author-affiliations/gpt_responses_batch_346.csv

Processing batch 347: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 347 processed and saved to ml-author-affiliations/gpt_responses_batch_347.csv

Processing batch 348: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 348 processed and saved to ml-author-affiliations/gpt_responses_batch_348.csv

Processing batch 349: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 349 processed and saved to ml-author-affiliations/gpt_responses_batch_349.csv

Processing batch 350: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 350 processed and saved to ml-author-affiliations/gpt_responses_batch_350.csv

Processing batch 351: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 351 processed and saved to ml-author-affiliations/gpt_responses_batch_351.csv

Processing batch 352: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 352 processed and saved to ml-author-affiliations/gpt_responses_batch_352.csv

Processing batch 353: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 353 processed and saved to ml-author-affiliations/gpt_responses_batch_353.csv

Processing batch 354: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 354 processed and saved to ml-author-affiliations/gpt_responses_batch_354.csv

Processing batch 355: 100%|██████████| 200/200 [01:58<00:00,  1.68it/s]

Batch 355 processed and saved to ml-author-affiliations/gpt_responses_batch_355.csv

Processing batch 356: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 356 processed and saved to ml-author-affiliations/gpt_responses_batch_356.csv

Processing batch 357: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 357 processed and saved to ml-author-affiliations/gpt_responses_batch_357.csv

Processing batch 358: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 358 processed and saved to ml-author-affiliations/gpt_responses_batch_358.csv

Processing batch 359: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 359 processed and saved to ml-author-affiliations/gpt_responses_batch_359.csv

Processing batch 360: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 360 processed and saved to ml-author-affiliations/gpt_responses_batch_360.csv

Processing batch 361: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 361 processed and saved to ml-author-affiliations/gpt_responses_batch_361.csv

Processing batch 362: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 362 processed and saved to ml-author-affiliations/gpt_responses_batch_362.csv

Processing batch 363: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 363 processed and saved to ml-author-affiliations/gpt_responses_batch_363.csv

Processing batch 364: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 364 processed and saved to ml-author-affiliations/gpt_responses_batch_364.csv

Processing batch 365: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 365 processed and saved to ml-author-affiliations/gpt_responses_batch_365.csv

Processing batch 366: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 366 processed and saved to ml-author-affiliations/gpt_responses_batch_366.csv

Processing batch 367: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 367 processed and saved to ml-author-affiliations/gpt_responses_batch_367.csv

Processing batch 368: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 368 processed and saved to ml-author-affiliations/gpt_responses_batch_368.csv

Processing batch 369: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 369 processed and saved to ml-author-affiliations/gpt_responses_batch_369.csv

Processing batch 370: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 370 processed and saved to ml-author-affiliations/gpt_responses_batch_370.csv

Processing batch 371: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 371 processed and saved to ml-author-affiliations/gpt_responses_batch_371.csv

Processing batch 372: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 372 processed and saved to ml-author-affiliations/gpt_responses_batch_372.csv

Processing batch 373: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 373 processed and saved to ml-author-affiliations/gpt_responses_batch_373.csv

Processing batch 374: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 374 processed and saved to ml-author-affiliations/gpt_responses_batch_374.csv

Processing batch 375: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 375 processed and saved to ml-author-affiliations/gpt_responses_batch_375.csv

Processing batch 376: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 376 processed and saved to ml-author-affiliations/gpt_responses_batch_376.csv

Processing batch 377: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 377 processed and saved to ml-author-affiliations/gpt_responses_batch_377.csv

Processing batch 378: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 378 processed and saved to ml-author-affiliations/gpt_responses_batch_378.csv

Processing batch 379: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 379 processed and saved to ml-author-affiliations/gpt_responses_batch_379.csv

Processing batch 380: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 380 processed and saved to ml-author-affiliations/gpt_responses_batch_380.csv

Processing batch 381: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 381 processed and saved to ml-author-affiliations/gpt_responses_batch_381.csv

Processing batch 382: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 382 processed and saved to ml-author-affiliations/gpt_responses_batch_382.csv

Processing batch 383: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 383 processed and saved to ml-author-affiliations/gpt_responses_batch_383.csv

Processing batch 384: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 384 processed and saved to ml-author-affiliations/gpt_responses_batch_384.csv

Processing batch 385: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 385 processed and saved to ml-author-affiliations/gpt_responses_batch_385.csv

Processing batch 386: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 386 processed and saved to ml-author-affiliations/gpt_responses_batch_386.csv

Processing batch 387: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 387 processed and saved to ml-author-affiliations/gpt_responses_batch_387.csv

Processing batch 388: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 388 processed and saved to ml-author-affiliations/gpt_responses_batch_388.csv

Processing batch 389: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 389 processed and saved to ml-author-affiliations/gpt_responses_batch_389.csv

Processing batch 390: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 390 processed and saved to ml-author-affiliations/gpt_responses_batch_390.csv

Processing batch 391: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 391 processed and saved to ml-author-affiliations/gpt_responses_batch_391.csv

Processing batch 392: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 392 processed and saved to ml-author-affiliations/gpt_responses_batch_392.csv

Processing batch 393: 100%|██████████| 200/200 [02:05<00:00,  1.59it/s]

Batch 393 processed and saved to ml-author-affiliations/gpt_responses_batch_393.csv

Processing batch 394: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 394 processed and saved to ml-author-affiliations/gpt_responses_batch_394.csv

Processing batch 395: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 395 processed and saved to ml-author-affiliations/gpt_responses_batch_395.csv

Processing batch 396: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 396 processed and saved to ml-author-affiliations/gpt_responses_batch_396.csv

Processing batch 397: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 397 processed and saved to ml-author-affiliations/gpt_responses_batch_397.csv

Processing batch 398: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 398 processed and saved to ml-author-affiliations/gpt_responses_batch_398.csv

Processing batch 399: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 399 processed and saved to ml-author-affiliations/gpt_responses_batch_399.csv

Processing batch 400: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 400 processed and saved to ml-author-affiliations/gpt_responses_batch_400.csv

Processing batch 401: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 401 processed and saved to ml-author-affiliations/gpt_responses_batch_401.csv

Processing batch 402: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 402 processed and saved to ml-author-affiliations/gpt_responses_batch_402.csv

Processing batch 403: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 403 processed and saved to ml-author-affiliations/gpt_responses_batch_403.csv

Processing batch 404: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 404 processed and saved to ml-author-affiliations/gpt_responses_batch_404.csv

Processing batch 405: 100%|██████████| 200/200 [01:59<00:00,  1.68it/s]

Batch 405 processed and saved to ml-author-affiliations/gpt_responses_batch_405.csv

Processing batch 406: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 406 processed and saved to ml-author-affiliations/gpt_responses_batch_406.csv

Processing batch 407: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 407 processed and saved to ml-author-affiliations/gpt_responses_batch_407.csv

Processing batch 408: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 408 processed and saved to ml-author-affiliations/gpt_responses_batch_408.csv

Processing batch 409: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 409 processed and saved to ml-author-affiliations/gpt_responses_batch_409.csv

Processing batch 410: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 410 processed and saved to ml-author-affiliations/gpt_responses_batch_410.csv

Processing batch 411: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 411 processed and saved to ml-author-affiliations/gpt_responses_batch_411.csv

Processing batch 412: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 412 processed and saved to ml-author-affiliations/gpt_responses_batch_412.csv

Processing batch 413: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 413 processed and saved to ml-author-affiliations/gpt_responses_batch_413.csv

Processing batch 414: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 414 processed and saved to ml-author-affiliations/gpt_responses_batch_414.csv

Processing batch 415: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 415 processed and saved to ml-author-affiliations/gpt_responses_batch_415.csv

Processing batch 416: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 416 processed and saved to ml-author-affiliations/gpt_responses_batch_416.csv

Processing batch 417: 100%|██████████| 200/200 [01:53<00:00,  1.77it/s]

Batch 417 processed and saved to ml-author-affiliations/gpt_responses_batch_417.csv

Processing batch 418: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 418 processed and saved to ml-author-affiliations/gpt_responses_batch_418.csv

Processing batch 419: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 419 processed and saved to ml-author-affiliations/gpt_responses_batch_419.csv

Processing batch 420: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 420 processed and saved to ml-author-affiliations/gpt_responses_batch_420.csv

Processing batch 421: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 421 processed and saved to ml-author-affiliations/gpt_responses_batch_421.csv

Processing batch 422: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 422 processed and saved to ml-author-affiliations/gpt_responses_batch_422.csv

Processing batch 423: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 423 processed and saved to ml-author-affiliations/gpt_responses_batch_423.csv

Processing batch 424: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 424 processed and saved to ml-author-affiliations/gpt_responses_batch_424.csv

Processing batch 425: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 425 processed and saved to ml-author-affiliations/gpt_responses_batch_425.csv

Processing batch 426: 100%|██████████| 200/200 [02:00<00:00,  1.65it/s]

Batch 426 processed and saved to ml-author-affiliations/gpt_responses_batch_426.csv

Processing batch 427: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 427 processed and saved to ml-author-affiliations/gpt_responses_batch_427.csv

Processing batch 428: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 428 processed and saved to ml-author-affiliations/gpt_responses_batch_428.csv

Processing batch 429: 100%|██████████| 200/200 [01:54<00:00,  1.75it/s]

Batch 429 processed and saved to ml-author-affiliations/gpt_responses_batch_429.csv

Processing batch 430: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 430 processed and saved to ml-author-affiliations/gpt_responses_batch_430.csv

Processing batch 431: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 431 processed and saved to ml-author-affiliations/gpt_responses_batch_431.csv

Processing batch 432: 100%|██████████| 200/200 [01:46<00:00,  1.89it/s]

Batch 432 processed and saved to ml-author-affiliations/gpt_responses_batch_432.csv

Processing batch 433: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 433 processed and saved to ml-author-affiliations/gpt_responses_batch_433.csv

Processing batch 434: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 434 processed and saved to ml-author-affiliations/gpt_responses_batch_434.csv

Processing batch 435: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 435 processed and saved to ml-author-affiliations/gpt_responses_batch_435.csv

Processing batch 436: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 436 processed and saved to ml-author-affiliations/gpt_responses_batch_436.csv

Processing batch 437: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 437 processed and saved to ml-author-affiliations/gpt_responses_batch_437.csv

Processing batch 438: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 438 processed and saved to ml-author-affiliations/gpt_responses_batch_438.csv

Processing batch 439: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 439 processed and saved to ml-author-affiliations/gpt_responses_batch_439.csv

Processing batch 440: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 440 processed and saved to ml-author-affiliations/gpt_responses_batch_440.csv

Processing batch 441: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 441 processed and saved to ml-author-affiliations/gpt_responses_batch_441.csv

Processing batch 442: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 442 processed and saved to ml-author-affiliations/gpt_responses_batch_442.csv

Processing batch 443: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 443 processed and saved to ml-author-affiliations/gpt_responses_batch_443.csv

Processing batch 444: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 444 processed and saved to ml-author-affiliations/gpt_responses_batch_444.csv

Processing batch 445: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 445 processed and saved to ml-author-affiliations/gpt_responses_batch_445.csv

Processing batch 446: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 446 processed and saved to ml-author-affiliations/gpt_responses_batch_446.csv

Processing batch 447: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 447 processed and saved to ml-author-affiliations/gpt_responses_batch_447.csv

Processing batch 448: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 448 processed and saved to ml-author-affiliations/gpt_responses_batch_448.csv

Processing batch 449: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 449 processed and saved to ml-author-affiliations/gpt_responses_batch_449.csv

Processing batch 450: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 450 processed and saved to ml-author-affiliations/gpt_responses_batch_450.csv

Processing batch 451: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 451 processed and saved to ml-author-affiliations/gpt_responses_batch_451.csv

Processing batch 452: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 452 processed and saved to ml-author-affiliations/gpt_responses_batch_452.csv

Processing batch 453: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 453 processed and saved to ml-author-affiliations/gpt_responses_batch_453.csv

Processing batch 454: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 454 processed and saved to ml-author-affiliations/gpt_responses_batch_454.csv

Processing batch 455: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 455 processed and saved to ml-author-affiliations/gpt_responses_batch_455.csv

Processing batch 456: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 456 processed and saved to ml-author-affiliations/gpt_responses_batch_456.csv

Processing batch 457: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 457 processed and saved to ml-author-affiliations/gpt_responses_batch_457.csv

Processing batch 458: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 458 processed and saved to ml-author-affiliations/gpt_responses_batch_458.csv

Processing batch 459: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 459 processed and saved to ml-author-affiliations/gpt_responses_batch_459.csv

Processing batch 460: 100%|██████████| 200/200 [01:34<00:00,  2.13it/s]

Batch 460 processed and saved to ml-author-affiliations/gpt_responses_batch_460.csv

Processing batch 461: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 461 processed and saved to ml-author-affiliations/gpt_responses_batch_461.csv

Processing batch 462: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 462 processed and saved to ml-author-affiliations/gpt_responses_batch_462.csv

Processing batch 463: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 463 processed and saved to ml-author-affiliations/gpt_responses_batch_463.csv

Processing batch 464: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 464 processed and saved to ml-author-affiliations/gpt_responses_batch_464.csv

Processing batch 465: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 465 processed and saved to ml-author-affiliations/gpt_responses_batch_465.csv

Processing batch 466: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 466 processed and saved to ml-author-affiliations/gpt_responses_batch_466.csv

Processing batch 467: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 467 processed and saved to ml-author-affiliations/gpt_responses_batch_467.csv

Processing batch 468: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 468 processed and saved to ml-author-affiliations/gpt_responses_batch_468.csv

Processing batch 469: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 469 processed and saved to ml-author-affiliations/gpt_responses_batch_469.csv

Processing batch 470: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 470 processed and saved to ml-author-affiliations/gpt_responses_batch_470.csv

Processing batch 471: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 471 processed and saved to ml-author-affiliations/gpt_responses_batch_471.csv

Processing batch 472: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 472 processed and saved to ml-author-affiliations/gpt_responses_batch_472.csv

Processing batch 473: 100%|██████████| 200/200 [01:29<00:00,  2.22it/s]

Batch 473 processed and saved to ml-author-affiliations/gpt_responses_batch_473.csv

Processing batch 474: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 474 processed and saved to ml-author-affiliations/gpt_responses_batch_474.csv

Processing batch 475: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 475 processed and saved to ml-author-affiliations/gpt_responses_batch_475.csv

Processing batch 476: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 476 processed and saved to ml-author-affiliations/gpt_responses_batch_476.csv

Processing batch 477: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 477 processed and saved to ml-author-affiliations/gpt_responses_batch_477.csv

Processing batch 478: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 478 processed and saved to ml-author-affiliations/gpt_responses_batch_478.csv

Processing batch 479: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 479 processed and saved to ml-author-affiliations/gpt_responses_batch_479.csv

Processing batch 480: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 480 processed and saved to ml-author-affiliations/gpt_responses_batch_480.csv

Processing batch 481: 100%|██████████| 200/200 [01:26<00:00,  2.32it/s]

Batch 481 processed and saved to ml-author-affiliations/gpt_responses_batch_481.csv

Processing batch 482: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 482 processed and saved to ml-author-affiliations/gpt_responses_batch_482.csv

Processing batch 483: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 483 processed and saved to ml-author-affiliations/gpt_responses_batch_483.csv

Processing batch 484: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 484 processed and saved to ml-author-affiliations/gpt_responses_batch_484.csv

Processing batch 485: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 485 processed and saved to ml-author-affiliations/gpt_responses_batch_485.csv

Processing batch 486: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 486 processed and saved to ml-author-affiliations/gpt_responses_batch_486.csv

Processing batch 487: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 487 processed and saved to ml-author-affiliations/gpt_responses_batch_487.csv

Processing batch 488: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 488 processed and saved to ml-author-affiliations/gpt_responses_batch_488.csv

Processing batch 489: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 489 processed and saved to ml-author-affiliations/gpt_responses_batch_489.csv

Processing batch 490: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 490 processed and saved to ml-author-affiliations/gpt_responses_batch_490.csv

Processing batch 491: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 491 processed and saved to ml-author-affiliations/gpt_responses_batch_491.csv

Processing batch 492: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 492 processed and saved to ml-author-affiliations/gpt_responses_batch_492.csv

Processing batch 493: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 493 processed and saved to ml-author-affiliations/gpt_responses_batch_493.csv

Processing batch 494: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 494 processed and saved to ml-author-affiliations/gpt_responses_batch_494.csv

Processing batch 495: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 495 processed and saved to ml-author-affiliations/gpt_responses_batch_495.csv

Processing batch 496: 100%|██████████| 200/200 [01:27<00:00,  2.29it/s]

Batch 496 processed and saved to ml-author-affiliations/gpt_responses_batch_496.csv

Processing batch 497: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 497 processed and saved to ml-author-affiliations/gpt_responses_batch_497.csv

Processing batch 498: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 498 processed and saved to ml-author-affiliations/gpt_responses_batch_498.csv

Processing batch 499: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 499 processed and saved to ml-author-affiliations/gpt_responses_batch_499.csv

Processing batch 500: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 500 processed and saved to ml-author-affiliations/gpt_responses_batch_500.csv

Processing batch 501: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 501 processed and saved to ml-author-affiliations/gpt_responses_batch_501.csv

Processing batch 502: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 502 processed and saved to ml-author-affiliations/gpt_responses_batch_502.csv

Processing batch 503: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 503 processed and saved to ml-author-affiliations/gpt_responses_batch_503.csv

Processing batch 504: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 504 processed and saved to ml-author-affiliations/gpt_responses_batch_504.csv

Processing batch 505: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 505 processed and saved to ml-author-affiliations/gpt_responses_batch_505.csv

Processing batch 506: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 506 processed and saved to ml-author-affiliations/gpt_responses_batch_506.csv

Processing batch 507: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 507 processed and saved to ml-author-affiliations/gpt_responses_batch_507.csv

Processing batch 508: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 508 processed and saved to ml-author-affiliations/gpt_responses_batch_508.csv

Processing batch 509: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 509 processed and saved to ml-author-affiliations/gpt_responses_batch_509.csv

Processing batch 510: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 510 processed and saved to ml-author-affiliations/gpt_responses_batch_510.csv

Processing batch 511: 100%|██████████| 200/200 [01:29<00:00,  2.22it/s]

Batch 511 processed and saved to ml-author-affiliations/gpt_responses_batch_511.csv

Processing batch 512: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 512 processed and saved to ml-author-affiliations/gpt_responses_batch_512.csv

Processing batch 513: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 513 processed and saved to ml-author-affiliations/gpt_responses_batch_513.csv

Processing batch 514: 100%|██████████| 200/200 [01:29<00:00,  2.22it/s]

Batch 514 processed and saved to ml-author-affiliations/gpt_responses_batch_514.csv

Processing batch 515: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 515 processed and saved to ml-author-affiliations/gpt_responses_batch_515.csv

Processing batch 516: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 516 processed and saved to ml-author-affiliations/gpt_responses_batch_516.csv

Processing batch 517: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 517 processed and saved to ml-author-affiliations/gpt_responses_batch_517.csv

Processing batch 518: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 518 processed and saved to ml-author-affiliations/gpt_responses_batch_518.csv

Processing batch 519: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 519 processed and saved to ml-author-affiliations/gpt_responses_batch_519.csv

Processing batch 520: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 520 processed and saved to ml-author-affiliations/gpt_responses_batch_520.csv

Processing batch 521: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 521 processed and saved to ml-author-affiliations/gpt_responses_batch_521.csv

Processing batch 522: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 522 processed and saved to ml-author-affiliations/gpt_responses_batch_522.csv

Processing batch 523: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 523 processed and saved to ml-author-affiliations/gpt_responses_batch_523.csv

Processing batch 524: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 524 processed and saved to ml-author-affiliations/gpt_responses_batch_524.csv

Processing batch 525: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 525 processed and saved to ml-author-affiliations/gpt_responses_batch_525.csv

Processing batch 526: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 526 processed and saved to ml-author-affiliations/gpt_responses_batch_526.csv

Processing batch 527: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 527 processed and saved to ml-author-affiliations/gpt_responses_batch_527.csv

Processing batch 528: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 528 processed and saved to ml-author-affiliations/gpt_responses_batch_528.csv

Processing batch 529: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 529 processed and saved to ml-author-affiliations/gpt_responses_batch_529.csv

Processing batch 530: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 530 processed and saved to ml-author-affiliations/gpt_responses_batch_530.csv

Processing batch 531: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 531 processed and saved to ml-author-affiliations/gpt_responses_batch_531.csv

Processing batch 532: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 532 processed and saved to ml-author-affiliations/gpt_responses_batch_532.csv

Processing batch 533: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 533 processed and saved to ml-author-affiliations/gpt_responses_batch_533.csv

Processing batch 534: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 534 processed and saved to ml-author-affiliations/gpt_responses_batch_534.csv

Processing batch 535: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 535 processed and saved to ml-author-affiliations/gpt_responses_batch_535.csv

Processing batch 536: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 536 processed and saved to ml-author-affiliations/gpt_responses_batch_536.csv

Processing batch 537: 100%|██████████| 200/200 [01:31<00:00,  2.17it/s]

Batch 537 processed and saved to ml-author-affiliations/gpt_responses_batch_537.csv

Processing batch 538: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 538 processed and saved to ml-author-affiliations/gpt_responses_batch_538.csv

Processing batch 539: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 539 processed and saved to ml-author-affiliations/gpt_responses_batch_539.csv

Processing batch 540: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 540 processed and saved to ml-author-affiliations/gpt_responses_batch_540.csv

Processing batch 541: 100%|██████████| 200/200 [01:24<00:00,  2.37it/s]

Batch 541 processed and saved to ml-author-affiliations/gpt_responses_batch_541.csv

Processing batch 542: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 542 processed and saved to ml-author-affiliations/gpt_responses_batch_542.csv

Processing batch 543: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 543 processed and saved to ml-author-affiliations/gpt_responses_batch_543.csv

Processing batch 544: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 544 processed and saved to ml-author-affiliations/gpt_responses_batch_544.csv

Processing batch 545: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 545 processed and saved to ml-author-affiliations/gpt_responses_batch_545.csv

Processing batch 546: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 546 processed and saved to ml-author-affiliations/gpt_responses_batch_546.csv

Processing batch 547: 100%|██████████| 200/200 [01:35<00:00,  2.11it/s]

Batch 547 processed and saved to ml-author-affiliations/gpt_responses_batch_547.csv

Processing batch 548: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 548 processed and saved to ml-author-affiliations/gpt_responses_batch_548.csv

Processing batch 549: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 549 processed and saved to ml-author-affiliations/gpt_responses_batch_549.csv

Processing batch 550: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 550 processed and saved to ml-author-affiliations/gpt_responses_batch_550.csv

Processing batch 551: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 551 processed and saved to ml-author-affiliations/gpt_responses_batch_551.csv

Processing batch 552: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 552 processed and saved to ml-author-affiliations/gpt_responses_batch_552.csv

Processing batch 553: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 553 processed and saved to ml-author-affiliations/gpt_responses_batch_553.csv

Processing batch 554: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 554 processed and saved to ml-author-affiliations/gpt_responses_batch_554.csv

Processing batch 555: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 555 processed and saved to ml-author-affiliations/gpt_responses_batch_555.csv

Processing batch 556: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 556 processed and saved to ml-author-affiliations/gpt_responses_batch_556.csv

Processing batch 557: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 557 processed and saved to ml-author-affiliations/gpt_responses_batch_557.csv

Processing batch 558: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 558 processed and saved to ml-author-affiliations/gpt_responses_batch_558.csv

Processing batch 559: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 559 processed and saved to ml-author-affiliations/gpt_responses_batch_559.csv

Processing batch 560: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 560 processed and saved to ml-author-affiliations/gpt_responses_batch_560.csv

Processing batch 561: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 561 processed and saved to ml-author-affiliations/gpt_responses_batch_561.csv

Processing batch 562: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 562 processed and saved to ml-author-affiliations/gpt_responses_batch_562.csv

Processing batch 563: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 563 processed and saved to ml-author-affiliations/gpt_responses_batch_563.csv

Processing batch 564: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 564 processed and saved to ml-author-affiliations/gpt_responses_batch_564.csv

Processing batch 565: 100%|██████████| 200/200 [01:52<00:00,  1.78it/s]

Batch 565 processed and saved to ml-author-affiliations/gpt_responses_batch_565.csv

Processing batch 566: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 566 processed and saved to ml-author-affiliations/gpt_responses_batch_566.csv

Processing batch 567: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 567 processed and saved to ml-author-affiliations/gpt_responses_batch_567.csv

Processing batch 568: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 568 processed and saved to ml-author-affiliations/gpt_responses_batch_568.csv

Processing batch 569: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 569 processed and saved to ml-author-affiliations/gpt_responses_batch_569.csv

Processing batch 570: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 570 processed and saved to ml-author-affiliations/gpt_responses_batch_570.csv

Processing batch 571: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 571 processed and saved to ml-author-affiliations/gpt_responses_batch_571.csv

Processing batch 572: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 572 processed and saved to ml-author-affiliations/gpt_responses_batch_572.csv

Processing batch 573: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 573 processed and saved to ml-author-affiliations/gpt_responses_batch_573.csv

Processing batch 574: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 574 processed and saved to ml-author-affiliations/gpt_responses_batch_574.csv

Processing batch 575: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 575 processed and saved to ml-author-affiliations/gpt_responses_batch_575.csv

Processing batch 576: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 576 processed and saved to ml-author-affiliations/gpt_responses_batch_576.csv

Processing batch 577: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 577 processed and saved to ml-author-affiliations/gpt_responses_batch_577.csv

Processing batch 578: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 578 processed and saved to ml-author-affiliations/gpt_responses_batch_578.csv

Processing batch 579: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 579 processed and saved to ml-author-affiliations/gpt_responses_batch_579.csv

Processing batch 580: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 580 processed and saved to ml-author-affiliations/gpt_responses_batch_580.csv

Processing batch 581: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 581 processed and saved to ml-author-affiliations/gpt_responses_batch_581.csv

Processing batch 582: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 582 processed and saved to ml-author-affiliations/gpt_responses_batch_582.csv

Processing batch 583: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 583 processed and saved to ml-author-affiliations/gpt_responses_batch_583.csv

Processing batch 584: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 584 processed and saved to ml-author-affiliations/gpt_responses_batch_584.csv

Processing batch 585: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 585 processed and saved to ml-author-affiliations/gpt_responses_batch_585.csv

Processing batch 586: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 586 processed and saved to ml-author-affiliations/gpt_responses_batch_586.csv

Processing batch 587: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 587 processed and saved to ml-author-affiliations/gpt_responses_batch_587.csv

Processing batch 588: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 588 processed and saved to ml-author-affiliations/gpt_responses_batch_588.csv

Processing batch 589: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 589 processed and saved to ml-author-affiliations/gpt_responses_batch_589.csv

Processing batch 590: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 590 processed and saved to ml-author-affiliations/gpt_responses_batch_590.csv

Processing batch 591: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 591 processed and saved to ml-author-affiliations/gpt_responses_batch_591.csv

Processing batch 592: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 592 processed and saved to ml-author-affiliations/gpt_responses_batch_592.csv

Processing batch 593: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 593 processed and saved to ml-author-affiliations/gpt_responses_batch_593.csv

Processing batch 594: 100%|██████████| 200/200 [02:00<00:00,  1.66it/s]

Batch 594 processed and saved to ml-author-affiliations/gpt_responses_batch_594.csv

Processing batch 595: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 595 processed and saved to ml-author-affiliations/gpt_responses_batch_595.csv

Processing batch 596: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 596 processed and saved to ml-author-affiliations/gpt_responses_batch_596.csv

Processing batch 597: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 597 processed and saved to ml-author-affiliations/gpt_responses_batch_597.csv

Processing batch 598: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 598 processed and saved to ml-author-affiliations/gpt_responses_batch_598.csv

Processing batch 599: 100%|██████████| 200/200 [01:54<00:00,  1.75it/s]

Batch 599 processed and saved to ml-author-affiliations/gpt_responses_batch_599.csv

Processing batch 600: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 600 processed and saved to ml-author-affiliations/gpt_responses_batch_600.csv

Processing batch 601: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 601 processed and saved to ml-author-affiliations/gpt_responses_batch_601.csv

Processing batch 602: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 602 processed and saved to ml-author-affiliations/gpt_responses_batch_602.csv

Processing batch 603: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 603 processed and saved to ml-author-affiliations/gpt_responses_batch_603.csv

Processing batch 604: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 604 processed and saved to ml-author-affiliations/gpt_responses_batch_604.csv

Processing batch 605: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 605 processed and saved to ml-author-affiliations/gpt_responses_batch_605.csv

Processing batch 606: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 606 processed and saved to ml-author-affiliations/gpt_responses_batch_606.csv

Processing batch 607: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 607 processed and saved to ml-author-affiliations/gpt_responses_batch_607.csv

Processing batch 608: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 608 processed and saved to ml-author-affiliations/gpt_responses_batch_608.csv

Processing batch 609: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 609 processed and saved to ml-author-affiliations/gpt_responses_batch_609.csv

Processing batch 610: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 610 processed and saved to ml-author-affiliations/gpt_responses_batch_610.csv

Processing batch 611: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 611 processed and saved to ml-author-affiliations/gpt_responses_batch_611.csv

Processing batch 612: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 612 processed and saved to ml-author-affiliations/gpt_responses_batch_612.csv

Processing batch 613: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 613 processed and saved to ml-author-affiliations/gpt_responses_batch_613.csv

Processing batch 614: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 614 processed and saved to ml-author-affiliations/gpt_responses_batch_614.csv

Processing batch 615: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 615 processed and saved to ml-author-affiliations/gpt_responses_batch_615.csv

Processing batch 616: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 616 processed and saved to ml-author-affiliations/gpt_responses_batch_616.csv

Processing batch 617: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 617 processed and saved to ml-author-affiliations/gpt_responses_batch_617.csv

Processing batch 618: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 618 processed and saved to ml-author-affiliations/gpt_responses_batch_618.csv

Processing batch 619: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 619 processed and saved to ml-author-affiliations/gpt_responses_batch_619.csv

Processing batch 620: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 620 processed and saved to ml-author-affiliations/gpt_responses_batch_620.csv

Processing batch 621: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 621 processed and saved to ml-author-affiliations/gpt_responses_batch_621.csv

Processing batch 622: 100%|██████████| 200/200 [11:39<00:00,  3.50s/it]

Batch 622 processed and saved to ml-author-affiliations/gpt_responses_batch_622.csv

Processing batch 623: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 623 processed and saved to ml-author-affiliations/gpt_responses_batch_623.csv

Processing batch 624: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 624 processed and saved to ml-author-affiliations/gpt_responses_batch_624.csv

Processing batch 625: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 625 processed and saved to ml-author-affiliations/gpt_responses_batch_625.csv

Processing batch 626: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 626 processed and saved to ml-author-affiliations/gpt_responses_batch_626.csv

Processing batch 627: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 627 processed and saved to ml-author-affiliations/gpt_responses_batch_627.csv

Processing batch 628: 100%|██████████| 200/200 [01:31<00:00,  2.17it/s]

Batch 628 processed and saved to ml-author-affiliations/gpt_responses_batch_628.csv

Processing batch 629: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 629 processed and saved to ml-author-affiliations/gpt_responses_batch_629.csv

Processing batch 630: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 630 processed and saved to ml-author-affiliations/gpt_responses_batch_630.csv

Processing batch 631: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 631 processed and saved to ml-author-affiliations/gpt_responses_batch_631.csv

Processing batch 632: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 632 processed and saved to ml-author-affiliations/gpt_responses_batch_632.csv

Processing batch 633: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 633 processed and saved to ml-author-affiliations/gpt_responses_batch_633.csv

Processing batch 634: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 634 processed and saved to ml-author-affiliations/gpt_responses_batch_634.csv

Processing batch 635: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 635 processed and saved to ml-author-affiliations/gpt_responses_batch_635.csv

Processing batch 636: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 636 processed and saved to ml-author-affiliations/gpt_responses_batch_636.csv

Processing batch 637: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 637 processed and saved to ml-author-affiliations/gpt_responses_batch_637.csv

Processing batch 638: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 638 processed and saved to ml-author-affiliations/gpt_responses_batch_638.csv

Processing batch 639: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 639 processed and saved to ml-author-affiliations/gpt_responses_batch_639.csv

Processing batch 640: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 640 processed and saved to ml-author-affiliations/gpt_responses_batch_640.csv

Processing batch 641: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 641 processed and saved to ml-author-affiliations/gpt_responses_batch_641.csv

Processing batch 642: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 642 processed and saved to ml-author-affiliations/gpt_responses_batch_642.csv

Processing batch 643: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 643 processed and saved to ml-author-affiliations/gpt_responses_batch_643.csv

Processing batch 644: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 644 processed and saved to ml-author-affiliations/gpt_responses_batch_644.csv

Processing batch 645: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 645 processed and saved to ml-author-affiliations/gpt_responses_batch_645.csv

Processing batch 646: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 646 processed and saved to ml-author-affiliations/gpt_responses_batch_646.csv

Processing batch 647: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 647 processed and saved to ml-author-affiliations/gpt_responses_batch_647.csv

Processing batch 648: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 648 processed and saved to ml-author-affiliations/gpt_responses_batch_648.csv

Processing batch 649: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 649 processed and saved to ml-author-affiliations/gpt_responses_batch_649.csv

Processing batch 650: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 650 processed and saved to ml-author-affiliations/gpt_responses_batch_650.csv

Processing batch 651: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 651 processed and saved to ml-author-affiliations/gpt_responses_batch_651.csv

Processing batch 652: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 652 processed and saved to ml-author-affiliations/gpt_responses_batch_652.csv

Processing batch 653: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 653 processed and saved to ml-author-affiliations/gpt_responses_batch_653.csv

Processing batch 654: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 654 processed and saved to ml-author-affiliations/gpt_responses_batch_654.csv

Processing batch 655: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 655 processed and saved to ml-author-affiliations/gpt_responses_batch_655.csv

Processing batch 656: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 656 processed and saved to ml-author-affiliations/gpt_responses_batch_656.csv

Processing batch 657: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 657 processed and saved to ml-author-affiliations/gpt_responses_batch_657.csv

Processing batch 658: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 658 processed and saved to ml-author-affiliations/gpt_responses_batch_658.csv

Processing batch 659: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 659 processed and saved to ml-author-affiliations/gpt_responses_batch_659.csv

Processing batch 660: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 660 processed and saved to ml-author-affiliations/gpt_responses_batch_660.csv

Processing batch 661: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 661 processed and saved to ml-author-affiliations/gpt_responses_batch_661.csv

Processing batch 662: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 662 processed and saved to ml-author-affiliations/gpt_responses_batch_662.csv

Processing batch 663: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 663 processed and saved to ml-author-affiliations/gpt_responses_batch_663.csv

Processing batch 664: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 664 processed and saved to ml-author-affiliations/gpt_responses_batch_664.csv

Processing batch 665: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 665 processed and saved to ml-author-affiliations/gpt_responses_batch_665.csv

Processing batch 666: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 666 processed and saved to ml-author-affiliations/gpt_responses_batch_666.csv

Processing batch 667: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 667 processed and saved to ml-author-affiliations/gpt_responses_batch_667.csv

Processing batch 668: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 668 processed and saved to ml-author-affiliations/gpt_responses_batch_668.csv

Processing batch 669: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 669 processed and saved to ml-author-affiliations/gpt_responses_batch_669.csv

Processing batch 670: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 670 processed and saved to ml-author-affiliations/gpt_responses_batch_670.csv

Processing batch 671: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 671 processed and saved to ml-author-affiliations/gpt_responses_batch_671.csv

Processing batch 672: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 672 processed and saved to ml-author-affiliations/gpt_responses_batch_672.csv

Processing batch 673: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 673 processed and saved to ml-author-affiliations/gpt_responses_batch_673.csv

Processing batch 674: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 674 processed and saved to ml-author-affiliations/gpt_responses_batch_674.csv

Processing batch 675: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 675 processed and saved to ml-author-affiliations/gpt_responses_batch_675.csv

Processing batch 676: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 676 processed and saved to ml-author-affiliations/gpt_responses_batch_676.csv

Processing batch 677: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 677 processed and saved to ml-author-affiliations/gpt_responses_batch_677.csv

Processing batch 678: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 678 processed and saved to ml-author-affiliations/gpt_responses_batch_678.csv

Processing batch 679: 100%|██████████| 200/200 [01:24<00:00,  2.35it/s]

Batch 679 processed and saved to ml-author-affiliations/gpt_responses_batch_679.csv

Processing batch 680: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 680 processed and saved to ml-author-affiliations/gpt_responses_batch_680.csv

Processing batch 681: 100%|██████████| 200/200 [01:29<00:00,  2.22it/s]

Batch 681 processed and saved to ml-author-affiliations/gpt_responses_batch_681.csv

Processing batch 682: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 682 processed and saved to ml-author-affiliations/gpt_responses_batch_682.csv

Processing batch 683: 100%|██████████| 200/200 [01:27<00:00,  2.29it/s]

Batch 683 processed and saved to ml-author-affiliations/gpt_responses_batch_683.csv

Processing batch 684: 100%|██████████| 200/200 [01:29<00:00,  2.25it/s]

Batch 684 processed and saved to ml-author-affiliations/gpt_responses_batch_684.csv

Processing batch 685: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 685 processed and saved to ml-author-affiliations/gpt_responses_batch_685.csv

Processing batch 686: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 686 processed and saved to ml-author-affiliations/gpt_responses_batch_686.csv

Processing batch 687: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 687 processed and saved to ml-author-affiliations/gpt_responses_batch_687.csv

Processing batch 688: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 688 processed and saved to ml-author-affiliations/gpt_responses_batch_688.csv

Processing batch 689: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 689 processed and saved to ml-author-affiliations/gpt_responses_batch_689.csv

Processing batch 690: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 690 processed and saved to ml-author-affiliations/gpt_responses_batch_690.csv

Processing batch 691: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 691 processed and saved to ml-author-affiliations/gpt_responses_batch_691.csv

Processing batch 692: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 692 processed and saved to ml-author-affiliations/gpt_responses_batch_692.csv

Processing batch 693: 100%|██████████| 200/200 [11:24<00:00,  3.42s/it]

Batch 693 processed and saved to ml-author-affiliations/gpt_responses_batch_693.csv

Processing batch 694: 100%|██████████| 200/200 [01:24<00:00,  2.37it/s]

Batch 694 processed and saved to ml-author-affiliations/gpt_responses_batch_694.csv

Processing batch 695: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 695 processed and saved to ml-author-affiliations/gpt_responses_batch_695.csv

Processing batch 696: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 696 processed and saved to ml-author-affiliations/gpt_responses_batch_696.csv

Processing batch 697: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 697 processed and saved to ml-author-affiliations/gpt_responses_batch_697.csv

Processing batch 698: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 698 processed and saved to ml-author-affiliations/gpt_responses_batch_698.csv

Processing batch 699: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 699 processed and saved to ml-author-affiliations/gpt_responses_batch_699.csv

Processing batch 700: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 700 processed and saved to ml-author-affiliations/gpt_responses_batch_700.csv

Processing batch 701: 100%|██████████| 200/200 [01:24<00:00,  2.37it/s]

Batch 701 processed and saved to ml-author-affiliations/gpt_responses_batch_701.csv

Processing batch 702: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 702 processed and saved to ml-author-affiliations/gpt_responses_batch_702.csv

Processing batch 703: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 703 processed and saved to ml-author-affiliations/gpt_responses_batch_703.csv

Processing batch 704: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 704 processed and saved to ml-author-affiliations/gpt_responses_batch_704.csv

Processing batch 705: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 705 processed and saved to ml-author-affiliations/gpt_responses_batch_705.csv

Processing batch 706: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 706 processed and saved to ml-author-affiliations/gpt_responses_batch_706.csv

Processing batch 707: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 707 processed and saved to ml-author-affiliations/gpt_responses_batch_707.csv

Processing batch 708: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 708 processed and saved to ml-author-affiliations/gpt_responses_batch_708.csv

Processing batch 709: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 709 processed and saved to ml-author-affiliations/gpt_responses_batch_709.csv

Processing batch 710: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 710 processed and saved to ml-author-affiliations/gpt_responses_batch_710.csv

Processing batch 711: 100%|██████████| 200/200 [01:25<00:00,  2.34it/s]

Batch 711 processed and saved to ml-author-affiliations/gpt_responses_batch_711.csv

Processing batch 712: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 712 processed and saved to ml-author-affiliations/gpt_responses_batch_712.csv

Processing batch 713: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 713 processed and saved to ml-author-affiliations/gpt_responses_batch_713.csv

Processing batch 714: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 714 processed and saved to ml-author-affiliations/gpt_responses_batch_714.csv

Processing batch 715: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 715 processed and saved to ml-author-affiliations/gpt_responses_batch_715.csv

Processing batch 716: 100%|██████████| 200/200 [01:26<00:00,  2.31it/s]

Batch 716 processed and saved to ml-author-affiliations/gpt_responses_batch_716.csv

Processing batch 717: 100%|██████████| 200/200 [01:22<00:00,  2.43it/s]

Batch 717 processed and saved to ml-author-affiliations/gpt_responses_batch_717.csv

Processing batch 718: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 718 processed and saved to ml-author-affiliations/gpt_responses_batch_718.csv

Processing batch 719: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 719 processed and saved to ml-author-affiliations/gpt_responses_batch_719.csv

Processing batch 720: 100%|██████████| 200/200 [01:27<00:00,  2.29it/s]

Batch 720 processed and saved to ml-author-affiliations/gpt_responses_batch_720.csv

Processing batch 721: 100%|██████████| 200/200 [01:23<00:00,  2.40it/s]

Batch 721 processed and saved to ml-author-affiliations/gpt_responses_batch_721.csv

Processing batch 722: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 722 processed and saved to ml-author-affiliations/gpt_responses_batch_722.csv

Processing batch 723: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 723 processed and saved to ml-author-affiliations/gpt_responses_batch_723.csv

Processing batch 724: 100%|██████████| 200/200 [01:22<00:00,  2.42it/s]

Batch 724 processed and saved to ml-author-affiliations/gpt_responses_batch_724.csv

Processing batch 725: 100%|██████████| 200/200 [01:23<00:00,  2.40it/s]

Batch 725 processed and saved to ml-author-affiliations/gpt_responses_batch_725.csv

Processing batch 726: 100%|██████████| 200/200 [01:24<00:00,  2.37it/s]

Batch 726 processed and saved to ml-author-affiliations/gpt_responses_batch_726.csv

Processing batch 727: 100%|██████████| 200/200 [01:22<00:00,  2.42it/s]

Batch 727 processed and saved to ml-author-affiliations/gpt_responses_batch_727.csv

Processing batch 728: 100%|██████████| 200/200 [01:23<00:00,  2.38it/s]

Batch 728 processed and saved to ml-author-affiliations/gpt_responses_batch_728.csv

Processing batch 729: 100%|██████████| 200/200 [01:18<00:00,  2.54it/s]

Batch 729 processed and saved to ml-author-affiliations/gpt_responses_batch_729.csv

Processing batch 730: 100%|██████████| 200/200 [01:21<00:00,  2.46it/s]

Batch 730 processed and saved to ml-author-affiliations/gpt_responses_batch_730.csv

Processing batch 731: 100%|██████████| 200/200 [01:25<00:00,  2.33it/s]

Batch 731 processed and saved to ml-author-affiliations/gpt_responses_batch_731.csv

Processing batch 732: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 732 processed and saved to ml-author-affiliations/gpt_responses_batch_732.csv

Processing batch 733: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 733 processed and saved to ml-author-affiliations/gpt_responses_batch_733.csv

Processing batch 734: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 734 processed and saved to ml-author-affiliations/gpt_responses_batch_734.csv

Processing batch 735: 100%|██████████| 200/200 [01:31<00:00,  2.17it/s]

Batch 735 processed and saved to ml-author-affiliations/gpt_responses_batch_735.csv

Processing batch 736: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 736 processed and saved to ml-author-affiliations/gpt_responses_batch_736.csv

Processing batch 737: 100%|██████████| 200/200 [01:24<00:00,  2.36it/s]

Batch 737 processed and saved to ml-author-affiliations/gpt_responses_batch_737.csv

Processing batch 738: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 738 processed and saved to ml-author-affiliations/gpt_responses_batch_738.csv

Processing batch 739: 100%|██████████| 200/200 [01:24<00:00,  2.37it/s]

Batch 739 processed and saved to ml-author-affiliations/gpt_responses_batch_739.csv

Processing batch 740: 100%|██████████| 200/200 [01:22<00:00,  2.42it/s]

Batch 740 processed and saved to ml-author-affiliations/gpt_responses_batch_740.csv

Processing batch 741: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 741 processed and saved to ml-author-affiliations/gpt_responses_batch_741.csv

Processing batch 742: 100%|██████████| 90/90 [00:40<00:00,  2.24it/s]

Batch 742 processed and saved to ml-author-affiliations/gpt_responses_batch_742.csv

In [23]:
folder_path2 = "ml-author-affiliations"

df2 = matcher.process_affiliation(df2)
affiliation_df2 = df2['affiliation_strings'].explode().value_counts().reset_index()
compile_df2 = matcher.compile_files(folder_path2)
compile_df2 = compile_df2.rename(columns={'affiliation_string': 'affiliation_strings'})
mapped_affiliation_df2 = matcher.create_affiliation_mapping(affiliation_df2, compile_df2)

df2 = matcher.process_departments(df2)
df2 = calculator.calculate_all_entropies(df2)
df2.to_csv('ml-information-entropy.csv',index=False)
df2.head(5)

100%|██████████| 70945/70945 [00:00<00:00, 791444.42it/s]

Calculating entropy for country_codes...
Calculating entropy for institutions...
Calculating entropy for departments...

,id,doi,title,abstract,publication_year,publication_date,created_date,type,cited_by_count,is_retracted,...,datetime,author_names,institutions,country_codes,institution_types,affiliation_strings,departments,country_codes_entropy,institutions_entropy,departments_entropy
102734,https://openalex.org/W2112949059,https://doi.org/10.1080/08927022.2021.1953585,Recent developments in molecular simulation,With the ever-increasing availability of high-...,2021,2021-07-13,2016-06-24,article,1,False,...,2021-07-13,[Jérôme Delhommelle],[University of North Dakota],[US],[education],"[Department of Biomedical Engineering, Univers...","[Biomedical Engineering, Chemistry, Molecular ...",-0.000000,-0.000000,1.584963
86745,https://openalex.org/W155445850,https://doi.org/10.18260/1-2--10735,Designing And Assessing A Learning Environment...,Abstract NOTE: The first page of text has been...,2020,2020-09-03,2016-06-24,article,1,False,...,2020-09-03,"[Ann McKenna, Alice M. Agogino]","[Northwestern University, University of Califo...","[US, US]","[education, education]","[Northwestern University****, University of Ca...",[],-0.000000,1.000000,NaN
184049,https://openalex.org/W2215302894,https://doi.org/10.1103/physrevd.99.024024,Sensitivity study using machine learning algor...,This is a follow-up sensitivity study on r-mod...,2019,2019-01-15,2016-06-24,article,13,False,...,2019-01-15,"[B. F. Whiting, Athanasios Aris Panagopoulos, ...","[Florida Museum of Natural History, California...","[US, US, US, IT, US]","[archive, education, education, education, edu...","[Department of Physics, University of Florida,...","[Physics, Computer Science, Computer Informati...",0.721928,2.321928,1.370951
146089,https://openalex.org/W2188045049,https://doi.org/10.32628/cseit217519,Prediction of Blood Donors Population Using Da...,Data mining is a technique that finds relation...,2021,2021-11-01,2016-06-24,article,6,False,...,2021-11-01,"[Aman Paul, Daljeet Singh]",[],[],"[None, None]","[Assistant Professor, Department of CSE, JCDM ...","[CSE, CSE]",NaN,NaN,-0.000000
92854,https://openalex.org/W2144283734,https://doi.org/10.1609/socs.v2i1.18207,Probably Approximately Correct Heuristic Search,A* is a best-first search algorithm that retur...,2021,2021-08-19,2016-06-24,article,3,False,...,2021-08-19,"[Roni Stern, Ariel Felner, Robert C. Holte]","[Ben-Gurion University of the Negev, Ben-Gurio...","[IL, IL, CA]","[education, education, education]","[BEN GURION UNIVERSITY, BEN GURION UNIVERSITY,...",[],0.918296,0.918296,NaN

#### Processing Non-LLM Papers

In [38]:
ml_ids = df2['id'].to_list()

df3 = processor.sample_documents('search-non-llm-random', 0.5)
df3 = df3.sample(n=150000)
print(f"The total number of sampled downloaded papers: {len(df3)}")
df3 = processor.filter_by_date(df3, start_date, end_date)
print(f"The total number of papers after sorting date: {len(df3)}")
df3 = processor.filter_by_type(df3)
print(f"The total number of papers after filtering paper types: {len(df3)}")
df3 = processor.remove_exact_duplicates(df3)
print(f"The total number of papers after removing duplicates: {len(df3)}")
df3 = processor.remove_similar_documents(df3)
print(f"The total number of papers after potential duplicates: {len(df3)}")
df3 = df3[~df3['id'].isin(llm_ids)]
df3 = df3[~df3['id'].isin(ml_ids)]
print(f"The total number of papers after removing LLM and ML papers: {len(df3)}")
df3.to_csv('non-llm-cleaned-samples.csv',index=False)

The total number of sampled downloaded papers: 150000
The total number of papers after sorting date: 127905
The total number of papers after filtering paper types: 89738
The total number of papers after removing duplicates: 73310

Processing preprints: 100%|██████████| 5786/5786 [00:12<00:00, 451.28it/s]

The total number of papers after potential duplicates: 73310
The total number of papers after removing LLM and ML papers: 73110

In [39]:
save_directory = "non-llm-author-affiliations"

extractor = AffiliationProcessor(
    batch_size=200,
    save_directory=save_directory
)

affiliations3 = extractor.extract_affiliation(df3)
affiliations3 = extractor.prepare_prompt(affiliations3)
print(f"The total number of authors: {len(affiliations3)}")
extractor.process_batches(affiliations3)

The total number of authors: 124851

Processing batch 0: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 0 processed and saved to non-llm-author-affiliations/gpt_responses_batch_0.csv

Processing batch 1: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 1 processed and saved to non-llm-author-affiliations/gpt_responses_batch_1.csv

Processing batch 2: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 2 processed and saved to non-llm-author-affiliations/gpt_responses_batch_2.csv

Processing batch 3: 100%|██████████| 200/200 [01:24<00:00,  2.37it/s]

Batch 3 processed and saved to non-llm-author-affiliations/gpt_responses_batch_3.csv

Processing batch 4: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 4 processed and saved to non-llm-author-affiliations/gpt_responses_batch_4.csv

Processing batch 5: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 5 processed and saved to non-llm-author-affiliations/gpt_responses_batch_5.csv

Processing batch 6: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 6 processed and saved to non-llm-author-affiliations/gpt_responses_batch_6.csv

Processing batch 7: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 7 processed and saved to non-llm-author-affiliations/gpt_responses_batch_7.csv

Processing batch 8: 100%|██████████| 200/200 [01:22<00:00,  2.41it/s]

Batch 8 processed and saved to non-llm-author-affiliations/gpt_responses_batch_8.csv

Processing batch 9: 100%|██████████| 200/200 [01:20<00:00,  2.47it/s]

Batch 9 processed and saved to non-llm-author-affiliations/gpt_responses_batch_9.csv

Processing batch 10: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 10 processed and saved to non-llm-author-affiliations/gpt_responses_batch_10.csv

Processing batch 11: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 11 processed and saved to non-llm-author-affiliations/gpt_responses_batch_11.csv

Processing batch 12: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 12 processed and saved to non-llm-author-affiliations/gpt_responses_batch_12.csv

Processing batch 13: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 13 processed and saved to non-llm-author-affiliations/gpt_responses_batch_13.csv

Processing batch 14: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 14 processed and saved to non-llm-author-affiliations/gpt_responses_batch_14.csv

Processing batch 15: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 15 processed and saved to non-llm-author-affiliations/gpt_responses_batch_15.csv

Processing batch 16: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 16 processed and saved to non-llm-author-affiliations/gpt_responses_batch_16.csv

Processing batch 17: 100%|██████████| 200/200 [01:22<00:00,  2.42it/s]

Batch 17 processed and saved to non-llm-author-affiliations/gpt_responses_batch_17.csv

Processing batch 18: 100%|██████████| 200/200 [01:24<00:00,  2.38it/s]

Batch 18 processed and saved to non-llm-author-affiliations/gpt_responses_batch_18.csv

Processing batch 19: 100%|██████████| 200/200 [01:24<00:00,  2.37it/s]

Batch 19 processed and saved to non-llm-author-affiliations/gpt_responses_batch_19.csv

Processing batch 20: 100%|██████████| 200/200 [01:21<00:00,  2.45it/s]

Batch 20 processed and saved to non-llm-author-affiliations/gpt_responses_batch_20.csv

Processing batch 21: 100%|██████████| 200/200 [01:26<00:00,  2.30it/s]

Batch 21 processed and saved to non-llm-author-affiliations/gpt_responses_batch_21.csv

Processing batch 22: 100%|██████████| 200/200 [01:27<00:00,  2.27it/s]

Batch 22 processed and saved to non-llm-author-affiliations/gpt_responses_batch_22.csv

Processing batch 23: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 23 processed and saved to non-llm-author-affiliations/gpt_responses_batch_23.csv

Processing batch 24: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 24 processed and saved to non-llm-author-affiliations/gpt_responses_batch_24.csv

Processing batch 25: 100%|██████████| 200/200 [01:25<00:00,  2.34it/s]

Batch 25 processed and saved to non-llm-author-affiliations/gpt_responses_batch_25.csv

Processing batch 26: 100%|██████████| 200/200 [01:25<00:00,  2.33it/s]

Batch 26 processed and saved to non-llm-author-affiliations/gpt_responses_batch_26.csv

Processing batch 27: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 27 processed and saved to non-llm-author-affiliations/gpt_responses_batch_27.csv

Processing batch 28: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 28 processed and saved to non-llm-author-affiliations/gpt_responses_batch_28.csv

Processing batch 29: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 29 processed and saved to non-llm-author-affiliations/gpt_responses_batch_29.csv

Processing batch 30: 100%|██████████| 200/200 [01:20<00:00,  2.48it/s]

Batch 30 processed and saved to non-llm-author-affiliations/gpt_responses_batch_30.csv

Processing batch 31: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 31 processed and saved to non-llm-author-affiliations/gpt_responses_batch_31.csv

Processing batch 32: 100%|██████████| 200/200 [01:25<00:00,  2.34it/s]

Batch 32 processed and saved to non-llm-author-affiliations/gpt_responses_batch_32.csv

Processing batch 33: 100%|██████████| 200/200 [01:25<00:00,  2.35it/s]

Batch 33 processed and saved to non-llm-author-affiliations/gpt_responses_batch_33.csv

Processing batch 34: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 34 processed and saved to non-llm-author-affiliations/gpt_responses_batch_34.csv

Processing batch 35: 100%|██████████| 200/200 [01:22<00:00,  2.41it/s]

Batch 35 processed and saved to non-llm-author-affiliations/gpt_responses_batch_35.csv

Processing batch 36: 100%|██████████| 200/200 [01:23<00:00,  2.39it/s]

Batch 36 processed and saved to non-llm-author-affiliations/gpt_responses_batch_36.csv

Processing batch 37: 100%|██████████| 200/200 [01:27<00:00,  2.29it/s]

Batch 37 processed and saved to non-llm-author-affiliations/gpt_responses_batch_37.csv

Processing batch 38: 100%|██████████| 200/200 [01:25<00:00,  2.34it/s]

Batch 38 processed and saved to non-llm-author-affiliations/gpt_responses_batch_38.csv

Processing batch 39: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 39 processed and saved to non-llm-author-affiliations/gpt_responses_batch_39.csv

Processing batch 40: 100%|██████████| 200/200 [01:22<00:00,  2.42it/s]

Batch 40 processed and saved to non-llm-author-affiliations/gpt_responses_batch_40.csv

Processing batch 41: 100%|██████████| 200/200 [01:23<00:00,  2.38it/s]

Batch 41 processed and saved to non-llm-author-affiliations/gpt_responses_batch_41.csv

Processing batch 42: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 42 processed and saved to non-llm-author-affiliations/gpt_responses_batch_42.csv

Processing batch 43: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 43 processed and saved to non-llm-author-affiliations/gpt_responses_batch_43.csv

Processing batch 44: 100%|██████████| 200/200 [01:26<00:00,  2.31it/s]

Batch 44 processed and saved to non-llm-author-affiliations/gpt_responses_batch_44.csv

Processing batch 45: 100%|██████████| 200/200 [01:23<00:00,  2.38it/s]

Batch 45 processed and saved to non-llm-author-affiliations/gpt_responses_batch_45.csv

Processing batch 46: 100%|██████████| 200/200 [01:26<00:00,  2.30it/s]

Batch 46 processed and saved to non-llm-author-affiliations/gpt_responses_batch_46.csv

Processing batch 47: 100%|██████████| 200/200 [01:23<00:00,  2.39it/s]

Batch 47 processed and saved to non-llm-author-affiliations/gpt_responses_batch_47.csv

Processing batch 48: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 48 processed and saved to non-llm-author-affiliations/gpt_responses_batch_48.csv

Processing batch 49: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 49 processed and saved to non-llm-author-affiliations/gpt_responses_batch_49.csv

Processing batch 50: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 50 processed and saved to non-llm-author-affiliations/gpt_responses_batch_50.csv

Processing batch 51: 100%|██████████| 200/200 [01:21<00:00,  2.46it/s]

Batch 51 processed and saved to non-llm-author-affiliations/gpt_responses_batch_51.csv

Processing batch 52: 100%|██████████| 200/200 [01:25<00:00,  2.35it/s]

Batch 52 processed and saved to non-llm-author-affiliations/gpt_responses_batch_52.csv

Processing batch 53: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 53 processed and saved to non-llm-author-affiliations/gpt_responses_batch_53.csv

Processing batch 54: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 54 processed and saved to non-llm-author-affiliations/gpt_responses_batch_54.csv

Processing batch 55: 100%|██████████| 200/200 [01:25<00:00,  2.33it/s]

Batch 55 processed and saved to non-llm-author-affiliations/gpt_responses_batch_55.csv

Processing batch 56: 100%|██████████| 200/200 [01:23<00:00,  2.38it/s]

Batch 56 processed and saved to non-llm-author-affiliations/gpt_responses_batch_56.csv

Processing batch 57: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 57 processed and saved to non-llm-author-affiliations/gpt_responses_batch_57.csv

Processing batch 58: 100%|██████████| 200/200 [01:24<00:00,  2.36it/s]

Batch 58 processed and saved to non-llm-author-affiliations/gpt_responses_batch_58.csv

Processing batch 59: 100%|██████████| 200/200 [01:23<00:00,  2.38it/s]

Batch 59 processed and saved to non-llm-author-affiliations/gpt_responses_batch_59.csv

Processing batch 60: 100%|██████████| 200/200 [01:25<00:00,  2.34it/s]

Batch 60 processed and saved to non-llm-author-affiliations/gpt_responses_batch_60.csv

Processing batch 61: 100%|██████████| 200/200 [01:26<00:00,  2.32it/s]

Batch 61 processed and saved to non-llm-author-affiliations/gpt_responses_batch_61.csv

Processing batch 62: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 62 processed and saved to non-llm-author-affiliations/gpt_responses_batch_62.csv

Processing batch 63: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 63 processed and saved to non-llm-author-affiliations/gpt_responses_batch_63.csv

Processing batch 64: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 64 processed and saved to non-llm-author-affiliations/gpt_responses_batch_64.csv

Processing batch 65: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 65 processed and saved to non-llm-author-affiliations/gpt_responses_batch_65.csv

Processing batch 66: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 66 processed and saved to non-llm-author-affiliations/gpt_responses_batch_66.csv

Processing batch 67: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 67 processed and saved to non-llm-author-affiliations/gpt_responses_batch_67.csv

Processing batch 68: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 68 processed and saved to non-llm-author-affiliations/gpt_responses_batch_68.csv

Processing batch 69: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 69 processed and saved to non-llm-author-affiliations/gpt_responses_batch_69.csv

Processing batch 70: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 70 processed and saved to non-llm-author-affiliations/gpt_responses_batch_70.csv

Processing batch 71: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 71 processed and saved to non-llm-author-affiliations/gpt_responses_batch_71.csv

Processing batch 72: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 72 processed and saved to non-llm-author-affiliations/gpt_responses_batch_72.csv

Processing batch 73: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 73 processed and saved to non-llm-author-affiliations/gpt_responses_batch_73.csv

Processing batch 74: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 74 processed and saved to non-llm-author-affiliations/gpt_responses_batch_74.csv

Processing batch 75: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 75 processed and saved to non-llm-author-affiliations/gpt_responses_batch_75.csv

Processing batch 76: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 76 processed and saved to non-llm-author-affiliations/gpt_responses_batch_76.csv

Processing batch 77: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 77 processed and saved to non-llm-author-affiliations/gpt_responses_batch_77.csv

Processing batch 78: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 78 processed and saved to non-llm-author-affiliations/gpt_responses_batch_78.csv

Processing batch 79: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 79 processed and saved to non-llm-author-affiliations/gpt_responses_batch_79.csv

Processing batch 80: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 80 processed and saved to non-llm-author-affiliations/gpt_responses_batch_80.csv

Processing batch 81: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 81 processed and saved to non-llm-author-affiliations/gpt_responses_batch_81.csv

Processing batch 82: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 82 processed and saved to non-llm-author-affiliations/gpt_responses_batch_82.csv

Processing batch 83: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 83 processed and saved to non-llm-author-affiliations/gpt_responses_batch_83.csv

Processing batch 84: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 84 processed and saved to non-llm-author-affiliations/gpt_responses_batch_84.csv

Processing batch 85: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 85 processed and saved to non-llm-author-affiliations/gpt_responses_batch_85.csv

Processing batch 86: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 86 processed and saved to non-llm-author-affiliations/gpt_responses_batch_86.csv

Processing batch 87: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 87 processed and saved to non-llm-author-affiliations/gpt_responses_batch_87.csv

Processing batch 88: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 88 processed and saved to non-llm-author-affiliations/gpt_responses_batch_88.csv

Processing batch 89: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 89 processed and saved to non-llm-author-affiliations/gpt_responses_batch_89.csv

Processing batch 90: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 90 processed and saved to non-llm-author-affiliations/gpt_responses_batch_90.csv

Processing batch 91: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 91 processed and saved to non-llm-author-affiliations/gpt_responses_batch_91.csv

Processing batch 92: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 92 processed and saved to non-llm-author-affiliations/gpt_responses_batch_92.csv

Processing batch 93: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 93 processed and saved to non-llm-author-affiliations/gpt_responses_batch_93.csv

Processing batch 94: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 94 processed and saved to non-llm-author-affiliations/gpt_responses_batch_94.csv

Processing batch 95: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 95 processed and saved to non-llm-author-affiliations/gpt_responses_batch_95.csv

Processing batch 96: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 96 processed and saved to non-llm-author-affiliations/gpt_responses_batch_96.csv

Processing batch 97: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 97 processed and saved to non-llm-author-affiliations/gpt_responses_batch_97.csv

Processing batch 98: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 98 processed and saved to non-llm-author-affiliations/gpt_responses_batch_98.csv

Processing batch 99: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 99 processed and saved to non-llm-author-affiliations/gpt_responses_batch_99.csv

Processing batch 100: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 100 processed and saved to non-llm-author-affiliations/gpt_responses_batch_100.csv

Processing batch 101: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 101 processed and saved to non-llm-author-affiliations/gpt_responses_batch_101.csv

Processing batch 102: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 102 processed and saved to non-llm-author-affiliations/gpt_responses_batch_102.csv

Processing batch 103: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 103 processed and saved to non-llm-author-affiliations/gpt_responses_batch_103.csv

Processing batch 104: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 104 processed and saved to non-llm-author-affiliations/gpt_responses_batch_104.csv

Processing batch 105: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 105 processed and saved to non-llm-author-affiliations/gpt_responses_batch_105.csv

Processing batch 106: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 106 processed and saved to non-llm-author-affiliations/gpt_responses_batch_106.csv

Processing batch 107: 100%|██████████| 200/200 [01:46<00:00,  1.89it/s]

Batch 107 processed and saved to non-llm-author-affiliations/gpt_responses_batch_107.csv

Processing batch 108: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 108 processed and saved to non-llm-author-affiliations/gpt_responses_batch_108.csv

Processing batch 109: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 109 processed and saved to non-llm-author-affiliations/gpt_responses_batch_109.csv

Processing batch 110: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 110 processed and saved to non-llm-author-affiliations/gpt_responses_batch_110.csv

Processing batch 111: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 111 processed and saved to non-llm-author-affiliations/gpt_responses_batch_111.csv

Processing batch 112: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 112 processed and saved to non-llm-author-affiliations/gpt_responses_batch_112.csv

Processing batch 113: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 113 processed and saved to non-llm-author-affiliations/gpt_responses_batch_113.csv

Processing batch 114: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 114 processed and saved to non-llm-author-affiliations/gpt_responses_batch_114.csv

Processing batch 115: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 115 processed and saved to non-llm-author-affiliations/gpt_responses_batch_115.csv

Processing batch 116: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 116 processed and saved to non-llm-author-affiliations/gpt_responses_batch_116.csv

Processing batch 117: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 117 processed and saved to non-llm-author-affiliations/gpt_responses_batch_117.csv

Processing batch 118: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 118 processed and saved to non-llm-author-affiliations/gpt_responses_batch_118.csv

Processing batch 119: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 119 processed and saved to non-llm-author-affiliations/gpt_responses_batch_119.csv

Processing batch 120: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 120 processed and saved to non-llm-author-affiliations/gpt_responses_batch_120.csv

Processing batch 121: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 121 processed and saved to non-llm-author-affiliations/gpt_responses_batch_121.csv

Processing batch 122: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 122 processed and saved to non-llm-author-affiliations/gpt_responses_batch_122.csv

Processing batch 123: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 123 processed and saved to non-llm-author-affiliations/gpt_responses_batch_123.csv

Processing batch 124: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 124 processed and saved to non-llm-author-affiliations/gpt_responses_batch_124.csv

Processing batch 125: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 125 processed and saved to non-llm-author-affiliations/gpt_responses_batch_125.csv

Processing batch 126: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 126 processed and saved to non-llm-author-affiliations/gpt_responses_batch_126.csv

Processing batch 127: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 127 processed and saved to non-llm-author-affiliations/gpt_responses_batch_127.csv

Processing batch 128: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 128 processed and saved to non-llm-author-affiliations/gpt_responses_batch_128.csv

Processing batch 129: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 129 processed and saved to non-llm-author-affiliations/gpt_responses_batch_129.csv

Processing batch 130: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 130 processed and saved to non-llm-author-affiliations/gpt_responses_batch_130.csv

Processing batch 131: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 131 processed and saved to non-llm-author-affiliations/gpt_responses_batch_131.csv

Processing batch 132: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 132 processed and saved to non-llm-author-affiliations/gpt_responses_batch_132.csv

Processing batch 133: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 133 processed and saved to non-llm-author-affiliations/gpt_responses_batch_133.csv

Processing batch 134: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 134 processed and saved to non-llm-author-affiliations/gpt_responses_batch_134.csv

Processing batch 135: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 135 processed and saved to non-llm-author-affiliations/gpt_responses_batch_135.csv

Processing batch 136: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 136 processed and saved to non-llm-author-affiliations/gpt_responses_batch_136.csv

Processing batch 137: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 137 processed and saved to non-llm-author-affiliations/gpt_responses_batch_137.csv

Processing batch 138: 100%|██████████| 200/200 [01:35<00:00,  2.08it/s]

Batch 138 processed and saved to non-llm-author-affiliations/gpt_responses_batch_138.csv

Processing batch 139: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 139 processed and saved to non-llm-author-affiliations/gpt_responses_batch_139.csv

Processing batch 140: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 140 processed and saved to non-llm-author-affiliations/gpt_responses_batch_140.csv

Processing batch 141: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 141 processed and saved to non-llm-author-affiliations/gpt_responses_batch_141.csv

Processing batch 142: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 142 processed and saved to non-llm-author-affiliations/gpt_responses_batch_142.csv

Processing batch 143: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 143 processed and saved to non-llm-author-affiliations/gpt_responses_batch_143.csv

Processing batch 144: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 144 processed and saved to non-llm-author-affiliations/gpt_responses_batch_144.csv

Processing batch 145: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 145 processed and saved to non-llm-author-affiliations/gpt_responses_batch_145.csv

Processing batch 146: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 146 processed and saved to non-llm-author-affiliations/gpt_responses_batch_146.csv

Processing batch 147: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 147 processed and saved to non-llm-author-affiliations/gpt_responses_batch_147.csv

Processing batch 148: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 148 processed and saved to non-llm-author-affiliations/gpt_responses_batch_148.csv

Processing batch 149: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 149 processed and saved to non-llm-author-affiliations/gpt_responses_batch_149.csv

Processing batch 150: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 150 processed and saved to non-llm-author-affiliations/gpt_responses_batch_150.csv

Processing batch 151: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 151 processed and saved to non-llm-author-affiliations/gpt_responses_batch_151.csv

Processing batch 152: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 152 processed and saved to non-llm-author-affiliations/gpt_responses_batch_152.csv

Processing batch 153: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 153 processed and saved to non-llm-author-affiliations/gpt_responses_batch_153.csv

Processing batch 154: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 154 processed and saved to non-llm-author-affiliations/gpt_responses_batch_154.csv

Processing batch 155: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 155 processed and saved to non-llm-author-affiliations/gpt_responses_batch_155.csv

Processing batch 156: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 156 processed and saved to non-llm-author-affiliations/gpt_responses_batch_156.csv

Processing batch 157: 100%|██████████| 200/200 [01:34<00:00,  2.13it/s]

Batch 157 processed and saved to non-llm-author-affiliations/gpt_responses_batch_157.csv

Processing batch 158: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 158 processed and saved to non-llm-author-affiliations/gpt_responses_batch_158.csv

Processing batch 159: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 159 processed and saved to non-llm-author-affiliations/gpt_responses_batch_159.csv

Processing batch 160: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 160 processed and saved to non-llm-author-affiliations/gpt_responses_batch_160.csv

Processing batch 161: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 161 processed and saved to non-llm-author-affiliations/gpt_responses_batch_161.csv

Processing batch 162: 100%|██████████| 200/200 [01:26<00:00,  2.31it/s]

Batch 162 processed and saved to non-llm-author-affiliations/gpt_responses_batch_162.csv

Processing batch 163: 100%|██████████| 200/200 [01:26<00:00,  2.31it/s]

Batch 163 processed and saved to non-llm-author-affiliations/gpt_responses_batch_163.csv

Processing batch 164: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 164 processed and saved to non-llm-author-affiliations/gpt_responses_batch_164.csv

Processing batch 165: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 165 processed and saved to non-llm-author-affiliations/gpt_responses_batch_165.csv

Processing batch 166: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 166 processed and saved to non-llm-author-affiliations/gpt_responses_batch_166.csv

Processing batch 167: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 167 processed and saved to non-llm-author-affiliations/gpt_responses_batch_167.csv

Processing batch 168: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 168 processed and saved to non-llm-author-affiliations/gpt_responses_batch_168.csv

Processing batch 169: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 169 processed and saved to non-llm-author-affiliations/gpt_responses_batch_169.csv

Processing batch 170: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 170 processed and saved to non-llm-author-affiliations/gpt_responses_batch_170.csv

Processing batch 171: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 171 processed and saved to non-llm-author-affiliations/gpt_responses_batch_171.csv

Processing batch 172: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 172 processed and saved to non-llm-author-affiliations/gpt_responses_batch_172.csv

Processing batch 173: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 173 processed and saved to non-llm-author-affiliations/gpt_responses_batch_173.csv

Processing batch 174: 100%|██████████| 200/200 [01:54<00:00,  1.75it/s]

Batch 174 processed and saved to non-llm-author-affiliations/gpt_responses_batch_174.csv

Processing batch 175: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 175 processed and saved to non-llm-author-affiliations/gpt_responses_batch_175.csv

Processing batch 176: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 176 processed and saved to non-llm-author-affiliations/gpt_responses_batch_176.csv

Processing batch 177: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 177 processed and saved to non-llm-author-affiliations/gpt_responses_batch_177.csv

Processing batch 178: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 178 processed and saved to non-llm-author-affiliations/gpt_responses_batch_178.csv

Processing batch 179: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 179 processed and saved to non-llm-author-affiliations/gpt_responses_batch_179.csv

Processing batch 180: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 180 processed and saved to non-llm-author-affiliations/gpt_responses_batch_180.csv

Processing batch 181: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 181 processed and saved to non-llm-author-affiliations/gpt_responses_batch_181.csv

Processing batch 182: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 182 processed and saved to non-llm-author-affiliations/gpt_responses_batch_182.csv

Processing batch 183: 100%|██████████| 200/200 [01:27<00:00,  2.28it/s]

Batch 183 processed and saved to non-llm-author-affiliations/gpt_responses_batch_183.csv

Processing batch 184: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 184 processed and saved to non-llm-author-affiliations/gpt_responses_batch_184.csv

Processing batch 185: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 185 processed and saved to non-llm-author-affiliations/gpt_responses_batch_185.csv

Processing batch 186: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 186 processed and saved to non-llm-author-affiliations/gpt_responses_batch_186.csv

Processing batch 187: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 187 processed and saved to non-llm-author-affiliations/gpt_responses_batch_187.csv

Processing batch 188: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 188 processed and saved to non-llm-author-affiliations/gpt_responses_batch_188.csv

Processing batch 189: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 189 processed and saved to non-llm-author-affiliations/gpt_responses_batch_189.csv

Processing batch 190: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 190 processed and saved to non-llm-author-affiliations/gpt_responses_batch_190.csv

Processing batch 191: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 191 processed and saved to non-llm-author-affiliations/gpt_responses_batch_191.csv

Processing batch 192: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 192 processed and saved to non-llm-author-affiliations/gpt_responses_batch_192.csv

Processing batch 193: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 193 processed and saved to non-llm-author-affiliations/gpt_responses_batch_193.csv

Processing batch 194: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 194 processed and saved to non-llm-author-affiliations/gpt_responses_batch_194.csv

Processing batch 195: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 195 processed and saved to non-llm-author-affiliations/gpt_responses_batch_195.csv

Processing batch 196: 100%|██████████| 200/200 [01:30<00:00,  2.21it/s]

Batch 196 processed and saved to non-llm-author-affiliations/gpt_responses_batch_196.csv

Processing batch 197: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 197 processed and saved to non-llm-author-affiliations/gpt_responses_batch_197.csv

Processing batch 198: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 198 processed and saved to non-llm-author-affiliations/gpt_responses_batch_198.csv

Processing batch 199: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 199 processed and saved to non-llm-author-affiliations/gpt_responses_batch_199.csv

Processing batch 200: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 200 processed and saved to non-llm-author-affiliations/gpt_responses_batch_200.csv

Processing batch 201: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 201 processed and saved to non-llm-author-affiliations/gpt_responses_batch_201.csv

Processing batch 202: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 202 processed and saved to non-llm-author-affiliations/gpt_responses_batch_202.csv

Processing batch 203: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 203 processed and saved to non-llm-author-affiliations/gpt_responses_batch_203.csv

Processing batch 204: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 204 processed and saved to non-llm-author-affiliations/gpt_responses_batch_204.csv

Processing batch 205: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 205 processed and saved to non-llm-author-affiliations/gpt_responses_batch_205.csv

Processing batch 206: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 206 processed and saved to non-llm-author-affiliations/gpt_responses_batch_206.csv

Processing batch 207: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 207 processed and saved to non-llm-author-affiliations/gpt_responses_batch_207.csv

Processing batch 208: 100%|██████████| 200/200 [01:50<00:00,  1.80it/s]

Batch 208 processed and saved to non-llm-author-affiliations/gpt_responses_batch_208.csv

Processing batch 209: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 209 processed and saved to non-llm-author-affiliations/gpt_responses_batch_209.csv

Processing batch 210: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 210 processed and saved to non-llm-author-affiliations/gpt_responses_batch_210.csv

Processing batch 211: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 211 processed and saved to non-llm-author-affiliations/gpt_responses_batch_211.csv

Processing batch 212: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 212 processed and saved to non-llm-author-affiliations/gpt_responses_batch_212.csv

Processing batch 213: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 213 processed and saved to non-llm-author-affiliations/gpt_responses_batch_213.csv

Processing batch 214: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 214 processed and saved to non-llm-author-affiliations/gpt_responses_batch_214.csv

Processing batch 215: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 215 processed and saved to non-llm-author-affiliations/gpt_responses_batch_215.csv

Processing batch 216: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 216 processed and saved to non-llm-author-affiliations/gpt_responses_batch_216.csv

Processing batch 217: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 217 processed and saved to non-llm-author-affiliations/gpt_responses_batch_217.csv

Processing batch 218: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 218 processed and saved to non-llm-author-affiliations/gpt_responses_batch_218.csv

Processing batch 219: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 219 processed and saved to non-llm-author-affiliations/gpt_responses_batch_219.csv

Processing batch 220: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 220 processed and saved to non-llm-author-affiliations/gpt_responses_batch_220.csv

Processing batch 221: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 221 processed and saved to non-llm-author-affiliations/gpt_responses_batch_221.csv

Processing batch 222: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 222 processed and saved to non-llm-author-affiliations/gpt_responses_batch_222.csv

Processing batch 223: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 223 processed and saved to non-llm-author-affiliations/gpt_responses_batch_223.csv

Processing batch 224: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 224 processed and saved to non-llm-author-affiliations/gpt_responses_batch_224.csv

Processing batch 225: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 225 processed and saved to non-llm-author-affiliations/gpt_responses_batch_225.csv

Processing batch 226: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 226 processed and saved to non-llm-author-affiliations/gpt_responses_batch_226.csv

Processing batch 227: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 227 processed and saved to non-llm-author-affiliations/gpt_responses_batch_227.csv

Processing batch 228: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 228 processed and saved to non-llm-author-affiliations/gpt_responses_batch_228.csv

Processing batch 229: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 229 processed and saved to non-llm-author-affiliations/gpt_responses_batch_229.csv

Processing batch 230: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 230 processed and saved to non-llm-author-affiliations/gpt_responses_batch_230.csv

Processing batch 231: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 231 processed and saved to non-llm-author-affiliations/gpt_responses_batch_231.csv

Processing batch 232: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 232 processed and saved to non-llm-author-affiliations/gpt_responses_batch_232.csv

Processing batch 233: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 233 processed and saved to non-llm-author-affiliations/gpt_responses_batch_233.csv

Processing batch 234: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 234 processed and saved to non-llm-author-affiliations/gpt_responses_batch_234.csv

Processing batch 235: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 235 processed and saved to non-llm-author-affiliations/gpt_responses_batch_235.csv

Processing batch 236: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 236 processed and saved to non-llm-author-affiliations/gpt_responses_batch_236.csv

Processing batch 237: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 237 processed and saved to non-llm-author-affiliations/gpt_responses_batch_237.csv

Processing batch 238: 100%|██████████| 200/200 [01:30<00:00,  2.20it/s]

Batch 238 processed and saved to non-llm-author-affiliations/gpt_responses_batch_238.csv

Processing batch 239: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 239 processed and saved to non-llm-author-affiliations/gpt_responses_batch_239.csv

Processing batch 240: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 240 processed and saved to non-llm-author-affiliations/gpt_responses_batch_240.csv

Processing batch 241: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 241 processed and saved to non-llm-author-affiliations/gpt_responses_batch_241.csv

Processing batch 242: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 242 processed and saved to non-llm-author-affiliations/gpt_responses_batch_242.csv

Processing batch 243: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 243 processed and saved to non-llm-author-affiliations/gpt_responses_batch_243.csv

Processing batch 244: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 244 processed and saved to non-llm-author-affiliations/gpt_responses_batch_244.csv

Processing batch 245: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 245 processed and saved to non-llm-author-affiliations/gpt_responses_batch_245.csv

Processing batch 246: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 246 processed and saved to non-llm-author-affiliations/gpt_responses_batch_246.csv

Processing batch 247: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 247 processed and saved to non-llm-author-affiliations/gpt_responses_batch_247.csv

Processing batch 248: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 248 processed and saved to non-llm-author-affiliations/gpt_responses_batch_248.csv

Processing batch 249: 100%|██████████| 200/200 [01:49<00:00,  1.82it/s]

Batch 249 processed and saved to non-llm-author-affiliations/gpt_responses_batch_249.csv

Processing batch 250: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 250 processed and saved to non-llm-author-affiliations/gpt_responses_batch_250.csv

Processing batch 251: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 251 processed and saved to non-llm-author-affiliations/gpt_responses_batch_251.csv

Processing batch 252: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 252 processed and saved to non-llm-author-affiliations/gpt_responses_batch_252.csv

Processing batch 253: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 253 processed and saved to non-llm-author-affiliations/gpt_responses_batch_253.csv

Processing batch 254: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 254 processed and saved to non-llm-author-affiliations/gpt_responses_batch_254.csv

Processing batch 255: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 255 processed and saved to non-llm-author-affiliations/gpt_responses_batch_255.csv

Processing batch 256: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 256 processed and saved to non-llm-author-affiliations/gpt_responses_batch_256.csv

Processing batch 257: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 257 processed and saved to non-llm-author-affiliations/gpt_responses_batch_257.csv

Processing batch 258: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 258 processed and saved to non-llm-author-affiliations/gpt_responses_batch_258.csv

Processing batch 259: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 259 processed and saved to non-llm-author-affiliations/gpt_responses_batch_259.csv

Processing batch 260: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 260 processed and saved to non-llm-author-affiliations/gpt_responses_batch_260.csv

Processing batch 261: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 261 processed and saved to non-llm-author-affiliations/gpt_responses_batch_261.csv

Processing batch 262: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 262 processed and saved to non-llm-author-affiliations/gpt_responses_batch_262.csv

Processing batch 263: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 263 processed and saved to non-llm-author-affiliations/gpt_responses_batch_263.csv

Processing batch 264: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 264 processed and saved to non-llm-author-affiliations/gpt_responses_batch_264.csv

Processing batch 265: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 265 processed and saved to non-llm-author-affiliations/gpt_responses_batch_265.csv

Processing batch 266: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 266 processed and saved to non-llm-author-affiliations/gpt_responses_batch_266.csv

Processing batch 267: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 267 processed and saved to non-llm-author-affiliations/gpt_responses_batch_267.csv

Processing batch 268: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 268 processed and saved to non-llm-author-affiliations/gpt_responses_batch_268.csv

Processing batch 269: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 269 processed and saved to non-llm-author-affiliations/gpt_responses_batch_269.csv

Processing batch 270: 100%|██████████| 200/200 [02:08<00:00,  1.56it/s]

Batch 270 processed and saved to non-llm-author-affiliations/gpt_responses_batch_270.csv

Processing batch 271: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 271 processed and saved to non-llm-author-affiliations/gpt_responses_batch_271.csv

Processing batch 272: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 272 processed and saved to non-llm-author-affiliations/gpt_responses_batch_272.csv

Processing batch 273: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 273 processed and saved to non-llm-author-affiliations/gpt_responses_batch_273.csv

Processing batch 274: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 274 processed and saved to non-llm-author-affiliations/gpt_responses_batch_274.csv

Processing batch 275: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 275 processed and saved to non-llm-author-affiliations/gpt_responses_batch_275.csv

Processing batch 276: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 276 processed and saved to non-llm-author-affiliations/gpt_responses_batch_276.csv

Processing batch 277: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 277 processed and saved to non-llm-author-affiliations/gpt_responses_batch_277.csv

Processing batch 278: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 278 processed and saved to non-llm-author-affiliations/gpt_responses_batch_278.csv

Processing batch 279: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 279 processed and saved to non-llm-author-affiliations/gpt_responses_batch_279.csv

Processing batch 280: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 280 processed and saved to non-llm-author-affiliations/gpt_responses_batch_280.csv

Processing batch 281: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 281 processed and saved to non-llm-author-affiliations/gpt_responses_batch_281.csv

Processing batch 282: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 282 processed and saved to non-llm-author-affiliations/gpt_responses_batch_282.csv

Processing batch 283: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 283 processed and saved to non-llm-author-affiliations/gpt_responses_batch_283.csv

Processing batch 284: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 284 processed and saved to non-llm-author-affiliations/gpt_responses_batch_284.csv

Processing batch 285: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 285 processed and saved to non-llm-author-affiliations/gpt_responses_batch_285.csv

Processing batch 286: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 286 processed and saved to non-llm-author-affiliations/gpt_responses_batch_286.csv

Processing batch 287: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 287 processed and saved to non-llm-author-affiliations/gpt_responses_batch_287.csv

Processing batch 288: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 288 processed and saved to non-llm-author-affiliations/gpt_responses_batch_288.csv

Processing batch 289: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 289 processed and saved to non-llm-author-affiliations/gpt_responses_batch_289.csv

Processing batch 290: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 290 processed and saved to non-llm-author-affiliations/gpt_responses_batch_290.csv

Processing batch 291: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 291 processed and saved to non-llm-author-affiliations/gpt_responses_batch_291.csv

Processing batch 292: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 292 processed and saved to non-llm-author-affiliations/gpt_responses_batch_292.csv

Processing batch 293: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 293 processed and saved to non-llm-author-affiliations/gpt_responses_batch_293.csv

Processing batch 294: 100%|██████████| 200/200 [01:46<00:00,  1.89it/s]

Batch 294 processed and saved to non-llm-author-affiliations/gpt_responses_batch_294.csv

Processing batch 295: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 295 processed and saved to non-llm-author-affiliations/gpt_responses_batch_295.csv

Processing batch 296: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 296 processed and saved to non-llm-author-affiliations/gpt_responses_batch_296.csv

Processing batch 297: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 297 processed and saved to non-llm-author-affiliations/gpt_responses_batch_297.csv

Processing batch 298: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 298 processed and saved to non-llm-author-affiliations/gpt_responses_batch_298.csv

Processing batch 299: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 299 processed and saved to non-llm-author-affiliations/gpt_responses_batch_299.csv

Processing batch 300: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 300 processed and saved to non-llm-author-affiliations/gpt_responses_batch_300.csv

Processing batch 301: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 301 processed and saved to non-llm-author-affiliations/gpt_responses_batch_301.csv

Processing batch 302: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 302 processed and saved to non-llm-author-affiliations/gpt_responses_batch_302.csv

Processing batch 303: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 303 processed and saved to non-llm-author-affiliations/gpt_responses_batch_303.csv

Processing batch 304: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 304 processed and saved to non-llm-author-affiliations/gpt_responses_batch_304.csv

Processing batch 305: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 305 processed and saved to non-llm-author-affiliations/gpt_responses_batch_305.csv

Processing batch 306: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 306 processed and saved to non-llm-author-affiliations/gpt_responses_batch_306.csv

Processing batch 307: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 307 processed and saved to non-llm-author-affiliations/gpt_responses_batch_307.csv

Processing batch 308: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 308 processed and saved to non-llm-author-affiliations/gpt_responses_batch_308.csv

Processing batch 309: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 309 processed and saved to non-llm-author-affiliations/gpt_responses_batch_309.csv

Processing batch 310: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 310 processed and saved to non-llm-author-affiliations/gpt_responses_batch_310.csv

Processing batch 311: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 311 processed and saved to non-llm-author-affiliations/gpt_responses_batch_311.csv

Processing batch 312: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 312 processed and saved to non-llm-author-affiliations/gpt_responses_batch_312.csv

Processing batch 313: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 313 processed and saved to non-llm-author-affiliations/gpt_responses_batch_313.csv

Processing batch 314: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

Batch 314 processed and saved to non-llm-author-affiliations/gpt_responses_batch_314.csv

Processing batch 315: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 315 processed and saved to non-llm-author-affiliations/gpt_responses_batch_315.csv

Processing batch 316: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 316 processed and saved to non-llm-author-affiliations/gpt_responses_batch_316.csv

Processing batch 317: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 317 processed and saved to non-llm-author-affiliations/gpt_responses_batch_317.csv

Processing batch 318: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 318 processed and saved to non-llm-author-affiliations/gpt_responses_batch_318.csv

Processing batch 319: 100%|██████████| 200/200 [01:41<00:00,  1.96it/s]

Batch 319 processed and saved to non-llm-author-affiliations/gpt_responses_batch_319.csv

Processing batch 320: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 320 processed and saved to non-llm-author-affiliations/gpt_responses_batch_320.csv

Processing batch 321: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 321 processed and saved to non-llm-author-affiliations/gpt_responses_batch_321.csv

Processing batch 322: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 322 processed and saved to non-llm-author-affiliations/gpt_responses_batch_322.csv

Processing batch 323: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 323 processed and saved to non-llm-author-affiliations/gpt_responses_batch_323.csv

Processing batch 324: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 324 processed and saved to non-llm-author-affiliations/gpt_responses_batch_324.csv

Processing batch 325: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 325 processed and saved to non-llm-author-affiliations/gpt_responses_batch_325.csv

Processing batch 326: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 326 processed and saved to non-llm-author-affiliations/gpt_responses_batch_326.csv

Processing batch 327: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 327 processed and saved to non-llm-author-affiliations/gpt_responses_batch_327.csv

Processing batch 328: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 328 processed and saved to non-llm-author-affiliations/gpt_responses_batch_328.csv

Processing batch 329: 100%|██████████| 200/200 [02:00<00:00,  1.66it/s]

Batch 329 processed and saved to non-llm-author-affiliations/gpt_responses_batch_329.csv

Processing batch 330: 100%|██████████| 200/200 [01:52<00:00,  1.79it/s]

Batch 330 processed and saved to non-llm-author-affiliations/gpt_responses_batch_330.csv

Processing batch 331: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 331 processed and saved to non-llm-author-affiliations/gpt_responses_batch_331.csv

Processing batch 332: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 332 processed and saved to non-llm-author-affiliations/gpt_responses_batch_332.csv

Processing batch 333: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 333 processed and saved to non-llm-author-affiliations/gpt_responses_batch_333.csv

Processing batch 334: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 334 processed and saved to non-llm-author-affiliations/gpt_responses_batch_334.csv

Processing batch 335: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 335 processed and saved to non-llm-author-affiliations/gpt_responses_batch_335.csv

Processing batch 336: 100%|██████████| 200/200 [01:54<00:00,  1.75it/s]

Batch 336 processed and saved to non-llm-author-affiliations/gpt_responses_batch_336.csv

Processing batch 337: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 337 processed and saved to non-llm-author-affiliations/gpt_responses_batch_337.csv

Processing batch 338: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 338 processed and saved to non-llm-author-affiliations/gpt_responses_batch_338.csv

Processing batch 339: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 339 processed and saved to non-llm-author-affiliations/gpt_responses_batch_339.csv

Processing batch 340: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 340 processed and saved to non-llm-author-affiliations/gpt_responses_batch_340.csv

Processing batch 341: 100%|██████████| 200/200 [01:29<00:00,  2.24it/s]

Batch 341 processed and saved to non-llm-author-affiliations/gpt_responses_batch_341.csv

Processing batch 342: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 342 processed and saved to non-llm-author-affiliations/gpt_responses_batch_342.csv

Processing batch 343: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 343 processed and saved to non-llm-author-affiliations/gpt_responses_batch_343.csv

Processing batch 344: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 344 processed and saved to non-llm-author-affiliations/gpt_responses_batch_344.csv

Processing batch 345: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 345 processed and saved to non-llm-author-affiliations/gpt_responses_batch_345.csv

Processing batch 346: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 346 processed and saved to non-llm-author-affiliations/gpt_responses_batch_346.csv

Processing batch 347: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 347 processed and saved to non-llm-author-affiliations/gpt_responses_batch_347.csv

Processing batch 348: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 348 processed and saved to non-llm-author-affiliations/gpt_responses_batch_348.csv

Processing batch 349: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 349 processed and saved to non-llm-author-affiliations/gpt_responses_batch_349.csv

Processing batch 350: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 350 processed and saved to non-llm-author-affiliations/gpt_responses_batch_350.csv

Processing batch 351: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 351 processed and saved to non-llm-author-affiliations/gpt_responses_batch_351.csv

Processing batch 352: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 352 processed and saved to non-llm-author-affiliations/gpt_responses_batch_352.csv

Processing batch 353: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 353 processed and saved to non-llm-author-affiliations/gpt_responses_batch_353.csv

Processing batch 354: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 354 processed and saved to non-llm-author-affiliations/gpt_responses_batch_354.csv

Processing batch 355: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 355 processed and saved to non-llm-author-affiliations/gpt_responses_batch_355.csv

Processing batch 356: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 356 processed and saved to non-llm-author-affiliations/gpt_responses_batch_356.csv

Processing batch 357: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 357 processed and saved to non-llm-author-affiliations/gpt_responses_batch_357.csv

Processing batch 358: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 358 processed and saved to non-llm-author-affiliations/gpt_responses_batch_358.csv

Processing batch 359: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 359 processed and saved to non-llm-author-affiliations/gpt_responses_batch_359.csv

Processing batch 360: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 360 processed and saved to non-llm-author-affiliations/gpt_responses_batch_360.csv

Processing batch 361: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 361 processed and saved to non-llm-author-affiliations/gpt_responses_batch_361.csv

Processing batch 362: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 362 processed and saved to non-llm-author-affiliations/gpt_responses_batch_362.csv

Processing batch 363: 100%|██████████| 200/200 [01:50<00:00,  1.81it/s]

Batch 363 processed and saved to non-llm-author-affiliations/gpt_responses_batch_363.csv

Processing batch 364: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 364 processed and saved to non-llm-author-affiliations/gpt_responses_batch_364.csv

Processing batch 365: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 365 processed and saved to non-llm-author-affiliations/gpt_responses_batch_365.csv

Processing batch 366: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 366 processed and saved to non-llm-author-affiliations/gpt_responses_batch_366.csv

Processing batch 367: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 367 processed and saved to non-llm-author-affiliations/gpt_responses_batch_367.csv

Processing batch 368: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 368 processed and saved to non-llm-author-affiliations/gpt_responses_batch_368.csv

Processing batch 369: 100%|██████████| 200/200 [01:48<00:00,  1.84it/s]

Batch 369 processed and saved to non-llm-author-affiliations/gpt_responses_batch_369.csv

Processing batch 370: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 370 processed and saved to non-llm-author-affiliations/gpt_responses_batch_370.csv

Processing batch 371: 100%|██████████| 200/200 [01:49<00:00,  1.83it/s]

Batch 371 processed and saved to non-llm-author-affiliations/gpt_responses_batch_371.csv

Processing batch 372: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 372 processed and saved to non-llm-author-affiliations/gpt_responses_batch_372.csv

Processing batch 373: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 373 processed and saved to non-llm-author-affiliations/gpt_responses_batch_373.csv

Processing batch 374: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 374 processed and saved to non-llm-author-affiliations/gpt_responses_batch_374.csv

Processing batch 375: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 375 processed and saved to non-llm-author-affiliations/gpt_responses_batch_375.csv

Processing batch 376: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 376 processed and saved to non-llm-author-affiliations/gpt_responses_batch_376.csv

Processing batch 377: 100%|██████████| 200/200 [01:43<00:00,  1.92it/s]

Batch 377 processed and saved to non-llm-author-affiliations/gpt_responses_batch_377.csv

Processing batch 378: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 378 processed and saved to non-llm-author-affiliations/gpt_responses_batch_378.csv

Processing batch 379: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 379 processed and saved to non-llm-author-affiliations/gpt_responses_batch_379.csv

Processing batch 380: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 380 processed and saved to non-llm-author-affiliations/gpt_responses_batch_380.csv

Processing batch 381: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 381 processed and saved to non-llm-author-affiliations/gpt_responses_batch_381.csv

Processing batch 382: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 382 processed and saved to non-llm-author-affiliations/gpt_responses_batch_382.csv

Processing batch 383: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 383 processed and saved to non-llm-author-affiliations/gpt_responses_batch_383.csv

Processing batch 384: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 384 processed and saved to non-llm-author-affiliations/gpt_responses_batch_384.csv

Processing batch 385: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 385 processed and saved to non-llm-author-affiliations/gpt_responses_batch_385.csv

Processing batch 386: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 386 processed and saved to non-llm-author-affiliations/gpt_responses_batch_386.csv

Processing batch 387: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 387 processed and saved to non-llm-author-affiliations/gpt_responses_batch_387.csv

Processing batch 388: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 388 processed and saved to non-llm-author-affiliations/gpt_responses_batch_388.csv

Processing batch 389: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 389 processed and saved to non-llm-author-affiliations/gpt_responses_batch_389.csv

Processing batch 390: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 390 processed and saved to non-llm-author-affiliations/gpt_responses_batch_390.csv

Processing batch 391: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 391 processed and saved to non-llm-author-affiliations/gpt_responses_batch_391.csv

Processing batch 392: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 392 processed and saved to non-llm-author-affiliations/gpt_responses_batch_392.csv

Processing batch 393: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 393 processed and saved to non-llm-author-affiliations/gpt_responses_batch_393.csv

Processing batch 394: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 394 processed and saved to non-llm-author-affiliations/gpt_responses_batch_394.csv

Processing batch 395: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 395 processed and saved to non-llm-author-affiliations/gpt_responses_batch_395.csv

Processing batch 396: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 396 processed and saved to non-llm-author-affiliations/gpt_responses_batch_396.csv

Processing batch 397: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 397 processed and saved to non-llm-author-affiliations/gpt_responses_batch_397.csv

Processing batch 398: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 398 processed and saved to non-llm-author-affiliations/gpt_responses_batch_398.csv

Processing batch 399: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 399 processed and saved to non-llm-author-affiliations/gpt_responses_batch_399.csv

Processing batch 400: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 400 processed and saved to non-llm-author-affiliations/gpt_responses_batch_400.csv

Processing batch 401: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 401 processed and saved to non-llm-author-affiliations/gpt_responses_batch_401.csv

Processing batch 402: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 402 processed and saved to non-llm-author-affiliations/gpt_responses_batch_402.csv

Processing batch 403: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 403 processed and saved to non-llm-author-affiliations/gpt_responses_batch_403.csv

Processing batch 404: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 404 processed and saved to non-llm-author-affiliations/gpt_responses_batch_404.csv

Processing batch 405: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 405 processed and saved to non-llm-author-affiliations/gpt_responses_batch_405.csv

Processing batch 406: 100%|██████████| 200/200 [01:47<00:00,  1.87it/s]

Batch 406 processed and saved to non-llm-author-affiliations/gpt_responses_batch_406.csv

Processing batch 407: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 407 processed and saved to non-llm-author-affiliations/gpt_responses_batch_407.csv

Processing batch 408: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 408 processed and saved to non-llm-author-affiliations/gpt_responses_batch_408.csv

Processing batch 409: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 409 processed and saved to non-llm-author-affiliations/gpt_responses_batch_409.csv

Processing batch 410: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 410 processed and saved to non-llm-author-affiliations/gpt_responses_batch_410.csv

Processing batch 411: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 411 processed and saved to non-llm-author-affiliations/gpt_responses_batch_411.csv

Processing batch 412: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 412 processed and saved to non-llm-author-affiliations/gpt_responses_batch_412.csv

Processing batch 413: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 413 processed and saved to non-llm-author-affiliations/gpt_responses_batch_413.csv

Processing batch 414: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 414 processed and saved to non-llm-author-affiliations/gpt_responses_batch_414.csv

Processing batch 415: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 415 processed and saved to non-llm-author-affiliations/gpt_responses_batch_415.csv

Processing batch 416: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 416 processed and saved to non-llm-author-affiliations/gpt_responses_batch_416.csv

Processing batch 417: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 417 processed and saved to non-llm-author-affiliations/gpt_responses_batch_417.csv

Processing batch 418: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 418 processed and saved to non-llm-author-affiliations/gpt_responses_batch_418.csv

Processing batch 419: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 419 processed and saved to non-llm-author-affiliations/gpt_responses_batch_419.csv

Processing batch 420: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 420 processed and saved to non-llm-author-affiliations/gpt_responses_batch_420.csv

Processing batch 421: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 421 processed and saved to non-llm-author-affiliations/gpt_responses_batch_421.csv

Processing batch 422: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 422 processed and saved to non-llm-author-affiliations/gpt_responses_batch_422.csv

Processing batch 423: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 423 processed and saved to non-llm-author-affiliations/gpt_responses_batch_423.csv

Processing batch 424: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 424 processed and saved to non-llm-author-affiliations/gpt_responses_batch_424.csv

Processing batch 425: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 425 processed and saved to non-llm-author-affiliations/gpt_responses_batch_425.csv

Processing batch 426: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 426 processed and saved to non-llm-author-affiliations/gpt_responses_batch_426.csv

Processing batch 427: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 427 processed and saved to non-llm-author-affiliations/gpt_responses_batch_427.csv

Processing batch 428: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 428 processed and saved to non-llm-author-affiliations/gpt_responses_batch_428.csv

Processing batch 429: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 429 processed and saved to non-llm-author-affiliations/gpt_responses_batch_429.csv

Processing batch 430: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 430 processed and saved to non-llm-author-affiliations/gpt_responses_batch_430.csv

Processing batch 431: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 431 processed and saved to non-llm-author-affiliations/gpt_responses_batch_431.csv

Processing batch 432: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 432 processed and saved to non-llm-author-affiliations/gpt_responses_batch_432.csv

Processing batch 433: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 433 processed and saved to non-llm-author-affiliations/gpt_responses_batch_433.csv

Processing batch 434: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 434 processed and saved to non-llm-author-affiliations/gpt_responses_batch_434.csv

Processing batch 435: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 435 processed and saved to non-llm-author-affiliations/gpt_responses_batch_435.csv

Processing batch 436: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 436 processed and saved to non-llm-author-affiliations/gpt_responses_batch_436.csv

Processing batch 437: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 437 processed and saved to non-llm-author-affiliations/gpt_responses_batch_437.csv

Processing batch 438: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 438 processed and saved to non-llm-author-affiliations/gpt_responses_batch_438.csv

Processing batch 439: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 439 processed and saved to non-llm-author-affiliations/gpt_responses_batch_439.csv

Processing batch 440: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 440 processed and saved to non-llm-author-affiliations/gpt_responses_batch_440.csv

Processing batch 441: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 441 processed and saved to non-llm-author-affiliations/gpt_responses_batch_441.csv

Processing batch 442: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 442 processed and saved to non-llm-author-affiliations/gpt_responses_batch_442.csv

Processing batch 443: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 443 processed and saved to non-llm-author-affiliations/gpt_responses_batch_443.csv

Processing batch 444: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 444 processed and saved to non-llm-author-affiliations/gpt_responses_batch_444.csv

Processing batch 445: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 445 processed and saved to non-llm-author-affiliations/gpt_responses_batch_445.csv

Processing batch 446: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 446 processed and saved to non-llm-author-affiliations/gpt_responses_batch_446.csv

Processing batch 447: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 447 processed and saved to non-llm-author-affiliations/gpt_responses_batch_447.csv

Processing batch 448: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 448 processed and saved to non-llm-author-affiliations/gpt_responses_batch_448.csv

Processing batch 449: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 449 processed and saved to non-llm-author-affiliations/gpt_responses_batch_449.csv

Processing batch 450: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 450 processed and saved to non-llm-author-affiliations/gpt_responses_batch_450.csv

Processing batch 451: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 451 processed and saved to non-llm-author-affiliations/gpt_responses_batch_451.csv

Processing batch 452: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 452 processed and saved to non-llm-author-affiliations/gpt_responses_batch_452.csv

Processing batch 453: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 453 processed and saved to non-llm-author-affiliations/gpt_responses_batch_453.csv

Processing batch 454: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 454 processed and saved to non-llm-author-affiliations/gpt_responses_batch_454.csv

Processing batch 455: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 455 processed and saved to non-llm-author-affiliations/gpt_responses_batch_455.csv

Processing batch 456: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 456 processed and saved to non-llm-author-affiliations/gpt_responses_batch_456.csv

Processing batch 457: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 457 processed and saved to non-llm-author-affiliations/gpt_responses_batch_457.csv

Processing batch 458: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 458 processed and saved to non-llm-author-affiliations/gpt_responses_batch_458.csv

Processing batch 459: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 459 processed and saved to non-llm-author-affiliations/gpt_responses_batch_459.csv

Processing batch 460: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 460 processed and saved to non-llm-author-affiliations/gpt_responses_batch_460.csv

Processing batch 461: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 461 processed and saved to non-llm-author-affiliations/gpt_responses_batch_461.csv

Processing batch 462: 100%|██████████| 200/200 [01:48<00:00,  1.85it/s]

Batch 462 processed and saved to non-llm-author-affiliations/gpt_responses_batch_462.csv

Processing batch 463: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 463 processed and saved to non-llm-author-affiliations/gpt_responses_batch_463.csv

Processing batch 464: 100%|██████████| 200/200 [02:12<00:00,  1.51it/s]

Batch 464 processed and saved to non-llm-author-affiliations/gpt_responses_batch_464.csv

Processing batch 465: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 465 processed and saved to non-llm-author-affiliations/gpt_responses_batch_465.csv

Processing batch 466: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 466 processed and saved to non-llm-author-affiliations/gpt_responses_batch_466.csv

Processing batch 467: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 467 processed and saved to non-llm-author-affiliations/gpt_responses_batch_467.csv

Processing batch 468: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 468 processed and saved to non-llm-author-affiliations/gpt_responses_batch_468.csv

Processing batch 469: 100%|██████████| 200/200 [01:53<00:00,  1.76it/s]

Batch 469 processed and saved to non-llm-author-affiliations/gpt_responses_batch_469.csv

Processing batch 470: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 470 processed and saved to non-llm-author-affiliations/gpt_responses_batch_470.csv

Processing batch 471: 100%|██████████| 200/200 [01:46<00:00,  1.88it/s]

Batch 471 processed and saved to non-llm-author-affiliations/gpt_responses_batch_471.csv

Processing batch 472: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 472 processed and saved to non-llm-author-affiliations/gpt_responses_batch_472.csv

Processing batch 473: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 473 processed and saved to non-llm-author-affiliations/gpt_responses_batch_473.csv

Processing batch 474: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 474 processed and saved to non-llm-author-affiliations/gpt_responses_batch_474.csv

Processing batch 475: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 475 processed and saved to non-llm-author-affiliations/gpt_responses_batch_475.csv

Processing batch 476: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 476 processed and saved to non-llm-author-affiliations/gpt_responses_batch_476.csv

Processing batch 477: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 477 processed and saved to non-llm-author-affiliations/gpt_responses_batch_477.csv

Processing batch 478: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 478 processed and saved to non-llm-author-affiliations/gpt_responses_batch_478.csv

Processing batch 479: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 479 processed and saved to non-llm-author-affiliations/gpt_responses_batch_479.csv

Processing batch 480: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 480 processed and saved to non-llm-author-affiliations/gpt_responses_batch_480.csv

Processing batch 481: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 481 processed and saved to non-llm-author-affiliations/gpt_responses_batch_481.csv

Processing batch 482: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 482 processed and saved to non-llm-author-affiliations/gpt_responses_batch_482.csv

Processing batch 483: 100%|██████████| 200/200 [01:40<00:00,  2.00it/s]

Batch 483 processed and saved to non-llm-author-affiliations/gpt_responses_batch_483.csv

Processing batch 484: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 484 processed and saved to non-llm-author-affiliations/gpt_responses_batch_484.csv

Processing batch 485: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 485 processed and saved to non-llm-author-affiliations/gpt_responses_batch_485.csv

Processing batch 486: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 486 processed and saved to non-llm-author-affiliations/gpt_responses_batch_486.csv

Processing batch 487: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 487 processed and saved to non-llm-author-affiliations/gpt_responses_batch_487.csv

Processing batch 488: 100%|██████████| 200/200 [01:53<00:00,  1.76it/s]

Batch 488 processed and saved to non-llm-author-affiliations/gpt_responses_batch_488.csv

Processing batch 489: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 489 processed and saved to non-llm-author-affiliations/gpt_responses_batch_489.csv

Processing batch 490: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 490 processed and saved to non-llm-author-affiliations/gpt_responses_batch_490.csv

Processing batch 491: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 491 processed and saved to non-llm-author-affiliations/gpt_responses_batch_491.csv

Processing batch 492: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 492 processed and saved to non-llm-author-affiliations/gpt_responses_batch_492.csv

Processing batch 493: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 493 processed and saved to non-llm-author-affiliations/gpt_responses_batch_493.csv

Processing batch 494: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 494 processed and saved to non-llm-author-affiliations/gpt_responses_batch_494.csv

Processing batch 495: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 495 processed and saved to non-llm-author-affiliations/gpt_responses_batch_495.csv

Processing batch 496: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 496 processed and saved to non-llm-author-affiliations/gpt_responses_batch_496.csv

Processing batch 497: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 497 processed and saved to non-llm-author-affiliations/gpt_responses_batch_497.csv

Processing batch 498: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 498 processed and saved to non-llm-author-affiliations/gpt_responses_batch_498.csv

Processing batch 499: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 499 processed and saved to non-llm-author-affiliations/gpt_responses_batch_499.csv

Processing batch 500: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 500 processed and saved to non-llm-author-affiliations/gpt_responses_batch_500.csv

Processing batch 501: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 501 processed and saved to non-llm-author-affiliations/gpt_responses_batch_501.csv

Processing batch 502: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 502 processed and saved to non-llm-author-affiliations/gpt_responses_batch_502.csv

Processing batch 503: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 503 processed and saved to non-llm-author-affiliations/gpt_responses_batch_503.csv

Processing batch 504: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 504 processed and saved to non-llm-author-affiliations/gpt_responses_batch_504.csv

Processing batch 505: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 505 processed and saved to non-llm-author-affiliations/gpt_responses_batch_505.csv

Processing batch 506: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 506 processed and saved to non-llm-author-affiliations/gpt_responses_batch_506.csv

Processing batch 507: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 507 processed and saved to non-llm-author-affiliations/gpt_responses_batch_507.csv

Processing batch 508: 100%|██████████| 200/200 [01:46<00:00,  1.87it/s]

Batch 508 processed and saved to non-llm-author-affiliations/gpt_responses_batch_508.csv

Processing batch 509: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 509 processed and saved to non-llm-author-affiliations/gpt_responses_batch_509.csv

Processing batch 510: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 510 processed and saved to non-llm-author-affiliations/gpt_responses_batch_510.csv

Processing batch 511: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 511 processed and saved to non-llm-author-affiliations/gpt_responses_batch_511.csv

Processing batch 512: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 512 processed and saved to non-llm-author-affiliations/gpt_responses_batch_512.csv

Processing batch 513: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 513 processed and saved to non-llm-author-affiliations/gpt_responses_batch_513.csv

Processing batch 514: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 514 processed and saved to non-llm-author-affiliations/gpt_responses_batch_514.csv

Processing batch 515: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 515 processed and saved to non-llm-author-affiliations/gpt_responses_batch_515.csv

Processing batch 516: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 516 processed and saved to non-llm-author-affiliations/gpt_responses_batch_516.csv

Processing batch 517: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 517 processed and saved to non-llm-author-affiliations/gpt_responses_batch_517.csv

Processing batch 518: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 518 processed and saved to non-llm-author-affiliations/gpt_responses_batch_518.csv

Processing batch 519: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 519 processed and saved to non-llm-author-affiliations/gpt_responses_batch_519.csv

Processing batch 520: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 520 processed and saved to non-llm-author-affiliations/gpt_responses_batch_520.csv

Processing batch 521: 100%|██████████| 200/200 [01:40<00:00,  1.99it/s]

Batch 521 processed and saved to non-llm-author-affiliations/gpt_responses_batch_521.csv

Processing batch 522: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 522 processed and saved to non-llm-author-affiliations/gpt_responses_batch_522.csv

Processing batch 523: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 523 processed and saved to non-llm-author-affiliations/gpt_responses_batch_523.csv

Processing batch 524: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 524 processed and saved to non-llm-author-affiliations/gpt_responses_batch_524.csv

Processing batch 525: 100%|██████████| 200/200 [01:33<00:00,  2.15it/s]

Batch 525 processed and saved to non-llm-author-affiliations/gpt_responses_batch_525.csv

Processing batch 526: 100%|██████████| 200/200 [01:28<00:00,  2.27it/s]

Batch 526 processed and saved to non-llm-author-affiliations/gpt_responses_batch_526.csv

Processing batch 527: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 527 processed and saved to non-llm-author-affiliations/gpt_responses_batch_527.csv

Processing batch 528: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 528 processed and saved to non-llm-author-affiliations/gpt_responses_batch_528.csv

Processing batch 529: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 529 processed and saved to non-llm-author-affiliations/gpt_responses_batch_529.csv

Processing batch 530: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 530 processed and saved to non-llm-author-affiliations/gpt_responses_batch_530.csv

Processing batch 531: 100%|██████████| 200/200 [01:51<00:00,  1.79it/s]

Batch 531 processed and saved to non-llm-author-affiliations/gpt_responses_batch_531.csv

Processing batch 532: 100%|██████████| 200/200 [01:38<00:00,  2.02it/s]

Batch 532 processed and saved to non-llm-author-affiliations/gpt_responses_batch_532.csv

Processing batch 533: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 533 processed and saved to non-llm-author-affiliations/gpt_responses_batch_533.csv

Processing batch 534: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 534 processed and saved to non-llm-author-affiliations/gpt_responses_batch_534.csv

Processing batch 535: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 535 processed and saved to non-llm-author-affiliations/gpt_responses_batch_535.csv

Processing batch 536: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 536 processed and saved to non-llm-author-affiliations/gpt_responses_batch_536.csv

Processing batch 537: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 537 processed and saved to non-llm-author-affiliations/gpt_responses_batch_537.csv

Processing batch 538: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 538 processed and saved to non-llm-author-affiliations/gpt_responses_batch_538.csv

Processing batch 539: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 539 processed and saved to non-llm-author-affiliations/gpt_responses_batch_539.csv

Processing batch 540: 100%|██████████| 200/200 [01:31<00:00,  2.18it/s]

Batch 540 processed and saved to non-llm-author-affiliations/gpt_responses_batch_540.csv

Processing batch 541: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 541 processed and saved to non-llm-author-affiliations/gpt_responses_batch_541.csv

Processing batch 542: 100%|██████████| 200/200 [01:32<00:00,  2.16it/s]

Batch 542 processed and saved to non-llm-author-affiliations/gpt_responses_batch_542.csv

Processing batch 543: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 543 processed and saved to non-llm-author-affiliations/gpt_responses_batch_543.csv

Processing batch 544: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 544 processed and saved to non-llm-author-affiliations/gpt_responses_batch_544.csv

Processing batch 545: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 545 processed and saved to non-llm-author-affiliations/gpt_responses_batch_545.csv

Processing batch 546: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 546 processed and saved to non-llm-author-affiliations/gpt_responses_batch_546.csv

Processing batch 547: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 547 processed and saved to non-llm-author-affiliations/gpt_responses_batch_547.csv

Processing batch 548: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 548 processed and saved to non-llm-author-affiliations/gpt_responses_batch_548.csv

Processing batch 549: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 549 processed and saved to non-llm-author-affiliations/gpt_responses_batch_549.csv

Processing batch 550: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 550 processed and saved to non-llm-author-affiliations/gpt_responses_batch_550.csv

Processing batch 551: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 551 processed and saved to non-llm-author-affiliations/gpt_responses_batch_551.csv

Processing batch 552: 100%|██████████| 200/200 [01:32<00:00,  2.15it/s]

Batch 552 processed and saved to non-llm-author-affiliations/gpt_responses_batch_552.csv

Processing batch 553: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 553 processed and saved to non-llm-author-affiliations/gpt_responses_batch_553.csv

Processing batch 554: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 554 processed and saved to non-llm-author-affiliations/gpt_responses_batch_554.csv

Processing batch 555: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 555 processed and saved to non-llm-author-affiliations/gpt_responses_batch_555.csv

Processing batch 556: 100%|██████████| 200/200 [01:47<00:00,  1.85it/s]

Batch 556 processed and saved to non-llm-author-affiliations/gpt_responses_batch_556.csv

Processing batch 557: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 557 processed and saved to non-llm-author-affiliations/gpt_responses_batch_557.csv

Processing batch 558: 100%|██████████| 200/200 [01:31<00:00,  2.19it/s]

Batch 558 processed and saved to non-llm-author-affiliations/gpt_responses_batch_558.csv

Processing batch 559: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 559 processed and saved to non-llm-author-affiliations/gpt_responses_batch_559.csv

Processing batch 560: 100%|██████████| 200/200 [01:42<00:00,  1.94it/s]

Batch 560 processed and saved to non-llm-author-affiliations/gpt_responses_batch_560.csv

Processing batch 561: 100%|██████████| 200/200 [01:29<00:00,  2.23it/s]

Batch 561 processed and saved to non-llm-author-affiliations/gpt_responses_batch_561.csv

Processing batch 562: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 562 processed and saved to non-llm-author-affiliations/gpt_responses_batch_562.csv

Processing batch 563: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 563 processed and saved to non-llm-author-affiliations/gpt_responses_batch_563.csv

Processing batch 564: 100%|██████████| 200/200 [01:33<00:00,  2.13it/s]

Batch 564 processed and saved to non-llm-author-affiliations/gpt_responses_batch_564.csv

Processing batch 565: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 565 processed and saved to non-llm-author-affiliations/gpt_responses_batch_565.csv

Processing batch 566: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

Batch 566 processed and saved to non-llm-author-affiliations/gpt_responses_batch_566.csv

Processing batch 567: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 567 processed and saved to non-llm-author-affiliations/gpt_responses_batch_567.csv

Processing batch 568: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 568 processed and saved to non-llm-author-affiliations/gpt_responses_batch_568.csv

Processing batch 569: 100%|██████████| 200/200 [01:38<00:00,  2.04it/s]

Batch 569 processed and saved to non-llm-author-affiliations/gpt_responses_batch_569.csv

Processing batch 570: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 570 processed and saved to non-llm-author-affiliations/gpt_responses_batch_570.csv

Processing batch 571: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 571 processed and saved to non-llm-author-affiliations/gpt_responses_batch_571.csv

Processing batch 572: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 572 processed and saved to non-llm-author-affiliations/gpt_responses_batch_572.csv

Processing batch 573: 100%|██████████| 200/200 [01:30<00:00,  2.22it/s]

Batch 573 processed and saved to non-llm-author-affiliations/gpt_responses_batch_573.csv

Processing batch 574: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 574 processed and saved to non-llm-author-affiliations/gpt_responses_batch_574.csv

Processing batch 575: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 575 processed and saved to non-llm-author-affiliations/gpt_responses_batch_575.csv

Processing batch 576: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 576 processed and saved to non-llm-author-affiliations/gpt_responses_batch_576.csv

Processing batch 577: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 577 processed and saved to non-llm-author-affiliations/gpt_responses_batch_577.csv

Processing batch 578: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 578 processed and saved to non-llm-author-affiliations/gpt_responses_batch_578.csv

Processing batch 579: 100%|██████████| 200/200 [01:35<00:00,  2.10it/s]

Batch 579 processed and saved to non-llm-author-affiliations/gpt_responses_batch_579.csv

Processing batch 580: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 580 processed and saved to non-llm-author-affiliations/gpt_responses_batch_580.csv

Processing batch 581: 100%|██████████| 200/200 [01:31<00:00,  2.20it/s]

Batch 581 processed and saved to non-llm-author-affiliations/gpt_responses_batch_581.csv

Processing batch 582: 100%|██████████| 200/200 [01:36<00:00,  2.07it/s]

Batch 582 processed and saved to non-llm-author-affiliations/gpt_responses_batch_582.csv

Processing batch 583: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 583 processed and saved to non-llm-author-affiliations/gpt_responses_batch_583.csv

Processing batch 584: 100%|██████████| 200/200 [01:37<00:00,  2.04it/s]

Batch 584 processed and saved to non-llm-author-affiliations/gpt_responses_batch_584.csv

Processing batch 585: 100%|██████████| 200/200 [01:28<00:00,  2.25it/s]

Batch 585 processed and saved to non-llm-author-affiliations/gpt_responses_batch_585.csv

Processing batch 586: 100%|██████████| 200/200 [01:31<00:00,  2.17it/s]

Batch 586 processed and saved to non-llm-author-affiliations/gpt_responses_batch_586.csv

Processing batch 587: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 587 processed and saved to non-llm-author-affiliations/gpt_responses_batch_587.csv

Processing batch 588: 100%|██████████| 200/200 [01:44<00:00,  1.91it/s]

Batch 588 processed and saved to non-llm-author-affiliations/gpt_responses_batch_588.csv

Processing batch 589: 100%|██████████| 200/200 [01:45<00:00,  1.90it/s]

Batch 589 processed and saved to non-llm-author-affiliations/gpt_responses_batch_589.csv

Processing batch 590: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 590 processed and saved to non-llm-author-affiliations/gpt_responses_batch_590.csv

Processing batch 591: 100%|██████████| 200/200 [01:36<00:00,  2.06it/s]

Batch 591 processed and saved to non-llm-author-affiliations/gpt_responses_batch_591.csv

Processing batch 592: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 592 processed and saved to non-llm-author-affiliations/gpt_responses_batch_592.csv

Processing batch 593: 100%|██████████| 200/200 [01:34<00:00,  2.11it/s]

Batch 593 processed and saved to non-llm-author-affiliations/gpt_responses_batch_593.csv

Processing batch 594: 100%|██████████| 200/200 [01:39<00:00,  2.02it/s]

Batch 594 processed and saved to non-llm-author-affiliations/gpt_responses_batch_594.csv

Processing batch 595: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]

Batch 595 processed and saved to non-llm-author-affiliations/gpt_responses_batch_595.csv

Processing batch 596: 100%|██████████| 200/200 [01:41<00:00,  1.97it/s]

Batch 596 processed and saved to non-llm-author-affiliations/gpt_responses_batch_596.csv

Processing batch 597: 100%|██████████| 200/200 [01:41<00:00,  1.98it/s]

Batch 597 processed and saved to non-llm-author-affiliations/gpt_responses_batch_597.csv

Processing batch 598: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 598 processed and saved to non-llm-author-affiliations/gpt_responses_batch_598.csv

Processing batch 599: 100%|██████████| 200/200 [01:53<00:00,  1.77it/s]

Batch 599 processed and saved to non-llm-author-affiliations/gpt_responses_batch_599.csv

Processing batch 600: 100%|██████████| 200/200 [01:34<00:00,  2.12it/s]

Batch 600 processed and saved to non-llm-author-affiliations/gpt_responses_batch_600.csv

Processing batch 601: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 601 processed and saved to non-llm-author-affiliations/gpt_responses_batch_601.csv

Processing batch 602: 100%|██████████| 200/200 [01:44<00:00,  1.92it/s]

Batch 602 processed and saved to non-llm-author-affiliations/gpt_responses_batch_602.csv

Processing batch 603: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

Batch 603 processed and saved to non-llm-author-affiliations/gpt_responses_batch_603.csv

Processing batch 604: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]

Batch 604 processed and saved to non-llm-author-affiliations/gpt_responses_batch_604.csv

Processing batch 605: 100%|██████████| 200/200 [01:39<00:00,  2.01it/s]

Batch 605 processed and saved to non-llm-author-affiliations/gpt_responses_batch_605.csv

Processing batch 606: 100%|██████████| 200/200 [01:43<00:00,  1.94it/s]

Batch 606 processed and saved to non-llm-author-affiliations/gpt_responses_batch_606.csv

Processing batch 607: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 607 processed and saved to non-llm-author-affiliations/gpt_responses_batch_607.csv

Processing batch 608: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 608 processed and saved to non-llm-author-affiliations/gpt_responses_batch_608.csv

Processing batch 609: 100%|██████████| 200/200 [01:39<00:00,  2.00it/s]

Batch 609 processed and saved to non-llm-author-affiliations/gpt_responses_batch_609.csv

Processing batch 610: 100%|██████████| 200/200 [01:42<00:00,  1.96it/s]

Batch 610 processed and saved to non-llm-author-affiliations/gpt_responses_batch_610.csv

Processing batch 611: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 611 processed and saved to non-llm-author-affiliations/gpt_responses_batch_611.csv

Processing batch 612: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 612 processed and saved to non-llm-author-affiliations/gpt_responses_batch_612.csv

Processing batch 613: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 613 processed and saved to non-llm-author-affiliations/gpt_responses_batch_613.csv

Processing batch 614: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 614 processed and saved to non-llm-author-affiliations/gpt_responses_batch_614.csv

Processing batch 615: 100%|██████████| 200/200 [01:47<00:00,  1.86it/s]

Batch 615 processed and saved to non-llm-author-affiliations/gpt_responses_batch_615.csv

Processing batch 616: 100%|██████████| 200/200 [01:36<00:00,  2.08it/s]

Batch 616 processed and saved to non-llm-author-affiliations/gpt_responses_batch_616.csv

Processing batch 617: 100%|██████████| 200/200 [01:42<00:00,  1.95it/s]

Batch 617 processed and saved to non-llm-author-affiliations/gpt_responses_batch_617.csv

Processing batch 618: 100%|██████████| 200/200 [01:35<00:00,  2.09it/s]

Batch 618 processed and saved to non-llm-author-affiliations/gpt_responses_batch_618.csv

Processing batch 619: 100%|██████████| 200/200 [01:33<00:00,  2.14it/s]

Batch 619 processed and saved to non-llm-author-affiliations/gpt_responses_batch_619.csv

Processing batch 620: 100%|██████████| 200/200 [01:28<00:00,  2.26it/s]

Batch 620 processed and saved to non-llm-author-affiliations/gpt_responses_batch_620.csv

Processing batch 621: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]

Batch 621 processed and saved to non-llm-author-affiliations/gpt_responses_batch_621.csv

Processing batch 622: 100%|██████████| 200/200 [01:37<00:00,  2.05it/s]

Batch 622 processed and saved to non-llm-author-affiliations/gpt_responses_batch_622.csv

Processing batch 623: 100%|██████████| 200/200 [01:43<00:00,  1.93it/s]

Batch 623 processed and saved to non-llm-author-affiliations/gpt_responses_batch_623.csv

Processing batch 624: 100%|██████████| 51/51 [00:26<00:00,  1.93it/s]

Batch 624 processed and saved to non-llm-author-affiliations/gpt_responses_batch_624.csv

In [42]:
folder_path3 = "non-llm-author-affiliations"

df3 = matcher.process_affiliation(df3)
affiliation_df3 = df3['affiliation_strings'].explode().value_counts().reset_index()
compile_df3 = matcher.compile_files(folder_path3)
compile_df3 = compile_df3.rename(columns={'affiliation_string': 'affiliation_strings'})
mapped_affiliation_df3 = matcher.create_affiliation_mapping(affiliation_df3, compile_df3)

df3 = matcher.process_departments(df3)
df3 = calculator.calculate_all_entropies(df3)
df3.to_csv('non-llm-information-entropy.csv',index=False)
df3.head(5)

100%|██████████| 73110/73110 [00:00<00:00, 762555.21it/s]

Calculating entropy for country_codes...
Calculating entropy for institutions...
Calculating entropy for departments...

,id,doi,title,abstract,publication_year,publication_date,created_date,type,cited_by_count,is_retracted,...,datetime,author_names,institutions,country_codes,institution_types,affiliation_strings,departments,country_codes_entropy,institutions_entropy,departments_entropy
209011,https://openalex.org/W2290907386,https://doi.org/10.46632/rmc/2/4/9,Prediction of diabetes Using an Artificial Neu...,Diabetes is a widespread illness for which the...,2021,2021-12-01,2016-06-24,article,38.0,False,...,2021-12-01,[Mayra Lachhani],"[G.S. Science, Arts And Commerce College]",[IN],[education],"[SSt College of Arts and Commerce, Maharashtra...",[Arts and Commerce],-0.000000,-0.000000,-0.0
161377,https://openalex.org/W41175702,https://doi.org/10.2427/8874,Description of survival data extended to the c...,Survival analysis is a powerful statistical to...,2022,2022-06-30,2016-06-24,article,1.0,False,...,2022-06-30,"[Davide Paolo Bernasconi, Laura Antolini]","[University of Milano-Bicocca, University of M...","[IT, IT]","[education, education]","[University of Milano-Bicocca, University of M...",[],-0.000000,-0.000000,NaN
176359,https://openalex.org/W2364927470,https://doi.org/10.1257/aer.20160600,The Taxing Deed of Globalization,This paper examines the effects of globalizati...,2019,2019-01-29,2016-06-24,article,81.0,False,...,2019-01-29,"[Peter Egger, Sergey Nigai, Nora Strecker]","[ETH Zurich, University of Colorado Boulder, E...","[CH, US, CH]","[education, education, education]","[ETH Zürich, KOF, LEE G101, Leonhardstrasse 21...",[Economics],0.918296,0.918296,-0.0
164838,https://openalex.org/W2341235562,https://doi.org/10.47536/jcrm.v11i2.618,Increasing numbers of ship strikes in the Cana...,"The Canary Islands, known for their extraordin...",2023,2023-02-14,2016-06-24,article,69.0,False,...,2023-02-14,"[Manuel Carrillo, Fabian Ritter]",[Gobierno de Canarias],[ES],"[government, None]","[CANARIAS CONSERVACIÓN, Maya 8, 38204 La Lagun...",[],-0.000000,-0.000000,NaN
204295,https://openalex.org/W2189310174,https://doi.org/10.18260/1-2--16113,Applications And Confidence Inventories For As...,Abstract NOTE: The first page of text has been...,2020,2020-09-03,2016-06-24,article,2.0,False,...,2020-09-03,"[Lisa Schneider, Maria Shea Terrell]","[Cornell University, Cornell University]","[US, US]","[education, education]","[Cornell University, Learning Initiatives in C...","[Engineering, Math]",-0.000000,-0.000000,1.0